### ISSUE TITLE
Governance update

### ISSUE THREAD

**Issue by Swader** [w3f/polkadot-wiki#1000]
> After being turned into a council motion, the proposal needs 51% of the council to approve it to pass, or 51% to reject it to fail. If majority is not reached, the proposal remains in limbo - neither accepted nor rejected until more council members weigh in.

Governance page.

This is incorrect, the thresholds are different on the respective networks.

**Comment by lsaether** [comment]
I think the thresholds are the same on both Kusama and Polkadot, but they are different for approve or reject motions.

EDIT: They look different also because the different number of councilors on Kusama and Polkadot
