### ISSUE TITLE
Ledger Set up: Replace screenshot of Account Type & Index

### ISSUE THREAD

**Issue by ghost** [w3f/polkadot-wiki#1014]
Can the screenshot that currently shows "Account type 1 and Index 2" please be replaced with the default settings of 0 and 0 in order not to mislead users. 
It would also be good to point out that regular users should just leave the default settings. They should only be changed if people know what they are doing. 

https://wiki.polkadot.network/docs/en/learn-ledger#loading-your-account

**Comment by Swader** [comment]
Yes, updating!
