### ISSUE TITLE
Add our official Discord community to learn-scams

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#1036]
https://discord.com/channels/722223075629727774/730471473562779779

**Comment by krichard410** [comment]
@laboon I don't think this link is working...I tried it from my Discord account and it gave me this:

<img width="492" alt="Screen Shot 2020-09-28 at 2 05 00 PM" src="https://user-images.githubusercontent.com/36748441/94430057-9a91d180-0193-11eb-9a2e-91189eee687a.png">

**Comment by Swader** [comment]
When creating an invite on Discord, there's a little checkbox that says "don't expire" or something like that. It defaults to 24 hour links.

**Comment by laboon** [comment]
Please use this link: https://discord.gg/wGUDt2p
