### ISSUE TITLE
Document Runtime Upgrades

### ISSUE THREAD

**Issue by joepetrowski** [w3f/polkadot-wiki#1039]
I was rather surprised that we don't have a page or even section on runtime upgrades. Should include:

- Runtime upgrade overview
  - Similarities and differences to a hard fork
  - "There's a new client release, when do I need to update by?"
- What does it mean if I am a ______?
  - Validator -> probably nothing, check client release notes for urgency
  - Nominator -> definitely nothing, just relax, man
  - Infrastructure provider (block explorer, exchange) -> update parsing logic, sidecar, may be new types
  - Wallet -> watch out for tx broadcasting (i.e. don't construct with spec `n` and broadcast with spec `>n`)
- How to monitor for changes (see below)

1. Monitor chain for `democracy.Started` events and log `index` and `blockNumber`.
2. Get `pallets/democracy/storage/ReferendumInfoOf?key1=index&at=blockNumber` from Sidecar to get the referendum info. It should have a status of `Ongoing`. Find ending block number (`end`) and the enactment delay (`delay`).
3. Execution block number will be `end + delay`.
4. Monitor chain for `democracy.Passed`, `democracy.NotPassed`, or `democracy.Cancelled` events citing the index. If `Passed`, need to look at `scheduler.Scheduled` event in same block for enactment block.
5. Monitor chain for `democracy.PreimageNoted` events with the same hash as the `ReferendumInfoOf(index)` item, may be up to the last block before execution, but will not work if this is missing.
6. Monitor chain for `democracy.Executed` events for actual execution. In the case of a runtime upgrade, there will also be a `system.CodeUpdated` event.

**Comment by laboon** [comment]
@DannyS03 please look into this, double-check what has changed (extrinsic names etc.), and add a page for this
