### ISSUE TITLE
Add PANIC to the monitoring part of the Polkadot wiki

### ISSUE THREAD

**Issue by dillu24** [w3f/polkadot-wiki#1048]
Given that [PANIC](https://github.com/SimplyVC/panic_polkadot) was supported by the W3F foundation via a grant, it should be mentioned in the Polkadot wiki as a way for monitoring your nodes. The advantage of PANIC is that it does not only monitor the availability of the nodes, but also the state on chain.

**Comment by salmad3** [comment]
Has been previously added to Wiki.
