### ISSUE TITLE
Abstract away the stale-check Github Action so others can use it

### ISSUE THREAD

**Issue by Swader** [w3f/polkadot-wiki#1064]
Our wiki now has a cronbot which checks for documents which have not been edited more than 21 days. If found, it will make 2 issues for such documents every 12 hours (to not overwhelm the issue list). The logic is in `scripts/stalecheck.js`. While the action is currently invoked from within `.github\workflows\stalecheck.yml`, we would like this solution abstracted into a **two** public actions. 

Action "find_old_docs":

INPUTS:

- max age of document
- folder(s) which contain the document(s)

OUTPUTS:

- object matching file paths and their age, like so:

```json
{
"docs/hello.md": 32,
"lib/world.md": 21
}
```

Action "issues_for_old_docs":

Creates an issue for each old document in the list.

INPUTS:

- list of old docs (See above)
- max (number of issues to create)
- labels: list of labels to apply
- assignees: list of assignees to apply
- randassignees: list of assignees from which to pick one at random for each issue create (mutually exclusive with `assignees`)

OUTPUTS:

- none

**Comment by salmad3** [comment]
While the concept is great, we can close this issue based on the discussion regarding removing the stale check. Please reopen if otherwise.
