### ISSUE TITLE
Community page is out of date - Riot is now Element

### ISSUE THREAD

**Issue by danforbes** [w3f/polkadot-wiki#1077]
This page references multiple Riot chats, which should be updated to use Element instead.

**Comment by nuke-web3** [comment]
Possibly via matrix.to link

substrate dev chat would be this: https://matrix.to/#/!HzySYSaIhtyWrwiwEV:matrix.org

Thus a user could easily choose a client (element being the most popular, but there is a rust based one some of the community might like to checkout as well that invite page mentions: https://matrix.org/docs/projects/client/fractal )

**Comment by Swader** [comment]
Resolved in a recent update

**Comment by Swader** [comment]
Resolved in a recent update
