### ISSUE TITLE
Document refcount and looking at references

### ISSUE THREAD

**Issue by Swader** [w3f/polkadot-wiki#1101]
![image](https://user-images.githubusercontent.com/1430603/95437119-e6dbcf00-0954-11eb-9b6f-c0663878b013.png)

![image](https://user-images.githubusercontent.com/1430603/95437156-f1966400-0954-11eb-8999-215d9e85a7cf.png)

**Comment by lsaether** [comment]
nice, thanks for screenshots

**Comment by Swader** [comment]
Will no longer allow toggling keepalive: https://github.com/polkadot-js/apps/pull/3990

**Comment by jakehemmerle** [comment]
Will add link to new wiki page and reference this near reaping transfers

**Comment by jakehemmerle** [comment]
@joepetrowski  Gav in reason 4 above references a chain state key called `staking.Payout` but this does not exist. I also see the `kill_stash` function at https://github.com/paritytech/substrate/blob/8060a437dc01cc247a757fb318a46f81c8e40d5c/frame/staking/src/lib.rs#L2397 but I'm not sure where to see which extrinsics trigger this.

Do you have any other ideas on how to check for staking set information and remove it?

'reference-issues' is my WIP branch for reference

**Comment by joepetrowski** [comment]
Reference counting has changed quite significantly since those screenshots. I would recommend starting from scratch and looking at the System module.

> I also see the kill_stash function but I'm not sure where to see which extrinsics trigger this.

You will have to do some more digging :smile: It might not be called directly in the lib.rs but there are a few functions that will invoke it.
