### ISSUE TITLE
Contributors

### ISSUE THREAD

**Issue by ansonla3** [w3f/polkadot-wiki#112]
Add a page that list out all contributors / maintainers

**Comment by Swader** [comment]
This should be something auto-generated from commit history. Which also begs the question, how are Crowdin submissions represented in the commits?

**Comment by lsaether** [comment]
I think @ansonla3 meant something like what the research team has [on their page](https://research.web3.foundation/en/latest/research_team_members.html).

@Swader What you describe is basically just the GitHub contributors list?

**Comment by Swader** [comment]
Yeah, though pretty visualizations of that are possible, thought @ansonla3 meant that. @ansonla3 can you clarify?

**Comment by ansonla3** [comment]
@Swader @lsaether  yep, a page that shows the main contributors with an image and some description

**Comment by Swader** [comment]
So kind of like our team members page in Notion, with shorter bios instead of the longer ones. We could do that.
