### ISSUE TITLE
Do not post duplicate stale page issues if one is already open

### ISSUE THREAD

**Issue by lsaether** [w3f/polkadot-wiki#1138]
Currently the stale page issue bot will post a duplicate issue for a page if it has not been updated yet and there's already an issue open. Instead, it should check if there's an open issue and ping the assignee to update it.

See for example #1071 and #1127 or #1069 and #1123 for indication of duplicated issues.

**Comment by Swader** [comment]
There is a check for that in the bot but apparently it's failing. Checking...
