### ISSUE TITLE
Kusama parameters link on Polkadot parameters page 404s

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#1193]
https://wiki.polkadot.network/docs/en/maintain-polkadot-parameters

links to https://wiki.polkadot.network/docs/en/kusama-parameters

This 404's

Correct page is now https://guide.kusama.network/docs/en/kusama-parameters

Link to that page DOES work from https://guide.kusama.network/docs/en/maintain-polkadot-parameters

Why didn't our link checker catch this?

**Comment by lsaether** [comment]
IIRC it's because the link checker only checks external links and not links that direct to other pages of the wiki.

@fgimenez was working on the regex a while back, maybe he can clarify.

**Comment by laboon** [comment]
This works now, not sure what fixed it, but yay
