### ISSUE TITLE
Auto-merge "New Crowdin Updates"

### ISSUE THREAD

**Issue by lsaether** [w3f/polkadot-wiki#1201]
Would be nice to have a bot that merges crowdin updates as long as they pass CI.

@ansonla3 is there a possible option on Crowdin to auto-merge the new updates from Crowdin?

**Comment by ansonla3** [comment]
it would still be better to keep it manually since that avoids merging error contents in the master.

**Comment by lsaether** [comment]
Oh ok, do you read over them before merging? Should I stop merging them in?

**Comment by ansonla3** [comment]
yep. I would check before merging it
