### ISSUE TITLE
The description in the wiki render is invalid

### ISSUE THREAD

**Issue by Swader** [w3f/polkadot-wiki#122]
![image](https://user-images.githubusercontent.com/1430603/67811651-8e8e2300-fa9d-11e9-8090-a2e353fa2be5.png)

This causes renders in social media, slack, and other previews to look weird.

**Comment by lsaether** [comment]
Will take a look into this, not sure where this is set in docusaurus configuration.

**Comment by lsaether** [comment]
What page does this show up on?

**Comment by lsaether** [comment]
Should be fixed now. It was caused by placing an image tag on the first line of a docs page. The description is generated by taking the first line of the markdown file for whatever page is being linked. 

Please re-open if you notice the problem again.
