### ISSUE TITLE
Secure Validator Sentry

### ISSUE THREAD

**Issue by andresilva** [w3f/polkadot-wiki#124]
Instruct users to set the `--sentry` flag on public nodes.

**Comment by Swader** [comment]
Can we please get some context on this, preferably a list of most up to date writeups on sentries if any exist?

**Comment by andresilva** [comment]
Check the description in `--help` please, I can answer any follow-up questions.

**Comment by laboon** [comment]
Anson are you working on this?

**Comment by ansonla3** [comment]
@laboon yep
