### ISSUE TITLE
Add slashing grace period to wiki on slashing page

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#1259]
So that way the slashes work -

once a validator gets slashed, it goes into the state as an "unapplied slash" (these are viewable by all, the apps UI shows it per validator and then all the affected parties along with the amounts)
while unapplied, a proposal can be made (during this period, 7 days on Kusama), to reverse it
after this grace period, the slashes are applied

**Comment by ansonla3** [comment]
#1281
