### ISSUE TITLE
Document uncle rewards

### ISSUE THREAD

**Issue by Swader** [w3f/polkadot-wiki#130]
https://research.web3.foundation/en/latest/polkadot/Token%20Economics/#payment-details

_(the exact values of the point system are up for discussion. There are no good reasons for those exact values)_

Validators get paid for different actions. Both to the block producer who includes a reference to an uncle block, and the author of the uncle block are paid.

We pay more to the former. The logic is that the system doesn't really benefit from uncle blocks, but it does benefit from having a record that an uncle block exists, so we can detect equivocations (i.e. the block producer deciding to create two blocks at the same height). I guess it made sense in PoW where uncle rewards were a consolation for wasted energy to no fault of the miner (latency, instead), but here the cost of block production is nothing.

Best location - learn-dot? learn-consensus? Leaning towards learn dot, plus a mention in learn-consensus with link.

**Comment by lsaether** [comment]
Should go in `maintain-guides-validator-payout` with links / references wherever applicable.
