### ISSUE TITLE
Rust toolchain version is not compatible with v0.8.26

### ISSUE THREAD

**Issue by laishulu** [w3f/polkadot-wiki#1352]
I think there is incompatibility between v0.8.26-1 and the rust toolchain mentioned in the wiki
I can't build v0.8.26-1 successfully using the toolchain I used to build v0.8.25

**Comment by lsaether** [comment]
Thanks! If you could answer a couple questions it would help us fix it faster.

Where is the mention of the toolchain? What toolchain were you trying to use?

**Comment by laishulu** [comment]
https://wiki.polkadot.network/docs/en/maintain-guides-how-to-validate-polkadot

<img width="775" alt="图片" src="https://user-images.githubusercontent.com/1224321/100739929-d9057000-3412-11eb-9df8-21d4a47f8ebe.png">

**Comment by laishulu** [comment]
@lsaether Any progress?

**Comment by laishulu** [comment]
the wiki is aalready updated.
