### ISSUE TITLE
Reading blockchain parameters from the chain

### ISSUE THREAD

**Issue by Swader** [w3f/polkadot-wiki#136]
There are several bits of information in the wiki which get outdated easily, whenever a parameter in Kusama (and later Polkadot) changes. E.g. the validator count going from 25, to 50, to 100. The council mandate duration going from 100 blocks, to 2 hours, to 1 year(?). The number of parachain slots, the reward distribution, and more.

My suggestion is making a simple script we could slap into the docusaurus output template which would, on each render or each CI run fetch these values from the live blockchain and replace template values with them. For example, instead of writing "Council members remain in position for 1 year unless voted out by a referendum" you'd write "Council members remain in position for {{COUNCIL_DURATION || 1 year}}" and the script would fetch council duration straight from the chain, translate to human readable value, and replace the template. If it doesn't find a value it defaults to "1 year".

This would also be a nice side project, a super-lightweight JS package for reading chain params, which would then be usable by others as well (block explorers, for example).

This is maybe a good target for Hackusama?

**Comment by lsaether** [comment]
Sure, it could also be a candidate for a small bounty.

**Comment by ansonla3** [comment]
good idea

**Comment by dreecer1** [comment]
Good idea, I'll add as a tooling challenge for Hackusama. If it gets done before early Jan, we can always remove it.

**Comment by lsaether** [comment]
Being done in #177
