### ISSUE TITLE
Reorganize community page to prioritize discord / other?

### ISSUE THREAD

**Issue by nuke-web3** [w3f/polkadot-wiki#1371]
https://github.com/w3f/polkadot-wiki/blob/master/docs/community.md

I see the matrix section is first up, and much further down we find discord `RECOMMENDED` , should this be moved up and further highlighted to encourage this being the first thing found on the page?

**Comment by nuke-web3** [comment]
might be worth highlighting that matrix and telegram are bridged there as well, so it's a lot less to get in on all the groups - just discord for (most) coms.

**Comment by joepetrowski** [comment]
No, Matrix is our primary chat tool. Why is Discord even marked as recommended?

**Comment by joepetrowski** [comment]
Well, OK maybe it's recommended over telegram. This page looks fine with Matrix as the primary section and Telegram/Discord at the bottom.
