### ISSUE TITLE
Update block times on FAQ?

### ISSUE THREAD

**Issue by nuke-web3** [w3f/polkadot-wiki#1373]
https://wiki.polkadot.network/docs/en/faq#what-is-the-expected-block-time-on-the-relay-chain

I suspect now that we have a few million blocks to look at, this can be updated? 😉 
6 second target, ya?

**Comment by laboon** [comment]
A few million blocks isn't much in the grand scheme of things...

**Comment by laboon** [comment]
made a PR to fix this and a few other things I noticed in the FAQ
