### ISSUE TITLE
Guide: Making a Treasury Proposal

### ISSUE THREAD

**Issue by lsaether** [w3f/polkadot-wiki#140]
We need a step-by-step guide for how one could make spends from the treasury.

**Comment by Swader** [comment]
That's just a few button clicks - we should probably then also document the social process of determining what that proposal refers to, and what the funds are going towards. 

Where would these discussions take place? Would it be an okay idea to create a Treasury category in [the forum](https://forum.web3.foundation/) and have suggestions be discussed there? Or maybe even a separate "Polkadot Governance" forum (perhaps on something better than Discourse, which isn't a high bar really), which would have a Polkadot and a Kusama main category with Governance and Treasury as subcategories in each?

This brings in a degree of centralization, but if the w3f is stewarding the forum I think people will feel safe about it. They can always create other venues to discuss proposals in I suppose if they dislike this.

**Comment by lsaether** [comment]
It's still up in the air. A few suggestions have been discussed:

- A Discourse forum. [We already have this for Kusama](https://forum.kusama.network/). So far Melea has been most active in updating it for the council and validator communities.
- We use [Commonwealth](https://commonwealth.im/). It's kinda being designed for governance discussion but that doesn't mean we have to use it.
- Riot room. We have these now too, but many people complain about the ephemeral nature of messages.
- A GitHub repository like the PSPs for Polkadot Governance Proposals (PGPs).
- A Discord server. Some people prefer Discord over Riot because it's easier to moderate and is less buggy and ephemeral. I'm mehh on this option.

The developer in me wants to create a GitHub repository so it can have nice interlinking with code changes, commits, and pull requests / issues. We could try this for Kusama by creating a Kusama Governance Proposals repository.

**Edit:** [KGPs](https://github.com/kusamanetwork/KGPs) if it's a bad idea we can delete it.

**Comment by Swader** [comment]
Related to #227

**Comment by Swader** [comment]
@ansonla3 are you working on this? If not I'd like to take it along with a treasury page overhaul.

**Comment by ansonla3** [comment]
@Swader hey, go-ahead. I have tried a few times already last week that seems not working at all.
