### ISSUE TITLE
Update learn-registrar.md

### ISSUE THREAD

**Issue by jonasW3F** [w3f/polkadot-wiki#1432]
I wanted to set an on-chain identity using the registrar and I found some inaccurate information in the wiki and some potential to add further explanations.

1) The fee is communicated to be 1 DOT or 0.04 KSM but @lamafab told me that the fee is actually 0 right now?
2) It should be mentioned that a user needs a "basic deposit" (for DOT 20.2580, don't know about KSM) to set the identity. This could be phrased as a "requirement"? Also, it is not clear what that deposit actually means. Are the funds locked or bonded? If yes, for how long? And what happens to the identity if a user withdraws the funds from the address (and only leaves the existential amount)?

**Comment by lsaether** [comment]
> The fee is communicated to be 1 DOT or 0.04 KSM but @lamafab told me that the fee is actually 0 right now?

That's totally news to me. I asked @lamafab when it first launched about the fee but maybe this has changed in the meantime?

**Comment by ansonla3** [comment]
@lamafab I remember 1. should be effective. does it change?

**Comment by jonasW3F** [comment]
Requesting judgment with 0 fee worked on Polkadot but on Kusama gave a `system.ExtrinsicFailed identity.FeeChanged ` error... Using the 0.04 KSM worked.

**Comment by laboon** [comment]
@lamafab verifies it is currently 0 although may change.  PR to fix is #1463 if someone wants to review.
