### ISSUE TITLE
Feedback from new validator

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#1455]
- The validator install doc on the wiki is out of date. With Debian 10
the install is purely DEB based and does not require self-compile. The
parity github doc provides better info.
- The W3 community telemetry incorrectly identifies all validators as
being in Frankfurt - that should be fixed

**Comment by laboon** [comment]
https://github.com/paritytech/polkadot

**Comment by salmad3** [comment]
Will be addressed in: https://github.com/w3f/polkadot-wiki/issues/2147
