### ISSUE TITLE
Need more clarification in learn-governance.md

### ISSUE THREAD

**Issue by jonasW3F** [w3f/polkadot-wiki#1459]
I looked up information on the conviction multiplier and was referred to "Voluntary locking". Only reading this subsection, I found a few things confusing:

1) I was looking for some human readable conversion of "periods" but was not able to find it quickly. How long is 1 period? I guess it is fixed and we could add one (or two if it is different for Kusama) columns and translate it to days / weeks? This gives a much better feel of what it means to use some of that multipliers.
2) It says  
> The maximum number of lock periods is set to 6 and the lock period is 30 days on Polkadot and eight days on Kusama.

But in the table the maximum lock period is 32. 

Maybe reading the whole governance section would make this clearer but it probably should be a little bit more self-contained.

**Comment by laboon** [comment]
Yeah it means "6 doublings" (1,2,4,8,16,32).  I think changing that wording would help it out.

**Comment by laboon** [comment]
@jonasW3F How does this look?  can you review? https://github.com/w3f/polkadot-wiki/pull/1460

**Comment by laboon** [comment]
fixed by #1460
