### ISSUE TITLE
Beginner's Page

### ISSUE THREAD

**Issue by lsaether** [w3f/polkadot-wiki#15]
We should have a page for someone that is totally new to Polkadot and introduces the major concepts using some videos and light articles.

**Comment by laboon** [comment]
Let's make this high priority for February.  Lots of questions about this.

**Comment by krichard410** [comment]
@lsaether Is it alright if I close this issue? I had created a Get Started page on the wiki :)

**Comment by lsaether** [comment]
Yep!
