### ISSUE TITLE
Add validator stats to output minimum token bond needed for effective nomination

### ISSUE THREAD

**Issue by Swader** [w3f/polkadot-wiki#1554]
https://github.com/w3f/validator-stats

**Comment by laboon** [comment]
Initial issue is obsolete - but we should put this information in:

Adjust to discuss the new nomination limits:

Max # validators: self-explanatory (1200 on Polkadot)
Max # nominators: self-explanatory (22500 on Polkadot)
Minimum DOT to validate: self-explanatory (currently 1 DOT)
Minimum to nominate: if `x`, you cannot nominate with less than `x` stake. if you are already nominating, then you can be forced to stop if your stake is  < `x` using the chill_other extrinsic. However, see below. (currently 40 DOT, most likely increasing to 80 soon)
Chill %: ( 90% ) If the total number of nominators < chill_percent * max number, then chill_other cannot be used.

https://polkadot.polkassembly.io/motion/103

**Comment by laboon** [comment]
Put information in https://wiki.polkadot.network/docs/learn-staking

and reference it in https://wiki.polkadot.network/docs/maintain-guides-how-to-nominate-polkadot
