### ISSUE TITLE
Create a Guides section

### ISSUE THREAD

**Issue by Swader** [w3f/polkadot-wiki#1569]
The section would contain all the getting started content + really simple guides on doing basic things. No technical explanations, just links to more complex versions of the guides (in learn / maintain / build). More picture-focused, where possible accompanied by video explainers. The guides section should be enough for a user to use ALL of Polkadot to its fullest extent, as much as "civilian" should be able to.

**Comment by Juan-DiegoC** [comment]
Were you envisioning something like [this](https://guides.github.com/)?

**Comment by Swader** [comment]
Yes, that's the inspiration behind the idea. Keeping it suuuuuper simple.

**Comment by salmad3** [comment]
Being revisited in: https://github.com/w3f/polkadot-wiki/pull/2392
