### ISSUE TITLE
Rephrase Crowdfunding to Crowdloan

### ISSUE THREAD

**Issue by wpank** [w3f/polkadot-wiki#1583]
https://wiki.polkadot.network/docs/en/learn-parachains#crowdfunding-parachains

There's a lot of pages like this that can use a refresh for language: crowdloan is the politically correct term to use now.

**Comment by joepetrowski** [comment]
We should probably make crowdloans their own page. And on the parachains page not just give the case when a parachain's lease ends and it retires. This is obviously one case, but it should also state that parachains can renew so it doesn't seem like retirement just happens.
