### ISSUE TITLE
SEO - parachain page

### ISSUE THREAD

**Issue by Swader** [w3f/polkadot-wiki#1586]
The first bit of content on the Parachain page is an image, which reflects poorly in social media previews:

![image](https://user-images.githubusercontent.com/1430603/104574471-5816d680-5656-11eb-9549-231e91c2c1a6.png)

Solution is to add a description meta field to the parachain page frontmatter which would get picked up by previews instead.

**Comment by emresurmeli** [comment]
Fixed in PR #1595
