### ISSUE TITLE
Unclear Kusama ED

### ISSUE THREAD

**Issue by TheTrunk** [w3f/polkadot-wiki#1596]
Hello,
From wiki it is not clear what the ED of Kusama network is

- https://wiki.polkadot.network/docs/en/build-protocol-info 
   - Mentions 0.01KSM
- https://wiki.polkadot.network/docs/en/learn-accounts
   - Mentions 0.001666666667KSM

Thank you for clarification and wiki correction.

**Comment by Swader** [comment]
Thanks for reporting, fixed!
