### ISSUE TITLE
Kusama Section

### ISSUE THREAD

**Issue by lsaether** [w3f/polkadot-wiki#16]
Evaluate integrating all Kusama content into the wiki in it's own "Kusama" section. This would make it easier to maintain as a single repository but may clutter up the Polkadot wiki unnecessarily.

**Comment by laboon** [comment]
I think we should be doing this.  Kusama userguide is getting more out-of-date and harder to keep track of. 

Maybe a landing page on the polkadot wiki that guide.kusama.network points to?
