### ISSUE TITLE
Dynamic value placeholders have not been replaced on Kusama treasury page

### ISSUE THREAD

**Issue by alxs** [w3f/polkadot-wiki#1603]
See [here](https://guide.kusama.network/docs/en/mirror-learn-treasury).
For example, on the first paragraph:

> ...with current defaults set to {{ spend_period }} days for Polkadot

I've had a quick look and it seems to be the only page where this is the case.

**Comment by Swader** [comment]
Thanks for reporting, taking a look!

**Comment by Swader** [comment]
Fix failed :(

**Comment by Swader** [comment]
Still not good :(

**Comment by alxs** [comment]
This issue was fixed by @lsaether [here](https://github.com/w3f/polkadot-wiki/commit/da71fae03a1f06a6463612bdc2a68456a8979ad0) as discussed in the above PR.
