### ISSUE TITLE
Update SRML and other links 

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#162]
Parity has changed the Substrate directory structure.  Update all links.

**Comment by Swader** [comment]
@fgimenez any progress on CI with html validator? I can't tag pantelis here 🤔

**Comment by lsaether** [comment]
Advice from Parity docs team is to hold off on this for another week in case there's any further changes after digesting the new terms.

**Comment by Swader** [comment]
I think we're settled on Pallet now, no?

**Comment by lsaether** [comment]
Yes

**Comment by Swader** [comment]
Re-pinging @fgimenez on CI link-checker integration

**Comment by fgimenez** [comment]
@Swader sorry for the very late response, proposed here #198

**Comment by laboon** [comment]
This was fixed by #243
