### ISSUE TITLE
Old grafana dash needs updating

### ISSUE THREAD

**Issue by Swader** [w3f/polkadot-wiki#1652]
https://github.com/paritytech/substrate/tree/master/.maintain/monitoring/grafana-dashboards - new dashes, the one from https://wiki.polkadot.network/docs/en/maintain-guides-how-to-monitor-your-node#alertmanager-integration is out of date.

**Comment by FlorianFranzen** [comment]
Just to add to this: A lot of the panels no longer have a valid data source since the system and process metrics were removed in paritytech/substrate#6822.

**Comment by salmad3** [comment]
Will be addressed in: https://github.com/w3f/polkadot-wiki/issues/2177

**Comment by salmad3** [comment]
https://github.com/w3f/polkadot-wiki/issues/2192#issuecomment-893716342
