### ISSUE TITLE
Multisig deposits - add to multisig info

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#1677]
Each account should be funded with enough tokens in order to pay the multisig reverve (3.34 KSM or 20.152 DOT).
For any multisig transaction the initiator for that transaction needs to have about 3.4 KSM in their account.  
To create an anonymous proxy the account creating the proxy needs to have 3.4 KSM
To create an anonymous proxy controlled by a multisig, both the initiator and the multisig account need to have 3.4 KSM.

**Comment by Swader** [comment]
IIRC this amount will vary depending on number of members in multisig.
