### ISSUE TITLE
"maintain" -> "stake" or changing home page of /maintain

### ISSUE THREAD

**Issue by jplatts12** [w3f/polkadot-wiki#168]
Add governance council to main page on https://wiki.polkadot.network/docs/en/maintain-index

OR another option would be to change this page from "Maintain" to "Stake" since collators, nominators and validators are all staking. Then move the council stuff to wiki more on governance

**Comment by lsaether** [comment]
Fixed in https://github.com/w3f/polkadot-wiki/commit/33d7f190449facb5591e6f57e199b7817e117078
