### ISSUE TITLE
Fix PDF generation

### ISSUE THREAD

**Issue by whitesunset** [w3f/polkadot-wiki#1695]
Self assigned

**Comment by Swader** [comment]
Currently the action makes a PDF document, but we don't host it anywhere for download. One option is to commit to repo but that bloats the history IMMENSELY, so let's not do that. Another is to upload it to IPFS and then reference the IPFS link in the footer / header of the wiki somewhere, which is more dogfooding, and stays online despite server accessibility, so let's try that approach. We can use the IPFS HTTP client we already have as a dependency on the wiki.

**Comment by Swader** [comment]
With #2112 the PDF generator has TOC and page exclusion lists, both features we requested to make PDF generation much more consistent and practical. This should be revisited.

**Comment by salmad3** [comment]
Most Recent linked Issue will see this revisited once IPFS is up and running.
