### ISSUE TITLE
Github link in footer is wrong

### ISSUE THREAD

**Issue by hirschenberger** [w3f/polkadot-wiki#1765]
The github link in the footer of all wiki pages that should link to `https://github.com/paritytech/polkadot` is wrong.

https://github.com/w3f/polkadot-wiki/blob/a5246ed33bda68543e387ab323a6ba9a9510dc34/website/core/Footer.js#L54

**Comment by Swader** [comment]
Thanks for the heads up, will be fixed in #1770
