### ISSUE TITLE
Feedback from Tomasz on bridges

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#1798]
Related to this - https://wiki.polkadot.network/docs/en/learn-bridges#types-of-bridges

"Honestly I see this repeated many times, but I never understand the split between Bridge modules and Bridge contracts.

For instance Ethereum bridge is a smart contract on Ethereum (obviously) but a pallet (assuming "a bridge module") on the Polkadot side.
Kusama <> Polkadot bridge is a bunch of pallets that need to be included on (relay/para) chains on both networks.
The bridge should always imply bi-directional communication, while it's possible to have one-way bridge which is what I kind of read from the "Bridge module" paragraph, it's not super useful."

**Comment by jakehemmerle** [comment]
After reading the current wiki page and the feedback here, it seems that Bridge Contracts are just a way of using smart contracts for locking up the coins on a smart-contract supporting chain (that doesn't support pallets, eg. Ethereum), iand doesn't use use something like XClaim to swap the coins.

How does a restructure like this sound:

Decentralized bridging needs to be handled on each chain using one of the following methods
- as a bridge pallet (for substrate-based chains)
- as a smart contract (written in the chain's native smart contract language, eg. Ethereum, Tezos)
- using a trustless swapping protocol (atomic swaps, or XClaim, eg. Bitcoin, Litecoin)

Should we favor smart contracts over something like XClaim? should I find some pros and cons of each?

**Comment by Swader** [comment]
> should I find some pros and cons of each?

Yes please
