### ISSUE TITLE
Substrate version check does not seem to be updating the links

### ISSUE THREAD

**Issue by Swader** [w3f/polkadot-wiki#1815]
The check-substrate action is supposed to update links to use the latest tag in the docs, and also to then check that the links are up to date. This passes, but the links don't get updated. It could be that the action is not configured to persist changes to the repo, instead relying on the wiki updater to run this locally.

Needs investigating - ideally, this would be handled by the CI so the links are automatically kept up to date on different PRs.

**Comment by salmad3** [comment]
Link checker was removed in CI as links were updated to point to `latest`: https://github.com/w3f/polkadot-wiki/issues/2330
