### ISSUE TITLE
Add instructions for converting vote bitfield to actual vote

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#1816]
If you look at your votes on a block explorer, trying to understand what you voted on is difficult, since it's a bitfield with both conviction and the aye/nay boolean stored in one byte. This is usually displayed by block explorers as a decimal integer, so it's very confusing.

```
Nay 0.1 => 0
Nay 1x => 1
Nay 2x => 2
Nay 3x => 3
Nay 4x => 4
Nay 5x => 5
Aye 0.1x => 128
Aye 1x => 129
Aye 2x => 130
Aye 3x => 131
Aye 4x => 132
Aye 5x => 133
```

**Comment by laboon** [comment]
Also add Aye 6x and Nay 6x (hopefully it should be easy to figure out what they should be =) )

**Comment by laboon** [comment]
https://wiki.polkadot.network/docs/en/maintain-guides-democracy

Add a section called "### Interpreting On-Chain Voting Data" at the bottom

https://github.com/paritytech/substrate/blob/9b08105b8c7106d723c4f470304ad9e2868569d9/frame/democracy/src/vote.rs#L40

**Comment by salmad3** [comment]
PR reviewed by Bruno & site updated.
