### ISSUE TITLE
Wiki still states that "Polkadot mainnet is not released yet"

### ISSUE THREAD

**Issue by jakehemmerle** [w3f/polkadot-wiki#1817]
https://wiki.polkadot.network/docs/en/maintain-networks#polkadot-mainnet

Should update with instructions on how to sync

**Comment by laboon** [comment]
@jakehemmerle Can you get this? It won't let me assign you for some reason.

**Comment by laboon** [comment]
Ahh there it goes, I guess the UI was just slow to update
