### ISSUE TITLE
Unvote all on Council no longer requires extrinsic

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#1837]
This page - https://wiki.polkadot.network/docs/en/maintain-guides-how-to-vote-councillor#removing-your-vote - uses an extrinsic instead of the UI to remove Council votes. It should be updated.

Steps to remove council vote, go to https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.polkadot.io#/council
click on "vote"
Issue "Unvote all"

**Comment by salmad3** [comment]
Site updated.
