### ISSUE TITLE
link lead to page does not exist yet in learn staking wiki page

### ISSUE THREAD

**Issue by sweetpotatoz** [w3f/polkadot-wiki#186]
The link in https://github.com/w3f/polkadot-wiki/blob/master/docs/learn-staking.md
to
https://research.web3.foundation/en/latest/polkadot/Token%20Economics/

under "Inflation" section is leading to This page does not exist yet.

**Comment by laboon** [comment]
Looks like the research pages got re-arranged a bit, actual link is https://research.web3.foundation/en/latest/polkadot/Token%20Economics.html

I've issued a PR to fix
