### ISSUE TITLE
change "Polkadot application" to "Kusama application"

### ISSUE THREAD

**Issue by ghost** [w3f/polkadot-wiki#1910]
The article https://guide.kusama.network/docs/en/kusama-ledger#using-on-polkadot-js-apps refers to "Polkadot Application" in several places while it should say "Kusama application". Can this be corrected? It is quite confusing for users :) 

We expect many users to refer to this article in the next few days in preparation for Kusama parachains and upcoming crowdloans.

**Comment by Swader** [comment]
On it!

**Comment by Swader** [comment]
Should be fixed in #1910.
