### ISSUE TITLE
Don't name nomination as "Set and forget".

### ISSUE THREAD

**Issue by kianenigma** [w3f/polkadot-wiki#1921]
As the lengthy discussion here shows, w3f researches are strongly of the opinion that Nomination is, if anything, the opposite. We should make it clear that nomination is a active operation, bears risks, and the nominator is expected to frequently check upon their validator. 

https://github.com/paritytech/polkadot-sdk/issues/472

cc @laboon

**Comment by Swader** [comment]
Thank you, on it

**Comment by salmad3** [comment]
Checked page and this has been addressed.
