### ISSUE TITLE
Add Multisig deposit for Kusama guide

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#1929]
It's currently 3.3401

**Comment by laboon** [comment]
https://wiki.polkadot.network/docs/en/learn-accounts#example-with-polkadotjs

**Comment by emresurmeli** [comment]
@laboon need a little bit of clarification on this - is it to just update the DepositBase value for Kusama in the learn-accounts#example-with-polkadotjs page? Or to add a Multisig deposit portion to the Kusama guide that doesn't exist yet?

**Comment by laboon** [comment]
Just update this page for now.

Would probably make sense to mirror this to Kusama in the future but that can be a different PR.

**Comment by Swader** [comment]
Closed in #2027
