### ISSUE TITLE
Add re-genesis information

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#1949]
See:
https://github.com/polkadot-js/extension/issues/687#issuecomment-811981857
https://github.com/polkadot-js/extension/issues/687

We should include in the wiki:

1. An explanation of what re-genesis is in the glossary
2. Perhaps some steps on how it is done

This will most likely involve having one of the core devs review our work very carefully, so we should probably wait until post-parachains to do this (or maybe split this issue up and just add the term to the glossary for now)

**Comment by jak-pan** [comment]
We have a list of things we needed to do here: https://github.com/galacticcouncil/HydraDX-node/issues/191 (almost there)
And there is a lot of cool ideas here: https://github.com/paritytech/substrate/issues/7458

**Comment by DrW3RK** [comment]
@DannyS03 I just followed the instructions in the issue linked and added the content to just Glossary, pointing to the open issue that tracks the design of Re-genesis. We can add a dedicated section to Re-genesis once the process is formalized.
