### ISSUE TITLE
Update parachain params

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#1966]
Based on https://github.com/paritytech/polkadot/pull/2854

Key points:

Kusama and Polkadot will have 8 lease periods
Polkadots will be ~ 3 months (so max. still two years)
Kusama's will be ~ 6 weeks (so max. 1 year)

This will have impacts throughout much of the wiki, as we have always assumed there would be four lease periods

**Comment by laboon** [comment]
" it will be exactly 48 weeks - down to like 6 seconds give or take. Also this PR includes the code for Polkadot as well - so it’s official that it’s 3 month periods for a max 8 periods (2 years) Polkadot and Kusama - can tell time, in terms of milliseconds, minutes, hours and days. So that’s why the lease slots for Kusama are programmed just 7 days x 6. And for Polkadot a month in this case is 28 days - so three months won’t be three exact calendar months - and thus the 2 year period won’t be 730 days (365x2) but 672 days (28x24)"

**Comment by Swader** [comment]
Closed in #2027
