### ISSUE TITLE
Add a Cardano comparison?

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#1969]
This is a pretty common question on Reddit - "what differentiates Polkadot from Cardano?"

**Comment by salmad3** [comment]
To add to this, also a Polygon comparison?

**Comment by laboon** [comment]
Polygon/Matic is pretty different than Polkadot, not sure if having a specific page for that makes sense.

But a "Scaling via L0 vs Scaling via L2" would be interesting. Thoughts?

**Comment by Swader** [comment]
I don't agree that they're very different. Polygon is actually Substrate with Frontier built in, basically. That's their main project that they're launching. So they will in fact be a stronger competition for Polkadot per-se than other "competitors" on the list right now, in my opinion. Granted, their current form is not that - right now they're a checkpointed sidechain - but in the near future when they launch this Substrate competitors, things will look a lot more similar.

**Comment by laboon** [comment]
Ahh right, we've discussed this before. Got confused with a different project.

**Comment by salmad3** [comment]
@joepetrowski we can address this if you'd like

**Comment by salmad3** [comment]
Fair to say this can be put away - for now, the focus can be keeping up with the current comparisons. First thing that comes to mind is the London Hard Fork.

**Comment by emresurmeli** [comment]
Afaik London Hard Fork is EIP-1559 which is about token burning. It hopes to combat the inflationary nature of ETH, and somehow(I still need to research) decrease transaction fee rates. Not sure how that fits as a good "comparison" page for Polkadot.

**Comment by Swader** [comment]
Here's a good explainer about EIP1559 and what it does and why with the fee burning: https://newsletter.banklesshq.com/p/how-much-will-eip-1559-burn-?utm_medium=email&utm_campaign=cta
