### ISSUE TITLE
build-build-with-polkadot contains broken EVM link

### ISSUE THREAD

**Issue by bmacer** [w3f/polkadot-wiki#1971]
Affected document: https://github.com/w3f/polkadot-wiki/blob/master/docs/build-build-with-polkadot.md

Within third paragraph of "What you need to know section", second sentence contains the letters "EVM" hyperlinked to https://github.com/paritytech/substrate/tree/master/frame/evm.  This link is broken (github 404).  I tried to do some due diligence to figure out a correct link but am still learning the technology.

**Comment by laboon** [comment]
Looks like this pallet got moved to Frontier - https://github.com/paritytech/substrate/pull/7573

https://github.com/paritytech/frontier/tree/master/frame/evm

**Comment by laboon** [comment]
One of us will re-write that para to explain Frontier and that this isn't built-in with Substrate now - thanks for reporting!

**Comment by laboon** [comment]
fixed in #1978
