### ISSUE TITLE
Add an article on how to Stop validating

### ISSUE THREAD

**Issue by michalisFr** [w3f/polkadot-wiki#1993]
The wiki is lacking an article on how to stop validating that could probably go after "How to Chill".

Given the fact that the session keys cannot be purged, and thus remove the refcount from the account, unless the stash account has staked funds, this needs to be explicitly mentioned. 

An article describing the following steps is needed:

1. Chill
2. Payout any pending rewards
3. Purge session keys

Then the user can unbond and reap the accounts if they want

**Comment by laboon** [comment]
This one is high priority @jakehemmerle . Let me know if you would not be able to work on this soon.

**Comment by Swader** [comment]
Note that this is for validators, not nominators, just a heads up

**Comment by jakehemmerle** [comment]
Notes from talking with Bill:

If you stop validating and unbond, you won't be able to transfer everything because of refcount. You need to set a controller, restake, purge keys, then unbond. Only controllers can purge the keys.

**Comment by jakehemmerle** [comment]
> 2. Payout any pending rewards

@michalisFr  do you know how payout is done? I assume it's not just clicking "Payout all" under Staking > Payouts. That appears to collect all rewards from your nominated validators. Couldn't find an extrinsic or RPC for it but may have missed it.

Also, it seems that payouts need to be paid, session keys purged, and then tokens chilled. That order is different than listed above. Can you tell me if what I have here is correct or what you have above is correct?

**Comment by Swader** [comment]
> If you stop validating and unbond, you won't be able to transfer everything because of refcount. You need to set a controller, restake, purge keys, then unbond. Only controllers can purge the keys.

Wow what a mess

**Comment by laboon** [comment]
Yeah, that's why we want to make sure there's a good description here, because as you can imagine, people get upset about dealing with another 28 day wait...

I believe there was some talk about fixing this in an issue back in October, but I think it turned out to be more difficult than anticipated (or at least de-prioritized). Kian could give details about it.

**Comment by laboon** [comment]
> > 1. Payout any pending rewards
> 
> @michalisFr do you know how payout is done? I assume it's not just clicking "Payout all" under Staking > Payouts. That appears to collect all rewards from your nominated validators. Couldn't find an extrinsic or RPC for it but may have missed it.
> 
> Also, it seems that payouts need to be paid, session keys purged, and then tokens chilled. That order is different than listed above. Can you tell me if what I have here is correct or what you have above is correct?

You don't chill the tokens, you chill (step back from) validating. So your validator chills, not your DOT.

Payouts are paid out using the `staking.payoutValidators` extrinsic, but you'll need to enter the correct era. Most validators will have a script that does this. Or if they are nominating their own validator, they can use the Payout All from Polkadot-JS.

I think the order would be:

1. Do all payouts (although it doesn't really matter, anyone can trigger a payout)
2. purge_keys
3. Stop validating
4. Unbond

**Comment by michalisFr** [comment]
@jakehemmerle Like Bill said most validators use scripts to do the payouts but they can be done through "Payout all" button too, or the extrinsic, using any account, so it doesn't really matter when it's done. Perhaps we only need to add it as a reminder, not as a step: "Don't forget to payout all rewards".

Just to clarify, "Payout all" pays both the validator and the nominators.

@laboon I think you first need to Chill (stop validating) and then purge the keys. Otherwise how are you validating without keys? I think that this would result in a slash too, if you're active when you purge them. 

The process when you start validating is that you first set the keys and then you validate, so it stands to reason to do things in the opposite order when you want to stop. First chill (stop validating) and then purge the keys.

**Comment by laboon** [comment]
@wpank can you review the linked PR? and see if my response below make sense?

I think you're right @michalisFr that you chill and then purge, but purging the keys first shouldn't cause a slash; worst case scenario is if you don't immediately stop chilling and thus get dinged for unresponsiveness if you haven't authored a block or issued an imOnline ping during the epoch. But a slash would only occur if > 10% of validators are also offline.
