### ISSUE TITLE
Add info on Statemint parachain

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#1999]
Check out descriptions in Rococo, Joe P. can also help

**Comment by emresurmeli** [comment]
Covered in PR #2090

**Comment by laboon** [comment]
@emresurmeli #2090 is more of an integration guide. Can you walk through and show making / transferring / minting / burning assets? You can ask Will for some Westies (need 100 WND deposit to make an asset on Westmint).

This is high priority along with the teleporting issue.

**Comment by joepetrowski** [comment]
^^A guide to transferring (like learn-balance-transfers) is top priority.

**Comment by laboon** [comment]
@emresurmeli Any update on this?

**Comment by laboon** [comment]
1. Teleport some KSM from the relay chain over to Statemine (you'll need 1 KSM + some for tx fees)
2. Go to https://polkadot.js.org/apps/#/assets
3. Click on Create
4. Set parameters
5. 1 KSM is now reserved
6. Click on Mint and generate some NEWCOINS
6. Go to https://polkadot.js.org/apps/#/assets/balances
7. From here you can send to accounts. Remember accounts must be created (and thus have ED's worth of KSM on *Statemine*, not relay chain) to receive assets.
8. Accounts can send assets to other accounts themselves

**Comment by emresurmeli** [comment]
Great, I'm going to adding this to the Kusama guide under "What to try > Create an asset on Statemint", but I'll be doing it on Westmint. Let me know if anyone can think of a better location for it.

**Comment by joepetrowski** [comment]
Why do we want to encourage people to try creating an asset? It's only something that a very very very tiny percentage of users would ever need to do. As a priority we need to teach people how to use existing assets. It should cover transfers, transaction fees, sufficiency, and frozen state.

**Comment by salmad3** [comment]
@emresurmeli any possible update? If you'd like to get a draft PR up we could add some input :)

**Comment by salmad3** [comment]
@emresurmeli would we be able to get this cleared soon? Would suit well with https://github.com/w3f/polkadot-wiki/issues/2692

**Comment by joepetrowski** [comment]
Actually I am working on something. Will need tutorials to go along with it. Will post an update shortly. Don't do anything for now.
