### ISSUE TITLE
Tipping information

### ISSUE THREAD

**Issue by Swader** [w3f/polkadot-wiki#205]
Apart from #140 and #153, we need to also clarify the treasury with new information on the recent upgrade which allows for tipping.

The details are in the module.

**Comment by lsaether** [comment]
This refers to the `report_awesome` extrinsic and still definitely needs to be included on the Treasury page.

**Comment by Swader** [comment]
It's rather unusable right now as you need to manually figure out the tip hash to further interact with it. It's really, really awkward to use, so much so I would prefer not to touch it until we have a better UX for it, either in Apps or CLI with shortcut commands.

**Comment by lsaether** [comment]
closed in #388
