### ISSUE TITLE
Local build fails with `yarn v2`

### ISSUE THREAD

**Issue by nuke-web3** [w3f/polkadot-wiki#2064]
Update: yarn v1.22.10 works fine. yarn v2 will need some support here to get working. Note: substrate devhub uses yarn v2 now, switching while doing development is a bit of a pain 😬 

---

Ubuntu 20.04 LTS
node v14.17.0
yarn v2.4.1

```
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'axios' imported from polkadot-wiki/scripts/generateRegistryTable.mjs
Did you mean to import axios-npm-0.21.1-d192f6b3b3-864fb7b5d0.zip/node_modules/axios/index.js?
    at packageResolve (internal/modules/esm/resolve.js:650:9)
    at moduleResolve (internal/modules/esm/resolve.js:691:18)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:784:11)
    at Loader.resolve (internal/modules/esm/loader.js:100:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:246:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:47:40)
    at link (internal/modules/esm/module_job.js:46:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
docs/build-ss58-registry.md 36ms
polkadot-wiki/.pnp.js:19746
    throw firstError;
    ^

Error: Your application tried to access recursive-readdir, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.

Required package: recursive-readdir (via "recursive-readdir")
Required by: polkadot-wiki/scripts/
........
```

`yarn add axios` yields the same errors.
 might be a yarn 2 issue, but if so, maybe it's time to update?

**Comment by Swader** [comment]
We have not tested it on yarn 2 because frankly I'm unable to get yarn 2 to work properly on my machine.

**Comment by Swader** [comment]
We are looking into a migration to Docusaurus 2 which has better plugin support, which should help with the whole stack upgrade (the scripts need to be consolidated a bit too, we've got a bit too much customization happening in too many places, better to build a CLI tool that has them all in one place).

**Comment by salmad3** [comment]
This should be okay now - with the exception that you have docusaurus locally. 
Please reopen if faced with a similar issue.
