### ISSUE TITLE
Do you have an API for staking targets?

### ISSUE THREAD

**Issue by Lebed-kun** [w3f/polkadot-wiki#2104]
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama-rpc.polkadot.io#/staking/targets

I need a "return" value for specified validator, but I don't have an idea how to retrieve it with some request.

**Comment by laboon** [comment]
I am not exactly sure what you mean, but have you looked through the Polkadot API code to see if that call exists? https://github.com/polkadot-js/api

 You can also stop by the Substrate Technical channel to ask specific questions about it - https://app.element.io/#/room/#substrate-technical:matrix.org
 
 This isn't really a wiki request, so I am closing.
