### ISSUE TITLE
Update Validator Based Pages

### ISSUE THREAD

**Issue by salmad3** [w3f/polkadot-wiki#2147]
- https://wiki.polkadot.network/docs/en/maintain-guides-secure-validator
- https://wiki.polkadot.network/docs/en/maintain-guides-how-to-validate-polkadot
- https://wiki.polkadot.network/docs/en/maintain-guides-how-to-upgrade

**Comment by DannyS03** [comment]
Some References: 
- https://github.com/w3f/polkadot-wiki/issues/1652#issue-798143572
- https://github.com/w3f/polkadot-wiki/issues/1455#issue-767669420
