### ISSUE TITLE
Improve Nominating page

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#217]
The nominating page needs to be filled in a bit more, especially answering the questions:

1. What does active/inactive mean?
2. Warn users about waiting for the next era to start
3. What happens if none of my validators end up in the validator set?
4. Show more screenshots
5. Explain how to pick a nominator (reference Returns page - https://polkadot.js.org/apps/#/staking/returns)

**Comment by Swader** [comment]
Closed via #271
