### ISSUE TITLE
Server setup best practices

### ISSUE THREAD

**Issue by Swader** [w3f/polkadot-wiki#2177]
The server setup documentation should be reviewed for best practices, like not running alertmanager with root and generally making a no-home user for all sensitive operations, as well as closing the unneeded ports etc.

https://wiki.polkadot.network/docs/en/maintain-guides-how-to-monitor-your-node#installing-and-configuring-alertmanager-optional

**Comment by salmad3** [comment]
https://github.com/w3f/polkadot-wiki/issues/2192#issuecomment-893716342
