### ISSUE TITLE
Update Node Based Pages 

### ISSUE THREAD

**Issue by salmad3** [w3f/polkadot-wiki#2192]
- https://wiki.polkadot.network/docs/maintain-guides-how-to-monitor-your-node
- https://wiki.polkadot.network/docs/en/build-node-management#monitoring-and-telemetry
- https://wiki.polkadot.network/docs/en/maintain-guides-how-to-monitor-your-node#alertmanager-integration

Addresses #2177, #1652

**Comment by DannyS03** [comment]
Revisiting, will close the other associated issues to keep things in one place.

**Comment by muddlebee** [comment]
hey @DannyS03 @DrW3RK 👋 

#2177 `Server setup best practices`
**Expectations** : run alertmanager without root and generally making a no-home user for all sensitive operations, as well as closing the unneeded ports etc.

#1652 `Old grafana dash needs updating`
**Expectations**: remove the invalid data sources from Grafana dashboard, keeping in reference the PR(service: remove collection of system/process metrics) at https://github.com/paritytech/substrate/pull/6822/files

Is this the correct approach for the tasks? I hope we are on the same page 👀 

I am familiar with the prometheus/grafana environment.

**Comment by salmad3** [comment]
hey @muddlebee, thanks for the message:) Have you come across https://github.com/w3f/1KC?

**Comment by muddlebee** [comment]
@DannyS03  I have applied there as well and posted the above approach there in the form 👀  
When is the program getting started and when can I know about my acceptance?

**Comment by muddlebee** [comment]
https://github.com/paritytech/substrate/tree/master/scripts/ci/monitoring/grafana-dashboards

Grafana scripts requires some tweaking as "substrate" keyword is hard-coded here as follows which is a network prefix for metrics https://github.com/paritytech/substrate/blob/master/scripts/ci/monitoring/grafana-dashboards/substrate-networking.json#L7

need to add a value parameters for all kind of network prefix like substrate,polkadot,kusama etc etc.. working on it and will send a PR to substrate repo.

cc @DannyS03

**Comment by muddlebee** [comment]
FYI 
fixed this issue and opened a PR at https://github.com/paritytech/substrate/pull/11166
but couldn't reach any consensus with the susbtrate repo reviewers on merge after long discussions, and the PR got auto closed due to inactivity.
