### ISSUE TITLE
Broken Links: Auctions

### ISSUE THREAD

**Issue by shawntabrizi** [w3f/polkadot-wiki#2215]
Looking for info about auctions in wiki leads me to many broken links:

<img width="1106" alt="image" src="https://user-images.githubusercontent.com/1860335/123069244-83be9980-d40a-11eb-91f1-ada84441d44f.png">

https://wiki.polkadot.network/docs/en/learn-auction#docsNav

<img width="566" alt="image" src="https://user-images.githubusercontent.com/1860335/123069310-92a54c00-d40a-11eb-9d32-daa41d1a94f7.png">

<img width="693" alt="image" src="https://user-images.githubusercontent.com/1860335/123069354-9d5fe100-d40a-11eb-8de3-84e0192ff9fd.png">

All broken

**Comment by Swader** [comment]
This is due to a Docusaurus 2 migration. We're trying to resolve it.

**Comment by shawntabrizi** [comment]
@Swader thanks!

**Comment by Swader** [comment]
This is a breaking change in D2 that we simply were not aware of of how rigid it was before starting the migration process. The core team has confirmed this.

I thought of an esoteric fix that will resolve this:

- after build
- mdkir en && cp -R docs en/docs
- replace content of each index.html file in that new folder with

```html
<!DOCTYPE html>
<script>
  window.location.replace(window.location.href.replace("/en/", "/"));
</script>
```

Testing...
