### ISSUE TITLE
Fees write-up / edit

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#225]
https://substrate.dev/docs/en/next/development/module/fees#fee-calculation

The assumption we have been making (implicitly and occasionally explicitly) on here is that fees are static.  However, there are actually multiple components to a fee on Kusama/Polkadot -

1. Base fee (currently 0.01 KSM)
2. Length fee (paid per byte)
3. Weight fee (varies based on the [weight](https://substrate.dev/docs/en/next/conceptual/runtime/weight) of the tx)

**Comment by Swader** [comment]
This means it's next to impossible for any software to adequately sweep a wallet :(

**Comment by laboon** [comment]
I know. :( Apparently there is a way to estimate fees but it hasn't always been accurate.

**Comment by lsaether** [comment]
Isn't there an RPC for getting fees?

EDIT: There does exist `rpc.payment.queryInfo` which does the same fee calculation as far as I can tell (?)

**Comment by lsaether** [comment]
closed in #228
