### ISSUE TITLE
links are incorrect after refresh page

### ISSUE THREAD

**Issue by lovelangy** [w3f/polkadot-wiki#2250]
reproduce step:

1.  open getting-started page. https://wiki.polkadot.network/docs/getting-started
2.  move mouse to 'Creating a Polkadot Account', verify the link is 'https://wiki.polkadot.network/docs/learn-account-generation/', which is correct. 
3.  Refresh the getting-started page, the url will be 'https://wiki.polkadot.network/docs/getting-started/' 
4.  move mouse to 'Creating a Polkadot Account', verify the link is 'https://wiki.polkadot.network/docs/getting-started/learn-account-generation', which is deadlink.

this happens to whole website, not just  getting-started page

**Comment by emresurmeli** [comment]
I noticed the same thing on https://wiki.polkadot.network/docs/learn-accounts/ when you click "the cryptography page" in the first sentence which links to https://wiki.polkadot.network/docs/learn-accounts/learn-cryptography but should be https://wiki.polkadot.network/docs/learn-cryptography

**Comment by nam-hle** [comment]
Hi @emresurmeli, I think the issue due to the way we refer other documents. From [Docusaurus](https://docusaurus.io/docs/2.0.0-beta.0/docs-markdown-features#referencing-other-documents), the recommendation is to include the file extension when referencing.

**Comment by salmad3** [comment]
search and some links on the Kusama guides also going to "Page Not Found"

**Comment by emresurmeli** [comment]
@nam-hle Is this something that can be fixed by updating the config or? I think we have a lot of places outside of the wiki that link to these pages, and so we need to be careful about those not breaking.

**Comment by nam-hle** [comment]
The issue is not fixed. The Docusarus maintainer said we need to add `.md` when referencing.

**Comment by salmad3** [comment]
Right sorry just noticed only a few working - @nam-hle we should just update all references I assume? If so, will make it a high priority

**Comment by salmad3** [comment]
Looks it solves the issue - will update now

**Comment by salmad3** [comment]
Merged PR as priority fix as there has been a number of folks pointing out the links not working - don't hesitate to review or reopen if not fixed.

**Comment by salmad3** [comment]
@nam-hle seems like link issue persists

**Comment by nam-hle** [comment]
Sorry for my delay. The job takes me too much energy. I check again the issue, maybe it's resolved somehow, isn't it?

**Comment by salmad3** [comment]
It seems like it is...

**Comment by salmad3** [comment]
The WikiOps issue can serve as a reference point, closing this
