### ISSUE TITLE
Explain anti-spam measures from collators

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#226]
x:
What's to stop parachain collators from spamming validators with invalid blocks? 

y:
It makes sense to prepare a use/miuse case sort of diagram for polkadot.. since security is "rational" a here, disuse cases could also be added.. people then could navigate the diagram to find out why this or that attack can't happen

z:
What's to stop parachain collators from spamming validators with invalid blocks? 

a:
I think they can only spam parachain validators because parachain validators are responsible to check the validity in the first place

b:
Validators can choose to ignore collators, and running a collator means having a relay chain address, and that means that you have at least the existential deposit there.  So at a minimum, if you're consistently sending invalid messages, you'd have to keep coming up with new accounts with the existential deposit (or moving DOTs around and paying the fees).
I'm not sure how one opts in to be a collator (and I couldn't figure out through a quick code check), so there may be additional protection against this as well.

**Comment by Swader** [comment]
> and running a collator means having a relay chain address

Why?

**Comment by laboon** [comment]
I think we can get rid of this and have specific detailed information on collators.
