### ISSUE TITLE
Add information about deriving new accounts on PS on Account Generation page

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#2267]
https://wiki.polkadot.network/docs/learn-account-generation/

If you "derive new account", you will also need to add a different derivation path. This can be as simple as //1, //2, etc. but you do need different ones for each derived account. Using the seed plus the derivation path, you now have multiple totally separate account that share the same seed.

**Comment by DrW3RK** [comment]
In Polkadot Watercooler on July 13th 2021

@kerrari:matrix.org
Is the "Parity Signer" development abandoned?

@martin:matrix.parity.io
Nope. Quite the opposite in fact. We're working on some pretty cool new stuff for it, and will also likely do a release sooner than later to re-enable transaction decoding

I will defer video tutorial creation and reopen this issue.
