### ISSUE TITLE
Documentation for account creation seems a bit out of date.

### ISSUE THREAD

**Issue by Zerophase** [w3f/polkadot-wiki#2286]
I'm setting up my Kusama account. In the documentation it mentions setting up the Kusama (canary) network. I'm guessing Kusama Canary is now Kusama Relay Chain. Might want to update that so it does not cause issues for those with less technical knowledge.

It's on the PolkaDot.js setup section.

https://guide.kusama.network/docs/kusama-claims/

**Comment by salmad3** [comment]
Thanks @Zerophase
