### ISSUE TITLE
User Guide for Ledger Nano on Statemine

### ISSUE THREAD

**Issue by joepetrowski** [w3f/polkadot-wiki#2304]
Create a guide for how to use a Ledger Nano hardware wallet on Statemine. It should follow [these guidelines](https://docs.google.com/document/d/1QI7DHd3HIyhKWydlmjBbB-dlUXquqAd-4f4ED_-wgAU/edit).

**Comment by joepetrowski** [comment]
Being handled by @michalisFr

**Comment by michalisFr** [comment]
PR for article: #2311 
PR for sidebar: #2313

**Comment by michalisFr** [comment]
@joepetrowski Both PRs are merged

**Comment by michalisFr** [comment]
UPDATE: Actually building failed for the sidebar additions. Looking into it

**Comment by michalisFr** [comment]
@joepetrowski Article uploaded to wiki:
https://guide.kusama.network/docs/kusama-statemine-ledger
