### ISSUE TITLE
Naming updates

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#231]
Apparently Parity is using some names for things that I'd never heard of, and are not mentioned in the wiki -

https://medium.com/polkadot-network/polkadot-2019-year-in-review-8c852ef42668

Specifically - 

_Run-Ahead, our runtime compiler that means your Substrate nodes run near full speed even when they’re old versions;
Fast-Forward, our hybrid consensus algorithm which lets us author blocks even in network conditions that would stall other legacy algorithms such as PBFT/Tendermint, and yet lets us finalise tens of thousands of blocks instantly;
KayWhySee, our extensible, federated identity system; and
Hand-Off, our technology for effortlessly pairing on-chain and off-chain logic, allowing the chain to hand out arbitrary, non-deterministic work over your network, and even have the workload updated along with on-chain updates._

**Comment by Swader** [comment]
I think we might want to completely skip this. It's only every been mentioned in Gav's post, I've never seen it anywhere else, not even in code. If more than one person starts to refer to this stuff, we should revisit, but as is I think it can only confuse. Vote to close.

**Comment by laboon** [comment]
Nobody else has raised any objections to closure.
