### ISSUE TITLE
Update learn-collator page with more info from the Cumulus codebase

### ISSUE THREAD

**Issue by emresurmeli** [w3f/polkadot-wiki#2329]
Collator page is a bit dry, research collators further through the Cumulous framework and add more under the hood info to the wiki

**Comment by salmad3** [comment]
What do you think about this? https://github.com/w3f/polkadot-wiki/pull/2076#issue-647244671

`cumulus and rococo pages absorbed into parachains page`

**Comment by salmad3** [comment]
Seeing that we would move around some of the parachain content in this rework: https://github.com/w3f/polkadot-wiki/issues/2381, and that this may be better suited in the `build` section. I will update the page with some more "learn" content about collators to enhance the page.
