### ISSUE TITLE
Link to wiki broken on Polkadot website

### ISSUE THREAD

**Issue by DrW3RK** [w3f/polkadot-wiki#2332]
The link to documentation on https://polkadot.network/technology/ points to https://wiki.polkadot.network/en/latest/ which gives Page Not Found error

**Comment by emresurmeli** [comment]
So it looks like the current config has some rerouting happening but I am thinking this is what's causing the page not found problem. It currently says that whenever a url that includes /docs/ reroute it to /docs/en or /docs/zh-CN or /docs/ru-RU.

Neither path includes a index.html so I think we should try testing without this plugin in the config. 

```
 plugins: [
    [
      "@docusaurus/plugin-client-redirects",
      {
        createRedirects: function (existingPath) {
          if (existingPath.startsWith("/docs/")) {
            return [
              existingPath.replace("/docs/", "/docs/en/"),
              existingPath.replace("/docs/", "/docs/zh-CN/"),
              existingPath.replace("/docs/", "/docs/ru-RU/"),
            ];
          }
        },
      },
    ],
  ],
  ```

**Comment by DrW3RK** [comment]
@emresurmeli As much counter intuitive it may sound, it is doing exactly the opposite

Try these links -

https://wiki.polkadot.network/docs/en/glossary
https://wiki.polkadot.network/docs/zh-CN/glossary
https://wiki.polkadot.network/docs/ru-RU/glossary

This is due to the way createRedirects works in Docusaurus. You need to intently look at the documentation to figure this out! https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-client-redirects

Now that this functionality is figured out, I will try to mess around on the staging server and make progress

Also, who wrote these redirects? what did they have on their mind? It does not make sense to redirect everything to English docs!

@jakehemmerle @nam-hle @DannyS03 this might interest you as well

**Comment by nam-hle** [comment]
I wrote it. Until now, the Crowdin can not be integrated into our website. So to make every v1 link to be not broken, we need to redirect all to the English versions. That is my intention.

**Comment by DrW3RK** [comment]
@nam-hle Thank you! That is what I thought as well. Just making sure that was the intention

**Comment by DrW3RK** [comment]
https://staging.polkadot.network/en/latest
https://staging.polkadot.network/en/

Both work now. Will push this to prod. Closing the issue
