### ISSUE TITLE
DNSLink and IPFS Pinning

### ISSUE THREAD

**Issue by jakehemmerle** [w3f/polkadot-wiki#2338]
Accessing the wikis via IPFS is really close to being possible.

### [CICD Script](https://github.com/w3f/polkadot-wiki/blob/master/scripts/ipfs-cluster-pin.js#L101)

This will allow the wikis to be loaded with IPFS-compatable browsers at https://polkadot-wiki.w3f.services, https://kusama-guide.w3f.services. It is almost complete, just needs bugfixing at the DNS TXT updating that happens [here](https://github.com/w3f/polkadot-wiki/blob/master/scripts/ipfs-cluster-pin.js#L149). 

Things to note while finishing this:
- The CICD script only gets run on the Kusama Guide pipeline when new code is pushed to the `prod` branch (eg. [here](https://github.com/w3f/polkadot-wiki/runs/4619351318?check_suite_focus=true)). There is no reason this can't change this to a test server.
- Ignore any errors like [this](https://github.com/w3f/polkadot-wiki/runs/4619351318?check_suite_focus=true#step:5:2426). The functions retry the pinning, but are noisy. You might be able to silence these errors by adjusting the configuration values [here](https://github.com/w3f/polkadot-wiki/blob/master/scripts/ipfs-cluster-pin.js#L47)
- The errors regarding the DNS TXT update function are being logged in the CICD pipeline [here](https://github.com/w3f/polkadot-wiki/runs/4619351318?check_suite_focus=true#step:5:2447).
- The credentials for this script get passed in [here](https://github.com/w3f/polkadot-wiki/blob/master/.github/workflows/deploy-kusama-prod.yml#L35). They come from environmental variables in the repo (repo secrets). All of these secrets exist in 1Password (ask Alessio if you can't find them)

### [DNSLink chaining issue](https://github.com/ipfs/ipfs-companion/issues/1039)

This will allow the wikis to be loaded via IPFS-compatable browsers **transparently through the main websites** (eg. https://wiki.polkadot.network, https://guide.kusama.network)

**These two things complete putting the wikis on IPFS with easy access.**

## Other Optimizations
There are a few optimizations we can do after this:

### Setup [`ipfs-cluster-follow`](https://cluster.ipfs.io/documentation/collaborative/setup/#ipfs-cluster-follow) support

This would make it really easy for anyone to join the cluster as a follower, replicating anything we pin to the wiki to their computer. This makes for higher data availability and quicker data accessibility. I think it could be really cool to turn this into a Polkadot/Kusama IPFS Cluster, pinning important things for the network, W3F, and Parity.

###

**Comment by salmad3** [comment]
https://github.com/w3f/polkadot-wiki/issues/1695#issuecomment-777381375

**Comment by salmad3** [comment]
Also this sir: https://github.com/w3f/polkadot-wiki/issues/1919

**Comment by salmad3** [comment]
If I may, I added https://github.com/w3f/polkadot-wiki/issues/1695 here since the approach seems like it would depend on having IPFS up.

**Comment by DannyS03** [comment]
https://github.com/w3f/polkadot-wiki/issues/2573 issue with staging and prod

**Comment by emresurmeli** [comment]
Jake offboarding notes and to do:

- [ ] Regenerate new cloudflare apikeys
- [ ] Currently the function in the script(try/catch on line 109) to update the DNS TXT file via cloudflare isn't working, fix that.
- [ ] The CI/CD for IPFS is currently on Kusama prod yml, move it over to Polkadot prod yml as well
- [ ] Resolve the DNSLink chaining issue.

**Comment by emresurmeli** [comment]
@ironoa Will Jakes cloudflare keys be an issue? Should we move the cloudflare account to a shared email and regenerate the apiKeys?

**Comment by salmad3** [comment]
Update for DNS chaining issue: https://github.com/ipfs/ipfs-companion/issues/1039#issuecomment-1035228075

**Comment by salmad3** [comment]
@emresurmeli need to rotate IPFS credentials in 1Password again

**Comment by alfarok** [comment]
I am moving the completion of this work to an updated issue, #3651.  I added a reference to this issue in the description to track all the previous knowledge.

**Comment by alfarok** [comment]
> @ironoa Will Jakes cloudflare keys be an issue? Should we move the cloudflare account to a shared email and regenerate the apiKeys?

Hey @emresurmeli, do you happen to know which email address was used here?  I was able to track down the cluster credentials in 1Password but the username listed isn't an email address and CloudFlare requires the email as the login.  Maybe the credentials in 1Password aren't for CloudFlare?  No worries if you're not sure just trying to track down what is existing vs what may need to be re-created.

**Comment by alfarok** [comment]
Based on [this  configuration](https://github.com/w3f/polkadot-wiki/blob/master/scripts/ipfs-cluster-pin.js#L85) it seems like the API key is stored in 1Password but not the login details for the account.
