### ISSUE TITLE
[CI] staging 404 error bug (w/ workaround)

### ISSUE THREAD

**Issue by jakehemmerle** [w3f/polkadot-wiki#2362]
If there is a 404 error when visiting staging servers, you need to go into the `polkadot-wiki-staging` and `kusama-guide-staging` repos and set `staging.polkadot.network` and `staging.kusama.network` in the settings under Pages. I'm not sure why this keeps getting unset.

Current workaround is to just do that but I'm going to try and see what the root problem is.

only affects staging deployments, not prod.

**Comment by DrW3RK** [comment]
In case you want to use your custom domain for GitHub Pages, create a CNAME file in the static directory. Anything within the static directory will be copied to the root of the build directory for deployment.

https://docusaurus.io/docs/deployment

This fixes it!

**Comment by DrW3RK** [comment]
**For future reference:** great fix @jakehemmerle for configuring deployment to account for prod and staging in .github > workflows. closing this issue
