### ISSUE TITLE
Rework & Additions to Build (and Learn) Section(s)

### ISSUE THREAD

**Issue by salmad3** [w3f/polkadot-wiki#2381]
**Focus is Parachain and general Build (and Learn) content**

This serves as a point of reference, please feel free to add points that represent the desired updates and changes, then, those can be created into issues. 

Previous attempts:
- https://github.com/w3f/polkadot-wiki/pull/2066
- https://github.com/w3f/polkadot-wiki/pull/2076

Changes made by @NukeManDan can be adapted.

**Comment by salmad3** [comment]
Epic has ~10 open issues linked to it.

**Comment by nuke-web3** [comment]
@DannyS03 chiming in that if you would like a review on anything related to this issue, I would be Happy to be assigned.

**Comment by salmad3** [comment]
Many thanks @NukeManDan, perhaps it would make sense to open a new PR for some of the changes you had originally made. We could start with the parachain content :)

**Comment by salmad3** [comment]
Combining some outstanding issues here as they align with the changes for the parachain content in previous attempts.

**Comment by salmad3** [comment]
Parachains: 
- Parachain development & build (PDKs)
- Parachain playground (https://github.com/w3f/polkadot-wiki/issues/1857)
- Parachain design (https://github.com/w3f/polkadot-wiki/issues/286) 
  - The points mentioned in the original issue are good, but I feel we should be careful in terms of specifics, and we should focus on "general design points" where the economics is sort of inherent.

**Comment by salmad3** [comment]
> Parachains:
> 
> * [ ]  Parachain development & build (PDKs)
> * [ ]  Parachain playground ([Document parachain playground #1857](https://github.com/w3f/polkadot-wiki/issues/1857))
> * [ ]  Parachain design ([Parachain economic design #286](https://github.com/w3f/polkadot-wiki/issues/286))
>   
>   * The points mentioned in the original issue are good, but I feel we should be careful in terms of specifics, and we should focus on "general design points" where the economics is sort of inherent.

@NukeManDan perhaps we can start with this
