### ISSUE TITLE
Update Pages to Latest UI

### ISSUE THREAD

**Issue by salmad3** [w3f/polkadot-wiki#2390]
Most pages that have screenshots and reference the official UI (i.e. Polkadot-JS Apps) should be up-to-date now, though, some still need to be (please add others if you come across them). 

- [ ] learn-identity
- [ ] maintain-guides-democracy
- [ ] learn-nominator
- [ ] maintain-guides-society-kusama
- [ ] balance-transfers (conditional rendering for Polkadot Wiki/Kusama Guide)
- [ ] learn-proxies

**Comment by salmad3** [comment]
@DrW3RK I added `maintain-guides-society-kusama` to the list and closed the previous issue. If it is okay with you, it could be a way to also go over some of the actions available on the other pages

**Comment by DrW3RK** [comment]
Will do!

**Comment by salmad3** [comment]
Good tester for 1KC

**Comment by DrW3RK** [comment]
The How-to-guides have now moved to the support page with updates to UI. The outdated UI snapshots will be removed as a part of https://github.com/w3f/polkadot-wiki/issues/3570
