### ISSUE TITLE
Deprecate concept of fishermen

### ISSUE THREAD

**Issue by alxs** [w3f/polkadot-wiki#2396]
@burdges suggested that there is currently no sensible way (and also no necessity) to implement fishermen.

As far as I'm aware (though I definitely could be missing something) this concept is outdated and can be deprecated in the documentation, possibly in more places than just the wiki. Since the concept is well-known in the ecosystem and has been thematised since the whitepaper, we probably shouldn't just "forget about it" but explain why polkadot is already secure without fishermen etc.

It would be good to get confirmation from someone "inside" like @bkchr @shawntabrizi.

**Comment by bkchr** [comment]
@rphmeier should know best.
