### ISSUE TITLE
Translations: Localization, Contributions & Related Configuration

### ISSUE THREAD

**Issue by emresurmeli** [w3f/polkadot-wiki#2398]
Elodie and I are working on tidying up the localization work that is pending and or has not been started yet. This new information should be reflected on the wiki with a helpful "how to contribute" approach. Some things to consider:

- Where can people learn about how to translate?
- Where can people learn about how to review pending translations?
- How can people use crowdin? (aka a how to for Crowdin)

This is all mostly details that're tbd, so as Elodie and I make progress I'll keep this issue updated. 

---
Drop down: https://github.com/w3f/polkadot-wiki/issues/2425 + related configuration

**Comment by salmad3** [comment]
Let's put these together: https://github.com/w3f/polkadot-wiki/issues/1446

**Comment by DannyS03** [comment]
Adding this here: https://github.com/w3f/polkadot-wiki/issues/2425

**Comment by malba22** [comment]
Spanish translation  needed?

**Comment by dbpatty** [comment]
We (me and Grace as head ambassador for localization) are plannig an howto doc for translators and curators with process definition and links and tools.

**Comment by salmad3** [comment]
Generally blocked but a high priority - can initiate the translation process once certain general docs are reviewed, the rest will depend on the team's approach to content and restructuring the wiki. A new translation process in sync with the 1KC program should be available in due course
