### ISSUE TITLE
Address conversion tool is not working

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#2415]
If you enter an address, it does not change when you select a new network. 

https://wiki.polkadot.network/docs/learn-accounts#address-conversion-tools

**Comment by jakehemmerle** [comment]
After spending about an hour trying to get this to work, I say we scrap it and tell them to redirect to one of the converters we have listed below. Thoughts?

**Comment by jakehemmerle** [comment]
I think it's related to some static JS rendering differences between docusaurus v1 and v2 (since the script was created by Logan a year ago)

**Comment by DrW3RK** [comment]
<img width="804" alt="Screenshot 2021-08-03 at 19 06 00" src="https://user-images.githubusercontent.com/86818441/128057115-ab898104-0c1a-4b33-bdfa-0e3def16abc5.png">

Needs a deeper look as to why this might be happening

**Comment by DrW3RK** [comment]
Yup, indeed this is a migration issue. Not with docusaurus, but with the way we reorganized wiki content folders

https://wiki.polkadot.network/js/custom.js   - The js folder is outside the docs folder. Looks like this would break all the pages that are currently using javascript in them

**Comment by salmad3** [comment]
@a-jwc said he would take a crack at this

**Comment by DrW3RK** [comment]
Keep me posted. I can look into this again tomorrow

**Comment by DrW3RK** [comment]
Figured out the issue. Just needed to reference to JS files appropriately in config file. Creating a PR and merging it to Master

**Comment by DrW3RK** [comment]
![image](https://user-images.githubusercontent.com/86818441/129708905-ae5ecb08-4a0f-4170-adb8-6f1f0d672ef8.png)
Made progress with correctly referencing JS files in the latest repo structure, but looks like the address changer JS file itself has an issue. Debugging this is beyond our scope I guess. I will remove the address converter tool from the doc. If anyone wants to debug this, raise a new issue/PR
