### ISSUE TITLE
Edit page buttons lead to a 404

### ISSUE THREAD

**Issue by nuke-web3** [w3f/polkadot-wiki#2451]
https://wiki.polkadot.network/docs/build-parachains-rococo has an "edit page" button that leads to a 404: https://github.com/w3f/polkadot-wiki/edit/master/docs/build-parachains-rococo.md

Other pages also may have this behavior.

**Comment by DrW3RK** [comment]
Noted! This is specific to the prod branch, as it seems to work as expected on staging. Will dig deeper into this. Here is a n example page on staging

https://staging.polkadot.network/docs/learn/learn-launch

**Comment by DrW3RK** [comment]
@DannyS03 This is due to the folder structure change on the Master. For instance, the below URL would work if you specify the folder in which you have that md file

https://github.com/w3f/polkadot-wiki/edit/master/docs/learn-architecture.md

**Comment by salmad3** [comment]
Right, thanks! 

Resulted from: https://github.com/w3f/polkadot-wiki/pull/2426
This restructure will be revisited shortly, but as it stands, master is the way it was and the link should lead to the correct location
