### ISSUE TITLE
"Last updated on X by Y" is connected to any change on the wiki overall, not the page in question

### ISSUE THREAD

**Issue by nuke-web3** [w3f/polkadot-wiki#2452]
https://wiki.polkadot.network/docs/build-parachains-rococo is an example, where the last edit at the bottom of the page seems to be the same for every other page, even thought the content has not been updated: https://github.com/w3f/polkadot-wiki/blob/master/docs/build/build-parachains-rococo.md

**Comment by salmad3** [comment]
Thanks @NukeManDan 

We had also mentioned this in: https://github.com/w3f/polkadot-wiki/issues/2294

**Comment by salmad3** [comment]
Attempt fix did not work

**Comment by DrW3RK** [comment]
@DannyS03 This is working on Staging. Check this page -
https://staging.polkadot.network/docs/build-build-with-polkadot

But the prod seems to be showing whoever rebases it -
https://wiki.polkadot.network/docs/build-build-with-polkadot

**Comment by salmad3** [comment]
> @DannyS03 This is working on Staging. Check this page -
> https://staging.polkadot.network/docs/build-build-with-polkadot
> 
> But the prod seems to be showing whoever rebases it -
> https://wiki.polkadot.network/docs/build-build-with-polkadot

Ahh that makes sense
