### ISSUE TITLE
NFTs Page

### ISSUE THREAD

**Issue by salmad3** [w3f/polkadot-wiki#2455]
- NFT basics
- A comparison
  - Perhaps obstacles of some of the inherent problems of first generation vs. next generation (Polkadot :)) 
- NFTs in the Polkadot ecosystem, for instance:  
  - https://rmrk.app/
  - https://kodadot.xyz/
  - https://unique.network/
  - https://enjin.io/blog/efinity
  - PolkadotAssetJS
  - Moonbeam integrates NFTs
  - Substrate & NFTs
  - Statemine

- ~Can sit in the build section after "Oracles"~ Sits in learn section for now.

**Comment by Swader** [comment]
I will submit a new PR for this tonight probably

**Comment by salmad3** [comment]
At your leisure!

**Comment by salmad3** [comment]
@Swader did you get a chance to try this out:)

**Comment by Swader** [comment]
Oh yes, sorry, draft is almost ready, will try and push it today!

**Comment by salmad3** [comment]
Oh no worries, sounds good

**Comment by DannyS03** [comment]
@Swader Update?

**Comment by salmad3** [comment]
Were you able to finish drafting something? @Swader let us know if we can help

**Comment by Swader** [comment]
So sorry 🙈 on it - I have a draft, but have not submitted

**Comment by DannyS03** [comment]
No worries, I'd say the main content could be
- General NFT intro, comparison 
- Substrate, Statemine (e.g. https://github.com/w3f/polkadot-wiki/issues/2719#issue-1023583867)
- RMRK 
- Other projects (briefly)

**Comment by salmad3** [comment]
Added in referenced PR.
