### ISSUE TITLE
Polkadot and Kusama Validator Logs

### ISSUE THREAD

**Issue by DrW3RK** [w3f/polkadot-wiki#2457]
Add a new page for explaining and supporting issues that show up in common logs of validator nodes on Polkadot and Kusama. 

Here is a resource that already put up some ground work https://github.com/ccris02/DOT_KSM_Logs

**Comment by salmad3** [comment]
@ccris02 feel free to open a draft PR and we can get input and feedback from others

**Comment by salmad3** [comment]
@muddlebee taking this on
