### ISSUE TITLE
Update Ethereum 2.0 Roadmap

### ISSUE THREAD

**Issue by dnl-rss** [w3f/polkadot-wiki#2490]
`docs/learn/learn-comparison-ethereum-2.md` references an Ethereum 2.0 roadmap that is outdated. Proof-of-stake merge is set to precede sharded blockchains.

https://ethereum.org/en/eth2/merge/

I'd be happy to start a pull request with an update, if this repo's maintainers agree it is warranted.

**Comment by salmad3** [comment]
Thanks @drees1, all contributions are appreciated, go for it:)

**Comment by dnl-rss** [comment]
@DannyS03 my pull request failed with the following logs:

```
CMD: git commit -m "Deploy website - based on 684fcd06962252b7e1cc32f6f49fc7d69f4d7a32" (code: 0)
fatal: could not read Password for 'https://w3fdeploy@github.com': No such device or address
CMD: git push --force origin gh-pages (code: 128)
Error: Running "git push" command failed.
    at runDeploy (/home/runner/work/polkadot-wiki/polkadot-wiki/node_modules/@docusaurus/core/lib/commands/deploy.js:145:19)
    at async deploy (/home/runner/work/polkadot-wiki/polkadot-wiki/node_modules/@docusaurus/core/lib/commands/deploy.js:166:13)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```

It seems this is an issue with the testing integrations, and not my actual changes. Is that correct? Is there anything that needs to be done on my end?

**Comment by salmad3** [comment]
> @DannyS03 my pull request failed with the following logs:
> 
> ```
> CMD: git commit -m "Deploy website - based on 684fcd06962252b7e1cc32f6f49fc7d69f4d7a32" (code: 0)
> fatal: could not read Password for 'https://w3fdeploy@github.com': No such device or address
> CMD: git push --force origin gh-pages (code: 128)
> Error: Running "git push" command failed.
>     at runDeploy (/home/runner/work/polkadot-wiki/polkadot-wiki/node_modules/@docusaurus/core/lib/commands/deploy.js:145:19)
>     at async deploy (/home/runner/work/polkadot-wiki/polkadot-wiki/node_modules/@docusaurus/core/lib/commands/deploy.js:166:13)
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> Error: Process completed with exit code 1.
> ```
> 
> It seems this is an issue with the testing integrations, and not my actual changes. Is that correct? Is there anything that needs to be done on my end?

Right that's correct it would be from the integration
