### ISSUE TITLE
Accordian not working for `Build` section

### ISSUE THREAD

**Issue by nuke-web3** [w3f/polkadot-wiki#2496]
https://wiki.polkadot.network/docs/learn-implementers-guide shows this as an example:

![image](https://user-images.githubusercontent.com/35669742/130123958-9012de26-7cdf-427f-8290-318c17234165.png)

the accordion expands and seems to be stuck/hidden behind the one below it? Page navigation and discovery is not possible at the moment from the left sidebar.

**Comment by DrW3RK** [comment]
Strange! I see the expanded view when I click the link

![image](https://user-images.githubusercontent.com/86818441/130124726-f432cc92-d420-406a-9836-807b97858208.png)

**Comment by DrW3RK** [comment]
I tested on three browsers (Chrome, Safari and Edge). All of them showed the expanded view. Which browser are you using?

**Comment by nuke-web3** [comment]
Firefox. I have blockers that can interfere with this sometimes, but should not be in this case. 

I also am at a higher page zoom level, that shouldn't effect this.

No other accordion has issues. 🤷🏼

**Comment by salmad3** [comment]
I tried this on Firefox (and other browsers), with and without a higher page zoom level and both seem fine. Hmm... 

While we make updates to the config, we can revisit if this is still an issue. I will close for now and please reopen if otherwise.
