### ISSUE TITLE
Missing components leads to bad UX

### ISSUE THREAD

**Issue by 0xSachinK** [w3f/polkadot-wiki#2502]
The [Thousand Validators Programme page](https://wiki.polkadot.network/docs/thousand-validators) on the wiki does not show the contents sidebar. The buttons at the end of the page which help to navigate to the next/previous article are also missing. 
These missing components lead to a bad UX and break the flow of reading for users.

**Comment by salmad3** [comment]
Thanks for pointing this out @Alpha-Guy 

Seems like a redirect issue
