### ISSUE TITLE
Remove translated docs from link-checking

### ISSUE THREAD

**Issue by Swader** [w3f/polkadot-wiki#251]
@fgimenez can you please set up the CI so that it doesn't take translated docs into account? As it is, all our PRs will auto-fail when we add new pages, and it doesn't make sense to wait for the crowdin bot to do a PR after every submit of ours. Since the crowdin PR is automated, it will by default inherit good and bad links from the main docs, so it doesn't make much sense to check those anyway.

**Comment by Swader** [comment]
@fgimenez I force merged a PR that was blocked by CI, to rush things in, but it seems the CI then failed not only during pre-check but also during deployment. CI should not block build if forced, even if pre-check failed. Can we have it configured that way? The idea is that we can push emergency fixes in despite CI maybe failing the test build.

**Comment by fgimenez** [comment]
> Can we have it configured that way? The idea is that we can push emergency fixes in despite CI maybe failing the test build.

Sure, i've proposed this PR for that https://github.com/w3f/polkadot-wiki/pull/252
