### ISSUE TITLE
Add WASM snippet and links to Learn Wasm Page

### ISSUE THREAD

**Issue by salmad3** [w3f/polkadot-wiki#2518]
Idea here is to allow the user to understand Substrate x Wasm

Some links to consider:
- https://github.com/polkadot-js/wasm
- https://wasmbyexample.dev/home.en-us.html#

Snippet as in a simple example of how Wasm is used in the implementation, or even a reference to Dev Hub (e.g. https://substrate.dev/docs/en/knowledgebase/advanced/executor)

**Comment by DannyS03** [comment]
Going to hold off of this for now
