### ISSUE TITLE
CI checking redirection

### ISSUE THREAD

**Issue by Swader** [w3f/polkadot-wiki#253]
https://circleci.com/gh/w3f/polkadot-wiki/1312?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

@fgimenez the 404 failures here are because the link checker is looking at `docs/en` and not `docs/en/` - in deployment, docs/en redirects to `docs/en/` and this makes relative links work (because they get appended to `/en/`) but in the CI checking the redirect does not happen on this index page, and so it 404s on links that are relative to the wrong directory.

This only happens on the home page of the wiki which is the only one without a page name. Can we set the CI up so that it does not check `/docs/en` or so that it redirects `docs/en` to `/docs/en/`?

**Comment by fgimenez** [comment]
Absolutely, it is a small change https://github.com/w3f/polkadot-wiki/pull/254 and the build is green.
