### ISSUE TITLE
[Naming Question] Substrate RPC or Polkadot RPC

### ISSUE THREAD

**Issue by paulvi** [w3f/polkadot-wiki#2551]
What is more correct Substrate RPC or Polkadot RPC ?

See https://wiki.polkadot.network/docs/build-node-interaction

Substrate is part of Polkadot.
And if Polkadot project does not add extra API methods to RPC, then it should be called Substrate RPC.

Anyways naming should be consistent.

**Comment by salmad3** [comment]
I believe you have addressed this in: https://github.com/w3f/polkadot-wiki/pull/2550
Please reopen if otherwise:)

**Comment by paulvi** [comment]
#2550 is different as it is about relationships.

But if you read through page, you see that **Substrate RPC API** is called **Polkadot RPC** just after list as name of next section:

![image](https://user-images.githubusercontent.com/1614482/132156189-9cc8f0f7-761d-4130-b596-badca6e9d8ab.png)
