### ISSUE TITLE
Remove mentions of state rent for the `contracts` pallet

### ISSUE THREAD

**Issue by cmichi** [w3f/polkadot-wiki#2561]
With https://github.com/paritytech/substrate/pull/9669 we removed the concept "state rent" from the `contracts` pallet.

I just quickly checked and saw that the Polkadot Wiki mentions it e.g. here:
https://wiki.polkadot.network/docs/build-smart-contracts#storage-rent. Possibly in other places as well.

The terms State Rent / Code Rent / Storage Rent all refer to the same concept.

In the future there will be a different mechanism to cope with state boat, but until that one is here we should remove mentions of this no longer used concept.

**Comment by salmad3** [comment]
Thanks @cmichi
