### ISSUE TITLE
Update Account creation video

### ISSUE THREAD

**Issue by DrW3RK** [w3f/polkadot-wiki#2568]
Based on the issues raised under the explainer video linked to the Wiki page on accounts creation, it is important to have video walkthroughs of all recommended ways of creating accounts on Polkadot

https://www.youtube.com/watch?v=hhUZ40ZWqkE&lc=UgxjbeiYbBEXfgnOd-94AaABAg

![image](https://user-images.githubusercontent.com/86818441/132706839-8106e6b9-2f94-4a54-82e9-faa0abe7be35.png)

**Comment by salmad3** [comment]
It seems this serves to be something internal as we would have to record a new video to update the page. Please reopen if otherwise.
