### ISSUE TITLE
Missing image assets

### ISSUE THREAD

**Issue by DrW3RK** [w3f/polkadot-wiki#2573]
Interact with Polkadot section has missing images
https://wiki.polkadot.network/docs/getting-started

**Comment by DannyS03** [comment]
Right I think this is due to the IPFS deployment issue with the CI

**Comment by salmad3** [comment]
Same with `contributing.md`, both work locally. @DrW3RK 
![image](https://user-images.githubusercontent.com/25497083/132999630-72431a90-0dc6-4789-bfc5-a0d327348f6c.png)

![image](https://user-images.githubusercontent.com/25497083/132999761-ad9a2f64-163c-42f2-9ae1-fd6d80c7b0aa.png)

![image](https://user-images.githubusercontent.com/25497083/132999646-891962a9-d1c8-4bb6-b5df-feb8836f35c1.png)

Kusama guide also not picking up updates. 
Holding off pushing some updates as a result. (i.e. https://github.com/w3f/polkadot-wiki/issues/2563, https://github.com/w3f/polkadot-wiki/issues/617)

**Comment by DannyS03** [comment]
Linked the open issue
