### ISSUE TITLE
General Content Check

### ISSUE THREAD

**Issue by salmad3** [w3f/polkadot-wiki#2582]
Just using this as a reference point.

- Similar to Stale Check, but will focus on the content that was recently updated. 
- Will capture some fixes/some issues outstanding (e.g. https://github.com/w3f/polkadot-wiki/issues/2573)

**Comment by DrW3RK** [comment]
If you plan to use html code in docs, make sure all the assets they point to are static assets - https://docusaurus.io/docs/static-assets
If you intend to use the assets in docs folder, then you have to follow the rules of Docusaurus. For instance, this is how you write code for creating an image with a hyperlink (which can point to the asset in docs folder. Docusaurus will hash it) 
![image](https://user-images.githubusercontent.com/86818441/133232977-cc3b5e65-6ea1-4772-897e-105d7d118e75.png)

I fixed the issue by copying over the images to static folder and referencing them directly in the doc's html code. Please fix this in other places as well

**Comment by salmad3** [comment]
If we could check out the following and add any critic that would be great:
- https://wiki.polkadot.network/docs/learn-crosschain
- https://wiki.polkadot.network/docs/build-pdk
- https://wiki.polkadot.network/docs/learn-phragmen
- https://wiki.polkadot.network/docs/build-storage
- https://staging.polkadot.network/docs/getting-started#interact-with-polkadot
- https://wiki.polkadot.network/docs/build-hackathon

- The Kusama guide has also not pushed changes in a while

@emresurmeli @DrW3RK @jakehemmerle @a-jwc

**Comment by salmad3** [comment]
Please re-open if needed
