### ISSUE TITLE
New Page for Slashing focusing on "Lessons Learned from [Past] Slashing"

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#2612]
"We should create a page "Lessons learned from past slashing events" to group everything together. Looks like the slashing conditions are still quite scattered around." -Wei Tang

Perhaps here: https://wiki.polkadot.network/docs/maintain-guides-secure-validator or in a separate page under Validator section?

**Comment by paradox-tt** [comment]
Hi @DannyS03,

I intend to publish a YT video on the topic of slashing based on the slides found in the PDF below.  Within the attached you'll find some causal factors for slashing (based on type) and mechanisms for mitigation.  I hope the information helps with the subjected issue.

[Slashing on Polkadot.pdf](https://github.com/w3f/polkadot-wiki/files/7272308/Slashing.on.Polkadot.pdf)

Best Regards,
Will | Paradox

**Comment by salmad3** [comment]
Hey @paradox-tt, thanks a ton for this =)

**Comment by paradox-tt** [comment]
You're welcome, I hope it helps!

**Comment by paradox-tt** [comment]
Draft document (as attached) is being reviewed before converting to mark-down for inclusion in the Wiki
[Best practices to prevent slashing.docx](https://github.com/w3f/polkadot-wiki/files/8478302/Best.practices.to.prevent.slashing.docx)
.

**Comment by salmad3** [comment]
Feel free to open a PR @paradox-tt adding a new .md file in the maintain section. The team can worry about mirroring or conditional rendering after the fact

**Comment by paradox-tt** [comment]
![image](https://user-images.githubusercontent.com/79228812/164225478-5d0cb7f0-715f-4f8f-bff9-cb0806081e5a.png)

Hey Danny, 

I don't think I have access to do so.

**Comment by DrW3RK** [comment]
https://wiki.polkadot.network/docs/maintain-guides-avoid-slashing Page added
