### ISSUE TITLE
"Cannot sign with locked key pair" error via Polkadot-JS Apps and complicated proxy setups

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#2626]
We should have information for this on the errors page (https://wiki.polkadot.network/docs/maintain-errors). This means that Polkadot-JS Apps UI does not have the correct key with which to sign this message, which means the account has not been added to Polkadot-JS Apps. We should explain this as the error message is not very clear.

However, there is a a further issue. Apps UI cannot handle complicated proxy setups (e.g. a proxy to a multisig to an anonymous proxy which is part of another multisig). The chain itself can handle it, but not the UI. The UI only handles a single proxy -> multisig chain. This includes using the extrinsics tab directly!

On the proxy page ( https://wiki.polkadot.network/docs/learn-proxies ), we should advise that users avoid these complicated proxy setups, as they will be unable to sign extrinsics with them using the UI.

**Comment by salmad3** [comment]
Thinking of adding the mentioned error on the support page and updating "maintain-errors.md" in general since the errors are generated from the runtime
