### ISSUE TITLE
Kusama guide should have reference to KSM

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#2629]
https://guide.kusama.network/docs/learn-staking/#inflation

References to "DOT" should say "KSM"

**Comment by salmad3** [comment]
Will be captured in: https://github.com/w3f/polkadot-wiki/issues/2597

**Comment by jakehemmerle** [comment]
@DannyS03 why do we think this is related to injection issues? No [conditional rendering](https://github.com/w3f/polkadot-wiki#conditional-rendering) is being used in the file anywhere

eg. https://github.com/w3f/polkadot-wiki/blob/master/docs/learn/learn-staking.md?plain=1#L454

**Comment by jakehemmerle** [comment]
Being addressed in #2644 ; not injection related

**Comment by jakehemmerle** [comment]
Perhaps we should rename to "Add conditional rendering to learn-staking" or something?
