### ISSUE TITLE
Broken External Reference link to Wiki page on Ledger

### ISSUE THREAD

**Issue by DrW3RK** [w3f/polkadot-wiki#2647]
This page - https://support.ledger.com/hc/en-us/articles/360018131260?docs=true
references to https://wiki.polkadot.network/docs/en/learn-ledger

When renaming docs or moving them to a different folder, we need to ensure they do not break external references in external websites https://github.com/w3f/polkadot-wiki/blob/801a3ba71d77e6bf839ebf9fd576e03faac39c19/docs/learn-ledger.md

**Comment by DrW3RK** [comment]
Right now, the ledger page lives here - https://wiki.polkadot.network/docs/ledger

I suggest duplicating the content in learn folder. This is to ensure the newly created page's external references are not broken. 

@DannyS03 what do you think?

**Comment by salmad3** [comment]
The page was originally in the learn section.

The motive behind the move was that the content also serves to be general, and is more accessible, if you will. However, this would suggest that there could be other pages under the general section, such as the page (or a page) for nominating.

I'd say both methods work: we could move it back to the learn section or update the slug to fix the references. The way we have the docs organized implies that the page should go back to the learn section. 

Also, we could embed the video on the page @DrW3RK
![image](https://user-images.githubusercontent.com/25497083/134931885-ea39b235-95dc-4e8a-918d-097bc151d1d9.png)

We could actually embed the new videos on some of the other pages too. This would also work well to create a balance of text and visual learning - also when considering the addition to more graphics on icons across the pages.

**Comment by DrW3RK** [comment]
I understand the motive. My point is that such renaming/rearrangements will have unforeseen consequences like this one. I am not sure how to fix this with Slug. 

The video is already embedded in the page right? Yeah, I'm updating the latest videos in the docs wherever I see fit

**Comment by DrW3RK** [comment]
Is there a different way of embedding videos?

**Comment by salmad3** [comment]
Right, I know what you mean. I believe the slug defined for this page is incorrect though. At the moment, it is `../ledger` but we can change it to `../learn-ledger`.

**Comment by salmad3** [comment]
> Is there a different way of embedding videos?

It seems that it only redirects to the video link: https://staging.polkadot.network/docs/ledger#using-ledger-live

**Comment by DrW3RK** [comment]
Fine. I updated Slug and it will fix the broken link on Ledger website. Closing the issue
