### ISSUE TITLE
Fix Conditional Rendering and Dynamic value inserts

### ISSUE THREAD

**Issue by DrW3RK** [w3f/polkadot-wiki#2662]
Conditional Rendering and Dynamic value inserts were dysfunctional in the Wiki for a while and on top of it, the injectPlugin.js caused Wiki build errors which had to be removed to make sure other updates get pushed to the Wiki https://github.com/w3f/polkadot-wiki/pull/2661

I tried looking up legacy instructions on how to get these working - https://github.com/w3f/polkadot-wiki/tree/f2fbc2ecc3375c4605f68324a0771105b90fcdac

I request everyone to look into this issue on priority

**Comment by DrW3RK** [comment]
I see that this issue on fixing injections was marked resolved. https://github.com/w3f/polkadot-wiki/issues/2443
Not sure when exactly they stopped working

**Comment by salmad3** [comment]
The injections work with the following changes: https://github.com/w3f/polkadot-wiki/pull/2669 
This PR was reverted as the build failed. Strangely enough, I was able to get this working locally without running into the issue with the ES Module configuration, but eventually ran into the same error.

**Comment by jakehemmerle** [comment]
#2629 (at least learn-staking) is not related to injections. No [conditional rendering](https://github.com/w3f/polkadot-wiki#conditional-rendering) is being used in the file anywhere, eg. https://github.com/w3f/polkadot-wiki/blob/master/docs/learn/learn-staking.md?plain=1#L454

**Comment by salmad3** [comment]
> #2629 (at least learn-staking) is not related to injections. No [conditional rendering](https://github.com/w3f/polkadot-wiki#conditional-rendering) is being used in the file anywhere, eg. https://github.com/w3f/polkadot-wiki/blob/master/docs/learn/learn-staking.md?plain=1#L454

Oh I added conditional rendering: https://github.com/w3f/polkadot-wiki/pull/2644

**Comment by salmad3** [comment]
The following has been in addressed in: https://github.com/w3f/polkadot-wiki/pull/2676 & https://github.com/w3f/polkadot-wiki/pull/2678
