### ISSUE TITLE
Add more information about alternative implementations

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#267]
Email Kamil and Amir regarding this

**Comment by salmad3** [comment]
## Polkadot Runtimes
- https://github.com/soramitsu/kagome
- https://github.com/ChainSafe/gossamer
- https://github.com/opennetsys/golkadot (development is stale)
- Java :O https://github.com/polkadot-java (development is stale)

## Others
- https://github.com/centrifuge/go-centrifuge (Substrate Go API client)
- https://github.com/scs/substrate-api-client (Substrate Rust API client)
