### ISSUE TITLE
Add warning about Digital Ocean Network Abuse

### ISSUE THREAD

**Issue by arrudagates** [w3f/polkadot-wiki#2680]
**Is your feature request related to a problem? Please describe.**
I recently had my Digital Ocean account permanently blocked due to what they called "suspicious activities", upon review of their [Acceptable Use Policy](https://www.digitalocean.com/legal/acceptable-use-policy/) I noticed that "Mining of Cryptocurrencies" is forbidden without a written permission (from them, I guess?), so being on Digital Ocean leaves your node at risk of being shut down at any time without warning. (Emails with proof that my node was shut down can be provided if needed.)

**Describe the solution you'd like**
My solution is to just add a warning to the wiki page next to the Digital Ocean link.

**Describe alternatives you've considered**
I think there's not really an alternative, the wiki should let people know about this before they go ahead and set up a node in Digital Ocean, so they can evaluate the risk themselves.

**Comment by salmad3** [comment]
Thanks for raising this @arrudagates
