### ISSUE TITLE
Fix link for looking up errors in Polkadot

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#2687]
https://wiki.polkadot.network/docs/maintain-errors#polkascan-and-subscan

_By looking at the runtime code we see that the pallet at index 5 is Balances. Now we will check the Balances pallet's code which is hosted in the Substrate repository, and look for the fourth error in the Error enum. According to its source the error that we got is InsufficientBalance or in other words "Balance too low to send value"._

The runtime code does not link to the correct location (list of pallets).

We should link to a permanent location instead of a line number because any update to the code would change the line number.

**Comment by salmad3** [comment]
Good point, I remember we updated this a few weeks back.
