### ISSUE TITLE
Treasury page bad formatting

### ISSUE THREAD

**Issue by michalisFr** [w3f/polkadot-wiki#2690]
The treasury page:
https://wiki.polkadot.network/docs/learn-treasury
has some variables that are not displayed properly. I'm guessing to display the relevant info based on if you're on the Polkadot wiki or the Kusama one.

Example:
<img width="801" alt="Screenshot 2021-10-05 at 3 11 31 PM" src="https://user-images.githubusercontent.com/45905709/136020215-e80e4fde-99f4-4b11-843e-d14943c74406.png">

I'm not sure if this affects other pages as well

**Comment by michalisFr** [comment]
@DannyS03 The page looks fine for me now 🤷‍♂️

**Comment by salmad3** [comment]
Thats good, yes just checked again and LGTM

We updated the conditional rendering recently so perhaps it was a cached version
