### ISSUE TITLE
Deadlinks on Kusama wiki index page

### ISSUE THREAD

**Issue by jimmychu0807** [w3f/polkadot-wiki#2698]
Links below the pretty images on https://guide.kusama.network/docs/kusama-index/ are all deadlinks.

It will be great to fix (maybe just removing the images and links?) by end of next week, as this page will be highlighted to hackathon participants happening two weeks later.

![Screenshot 2021-10-07 at 09 51 30](https://user-images.githubusercontent.com/898091/136308032-c05a6cba-4b80-4d68-9ab0-53e7c292fde9.png)

**Comment by salmad3** [comment]
Thanks @jimmychu0807, it will be updated shortly via https://github.com/w3f/polkadot-wiki/pull/2630

**Comment by salmad3** [comment]
Which hackathon if you don't mind me asking:)

**Comment by jimmychu0807** [comment]
It is Polkadot Hackathon: APAC. It will be officially announced next week.
