### ISSUE TITLE
Can't start project

### ISSUE THREAD

**Issue by VuHoang19** [w3f/polkadot-wiki#2701]
![image](https://user-images.githubusercontent.com/91931745/136521861-5a6b6379-cb13-4b92-8389-a0c0e96caf94.png)

**Comment by VuHoang19** [comment]
I want to create a translation to Vietnamese language. But I can't run this project locally due to this error

**Comment by VuHoang19** [comment]
this issue also fixes by remove injectPlugin.js

**Comment by DrW3RK** [comment]
Running `yarn polkadot:build` creates this missing file. Need to update the instructions on how to build and run the Wiki locally
