### ISSUE TITLE
Vietnamese translation

### ISSUE THREAD

**Issue by VuHoang19** [w3f/polkadot-wiki#2707]
Please create vietnamese support. I will supply md file to this project

**Comment by salmad3** [comment]
Hey @VuHoang19, have you checked this out: https://wiki.polkadot.network/docs/contributing#helping-with-translations? We are currently cleaning up the process for translations: https://github.com/w3f/polkadot-wiki/issues/2398

Let's get in touch on Element: @danny:web3.foundation

**Comment by VuHoang19** [comment]
Not found Vietnamese project. So i make this issue
