### ISSUE TITLE
Add tutorials for Statemint/e

### ISSUE THREAD

**Issue by joepetrowski** [w3f/polkadot-wiki#2719]
Follow up to https://github.com/w3f/polkadot-wiki/pull/2718

Make tutorials for:
- How to create/manage a fungible asset class (targeted at advanced users)
- How to use assets on Statemint/e (targeted at normal users)
- Ditto for non-fungibles

**Comment by salmad3** [comment]
Non-fungibles can also be covered in: https://github.com/w3f/polkadot-wiki/issues/2455

**Comment by salmad3** [comment]
Also pending Statemint deployment on Polkadot

**Comment by paradox-tt** [comment]
How to setup a collator on Statemint/e ?

**Comment by salmad3** [comment]
Reopening as documentation still needed for Statemint

When ready, the doc can be placed under the Learn > Basics > Tokens and Assets section for the Polkadot Wiki, and the recent doc is better suited under the What to Try > Assets section on the Kusama Guide.

**Comment by filippoweb3** [comment]
This issue can be linked to [this](https://github.com/w3f/polkadot-wiki/issues/3517) larger issue (that is almost resolved) about video tutorials.

**Comment by filippoweb3** [comment]
@joepetrowski can you check if the newest three videos here (https://youtube.com/playlist?list=PLOyWqupZ-WGuAuS00rK-pebTMAOxW41W8) satisfy your request? If yes, we can close this issue. Thanks!

**Comment by joepetrowski** [comment]
Yes, although we'll need new ones for NFT 2.0 :)
