### ISSUE TITLE
Reduce `git` Size & Bloat

### ISSUE THREAD

**Issue by nuke-web3** [w3f/polkadot-wiki#2735]
This repository cloned is ~ 465.4 MiB . Is this all required? Anything that could be done to reduce this easily?

**Comment by salmad3** [comment]
Right, we could benefit from a clean up. We did a restructure of the repo not too long ago and took out a bunch of file that were unused or from the previous site version; this was preserved on a branch called `preserve`.

**Comment by salmad3** [comment]
Considering our intent to do a complete revamp, this can be captured in a future master issue. Please reopen if otherwise.
