### ISSUE TITLE
Document Substrate Connect

### ISSUE THREAD

**Issue by salmad3** [w3f/polkadot-wiki#2738]
https://substrate.io/substrate-connect/

**Comment by nuke-web3** [comment]
Just noticed this issue by happy accident :partying_face: 

Some content is already [here](https://github.com/substrate-developer-hub/substrate-docs/blob/main/v3/docs/05-integrate/c-substrate-connect/index.mdx) in case you missed it :wink: 

In general, may I ask the wiki maintainers collaborate with the [devhub](https://github.com/substrate-developer-hub/substrate-docs/) on anything Substrate specific? We can open an issue to get our attention over there and work together :handshake:

**Comment by salmad3** [comment]
Yes, sounds good :)
