### ISSUE TITLE
Participate in Democracy: add places to discuss

### ISSUE THREAD

**Issue by Elodie-w3f** [w3f/polkadot-wiki#2750]
Felixwatts, a community member on the Polkadot Discord server asked: 
_"regarding Polkadot referenda, is there a place where the proposals are discussed online?"_

I shared the links of the #Polkadot-direction channel (https://matrix.to/#/#polkadot-direction:matrix.parity.io) as well as Polkassembly (https://polkadot.polkassembly.io/referenda)

This person highlighted the fact that this information doesn't appear on the wiki page "[Participate in Democracy](https://wiki.polkadot.network/docs/maintain-guides-democracy)"

Is it possible to update this page to add the links of places to discuss proposals, etc. ?

**Comment by DrW3RK** [comment]
Fair! We can add these links to the Wiki page
