### ISSUE TITLE
[Feature Request] Dark mode & switch button?

### ISSUE THREAD

**Issue by nuke-web3** [w3f/polkadot-wiki#2758]
My eyes would thank you **so so so much**

I know this is possible, and within branding guidelines without too much effort. Here is an example from @DrW3RK :
https://github.com/DrW3RK/polkadot-mooc
![image](https://user-images.githubusercontent.com/35669742/138199647-148e02f4-cc17-4550-b29d-696b90c14786.png)

**Comment by nuke-web3** [comment]
In fact, in console I can change `data-theme="dark"` and this already is most of the way there :grin: - needs some settings tweaked to work and a button to toggle.

![image](https://user-images.githubusercontent.com/35669742/138199929-95f70023-58f3-4e75-918e-84b591d098f3.png)

**Comment by salmad3** [comment]
Ah nice, I've thought of this too (habit of using everything in dark mode)

**Comment by salmad3** [comment]
![image](https://user-images.githubusercontent.com/25497083/138666606-236bf581-3d52-4ed0-99c0-dc8f09fb5823.png)

**Comment by salmad3** [comment]
Considering our intent to do a complete revamp, this can be captured in a future master issue. Please reopen if otherwise.

**Comment by nuke-web3** [comment]
if you plan to eventually get to this, it is a common practice _not_ to close the issue. IMHO this should remain open until it is abandoned or implemented 🙏
