### ISSUE TITLE
Extrinsics page only accepts Plancks

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#2760]
We need to figure out where we reference this (anywhere we call extrinsics directly) in the wiki and update.

"If you don't know, in the extrinsics page all amount fields were changed to plancks. Jaco says it's not possible to change it back to the way it was atm because of the v14 metadata update. So we need to update any relevant articles." - from Michalis

**Comment by salmad3** [comment]
Based on "Jaco pushed a UI update and the extrinsics page has the option again to enter amounts in DOT (or other denominations)." we can close. We can however add a note about Plancks. Please reopen if otherwise.
