### ISSUE TITLE
Add Conditional Rendering to Remaining Kusama Guide pages

### ISSUE THREAD

**Issue by DrW3RK** [w3f/polkadot-wiki#2765]
There are a few pages for which conditional rendering is not implemented or not working as expected, resulting in confusing instructions with references to DOTs. Here are a few pages -

https://guide.kusama.network/docs/learn-balance-transfers
https://guide.kusama.network/docs/thousand-validators
https://guide.kusama.network/docs/learn-governance
https://guide.kusama.network/docs/learn-identity (Registrars section)
https://guide.kusama.network/docs/build-pdk (How to test your Parachain. Also. a figure is missing in How to Connect to a Parachain section)

Review thoroughly on all pages as a part of the PR

**Comment by salmad3** [comment]
Please reopen if other sections need to be updated. Closing.
