### ISSUE TITLE
Create a `Time -> Block Number` Calculator

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#2766]
e.g. estimate what block height will be five hours from now, or at a particular date

Might be a good JavaScript program for Alex to put together?

**Comment by salmad3** [comment]
Alex was working on this, see the `chau-tools` branch. We should target him through 1KC.

**Comment by xlc** [comment]
We built this https://parachain-utilities.vercel.app/block-time http://github.com/AcalaNetwork/parachain-utilities

**Comment by salmad3** [comment]
Pending fix for rendering only on client side

**Comment by DrW3RK** [comment]
Implemented https://wiki.polkadot.network/docs/learn-auction
