### ISSUE TITLE
Update Account Proxies Page to Include Crowdloan

### ISSUE THREAD

**Issue by wpank** [w3f/polkadot-wiki#2774]
There is a new crowdloan proxy type that can be used to contribute to crowdloans. The proxy page should be updated to include this.

**Comment by salmad3** [comment]
Nice, would also add as a contribution method in https://wiki.polkadot.network/docs/learn-crowdloans#supporting-a-crowdloan-campaign

**Comment by DrW3RK** [comment]
Right, but there is a catch. The key use case for this proxy account would be to set it up for cold wallets like Ledger or Parity signer. If used with Ledger, claiming the crowdloan rewards will not be possible if the parachain dispatches them to Ledger account's substrate based on-chain address. With Parity Signer, there seems to be a solution which needs to be linked to the Wiki page - https://github.com/paritytech/parity-signer/issues/848

@wpank In the code, this is referred to as an Auction Proxy. What should we call it in the wiki? Crowdloan or Auction proxy? https://github.com/paritytech/polkadot/blob/master/runtime/kusama/src/lib.rs#L1080
