### ISSUE TITLE
Adding best practices and Chainlink oracles information to Polkadot Wiki

### ISSUE THREAD

**Issue by jplatts12** [w3f/polkadot-wiki#279]
We need to make all Substrate chain builders aware of best practices for rolling your own oracle. We should also make clear in our Wiki that if a chain needs an oracle, they should be aware that Chainlink provides high quality oracles for Substrate based chains.

Two places where information on oracles exist on the Wiki now: 
- https://wiki.polkadot.network/docs/en/build-build-with-polkadot#what-is-the-difference-between-building-a-parachain-a-parathread-or-a-smart-contract
- https://wiki.polkadot.network/docs/en/build-examples-index#community

**Comment by Swader** [comment]
I don't think we should recommend any oracle service in the wiki, just like we won't be recommending any third party parachains outright. I also think this is more substrate.dev territory than Polkadot wiki, but we could add some information once parachains become a thing and we can actually do something with the oracles we build.

**Comment by lsaether** [comment]
It's probably is a good idea to have a page that covers oracles in general, how the oracle problem is hard, and why certain approaches are better than others. For now it will be a survey but as time goes on it can be more specific about parachains that are deployed.
