### ISSUE TITLE
[Feature Request] Usage of Proxies

### ISSUE THREAD

**Issue by gilescope** [w3f/polkadot-wiki#2801]
polkadot-wiki/docs/learn/learn-proxies.md is great at documenting how to create and destroy a proxy. It would be great if it answered some of the proxy usage questions:

will I see the funds of the original account in the proxied account if I am using a wallet / polkadot.js? If not, is there a way to see that the proxy has those funds under management?
Eg. when voting through a proxy accout the brand ui only shows the dots that exist in the proxy accout and not also the proxied accout - we are left wondering if we vote will it count the proxied votes too or do we have to do anything extra? 
Is entering into a crowdloan any different? There's mention to check as far as rewards go but no mention of if one has to participate in the crowdloan using the ui or if one has to do it through polkadot.js's developer / extrinsics...
Is nominating from a proxied account the same?

I am happy to raise a PR if we can come up with some good answers to these questions.

**Comment by salmad3** [comment]
Thanks for raising this @gilescope

Were you thinking like a "Use cases" or "Things to consider" type of sub-section under "Why Use a Proxy"?

**Comment by salmad3** [comment]
The questions are good, I believe this covers a little of everything

**Comment by gilescope** [comment]
Maybe a proxy usage faq? I suspect there’s a fair few questions. E.g. for
the moonbeam crowdloan both the proxy and proxied address needed to be
specified. I assume that’s probably a requirement for others too.

**Comment by DrW3RK** [comment]
Seen on one of the community chat rooms - _I'm trying to use the proxy now, but its confusing, even the docs don't seem to explain it:_
https://wiki.polkadot.network/docs/maintain-guides-democracy#voting-with-a-governance-proxy

The docs can benefit from latest tutorials on how to use each proxy

**Comment by salmad3** [comment]
After looking at the state of this feature request, it seems this would be another task to try out in the 1KC pilot program, potentially finding a contributor who has experience with proxies.

**Comment by Imod7** [comment]
I noticed also that in the steps on how to [add a proxy](https://wiki.polkadot.network/docs/learn-proxies#how-to-set-up-a-proxy) it mentions the `addProxy(proxy, proxy_type)` function and I think the function now is `addProxy(delegate, proxyType, delay)` so with different parameters. 
I double checked it in :
- [PolkadotJS explorer](https://polkadot.js.org/apps/#/explorer) > Developer > Extrinsics section and 
- Substrate > [Proxy Pallet](https://github.com/paritytech/substrate/blob/f318350b6410ef47e438aae24c0b4779373d0a7b/frame/proxy/src/lib.rs#L234)

**Comment by dingding111111** [comment]
When you create a proxy account, the funds of the original account are moved to the proxy account, which becomes the new owner of those funds. So if you are using a wallet or polkadot.js to interact with the proxy account, you will see the funds that are under the management of the proxy. However, you won't be able to see the funds of the original account unless you have access to that account.

When you vote through a proxy account, the votes will be counted based on the balance of the proxy account. The votes will not be counted based on the balance of the original account. So if you want your votes to be counted based on the balance of the original account, you will need to vote directly from that account.

Entering into a crowdloan with a proxy account is not fundamentally different from entering into a crowdloan with a regular account. You can participate in a crowdloan using the UI or through extrinsics in polkadot.js developer tools. However, when you are using a proxy account to participate in a crowdloan, you need to make sure that you have authorized the crowdloan on behalf of the proxy account.

Nominating from a proxied account is similar to nominating from a regular account. When you nominate from a proxy account, you are effectively nominating on behalf of the original account. The rewards earned by the proxy account will be sent to the proxy account, not the original account. However, the original account will still be responsible for paying any transaction fees associated with the nomination.

**Comment by laboon** [comment]
> When you create a proxy account, the funds of the original account are moved to the proxy account, which becomes the new owner of those funds. 

This isn't correct. Creating a proxy doesn't transfer any funds.

> When you vote through a proxy account, the votes will be counted based on the balance of the proxy account. 

This also is not correct.  The whole point of a governance proxy is that you can vote on behalf of the proxied account.

Actually reading through all of this and there's a lot of incorrect information. @dingding111111 from where did you get this information? Or is it ChatGPT-generated?

**Comment by dingding111111** [comment]
Yes . It was chatGPT - generated. thanks for emailing and correcting me. I’m sorry for post it after read your email.

I didn’t even read your questions properly, and after got answer from chatGPT , I thought I could make myself smart .

It won’t happen again .

Regards

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by DrW3RK** [comment]
Added requested content

https://wiki.polkadot.network/docs/learn-proxies

https://wiki.polkadot.network/docs/learn-proxies-pure
