### ISSUE TITLE
Differences between archive nodes and full nodes (pruning)

### ISSUE THREAD

**Issue by lsaether** [w3f/polkadot-wiki#283]
What are the capabilities of a full node with pruning? What are the expected storage requirements of a pruned full node of the Relay Chain? ... of a parachain?

**Comment by lsaether** [comment]
@Swader Any update on this? Would be fine to just have a single paragraph on one of the node pages giving an overview of what pruning is, why someone would use it, and why someone would _not_ want to use it (if they need full history for whatever reason).

**Comment by Swader** [comment]
On it. Closing today.
