### ISSUE TITLE
Polkadot 2.0 features and additions

### ISSUE THREAD

**Issue by lsaether** [w3f/polkadot-wiki#285]
What will be the major research directions for Polkadot 2.0?

- Heirarchical relay chains
...

**Comment by krichard410** [comment]
Should we ask the research team for help on this ticket? I think someone there could help =)

**Comment by krichard410** [comment]
I'm thinking this could be added as a small section on the polkadot launch phase page, after you read thru what the version 1.0 has to offer (depending on how much content there is)
