### ISSUE TITLE
[Feature Request] slot auctions in detail

### ISSUE THREAD

**Issue by nuke-web3** [w3f/polkadot-wiki#2874]
https://wiki.polkadot.network/docs/maintain-polkadot-parameters#periods-of-common-actions-and-attributes
I would want to see explicitly what parameters there are now for parachains 

---

https://wiki.polkadot.network/docs/learn-auction
Might be missing it, but cannot find details in writing of the processes explained here
https://youtube.com/watch?v=qGjCYl2awkM

**Comment by samelamin** [comment]
I think this is a good idea. 

Our community were confused as to why a slot ended with a winner but the end period was still going 

Perhaps having it stated clearly that the end period will continue on regardless might make it clearer to new people to the ecosystem
