### ISSUE TITLE
Add steps for decoding call data (to know what you're signing)

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#2880]
Polkadot-JS extension only shows raw call data. We can use Polkadot-JS App to decode it. We should let people know so that 

1. Before submitting transaction, copy call data
2. Go to https://polkadot.js.org/apps/#/extrinsics/decode
3. Paste call data in window
4. Verify it's what you expect
5. Go back to Polkadot-JS extension and approve

<img width="560" alt="Screenshot 2021-12-15 at 12 42 01" src="https://user-images.githubusercontent.com/1417717/146180910-78a50db9-e5e6-4ca9-9585-1e6162602fd4.png">

![Screenshot 2021-12-15 at 12 46 48](https://user-images.githubusercontent.com/1417717/146181059-0c2c4f65-97a0-46be-84fe-153594a84ee0.png)

**Comment by laboon** [comment]
Note that another way to deal with this is simply update your metadata for that chain... then you will be able to have Polkadot-js extension parse the call data for you.

**Comment by salmad3** [comment]
Have this written out, and thinking that it goes well on page like https://github.com/w3f/polkadot-wiki/issues/2441, but not sure where it fits best atm. Thoughts @DrW3RK @emresurmeli?
