### ISSUE TITLE
Staking page, Slashing section issues

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#2936]
https://wiki.polkadot.network/docs/learn-staking#slashing

"Let us run through a few examples to understand this equation. In all of the examples, assume that there are 100 validators in the active set."

But there are no examples below that...

"The penalty would be Min((3 5 / 100)^2, 1) = 0.0225, or a 2.25% slash. If 20 validators equivocate, this is a much more serious offence and possibly indicates a coordinated attack on the network, and so the slash will be much greater - Min((3 20 / 100)^2, 1) = 0.36, or a 36% slash on all of these validators and their nominators. All slashed validators will also be chilled."

There are some extraneous italics here..

**Comment by emresurmeli** [comment]
https://polkadot.network/blog/grandpa-equivocation-and-sysinfo-process-collection-results-in-slashing-on-kusama-network-a-post-mortem/

A good resource to add to the "learned lessons" section.

**Comment by DannyS03** [comment]
The above refers more to https://github.com/w3f/polkadot-wiki/issues/2612. The page also needs an update and we should consider another way of presenting equations. PR is open to address the example issue and will leave the rest to our task for 1KC as it fits well.

**Comment by DannyS03** [comment]
> 

The above refers more to https://github.com/w3f/polkadot-wiki/issues/2612. The page also needs an update and we should consider another way of presenting equations. PR is open to address the example issue and will leave the rest to our task for 1KC as it fits well.

**Comment by salmad3** [comment]
> https://polkadot.network/blog/grandpa-equivocation-and-sysinfo-process-collection-results-in-slashing-on-kusama-network-a-post-mortem/
> 
> A good resource to add to the "learned lessons" section.

The above refers more to https://github.com/w3f/polkadot-wiki/issues/2612. The page also needs an update and we should consider another way of presenting equations. PR is open to address the example issue and will leave the rest to our task for 1KC as it fits well.
