### ISSUE TITLE
Add description of Para validators 

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#2973]
Z
In the polkadot.js staking overview there is an indication for "para validator" and I can't find any documentation about it. Can anyone explain what this means and what the implications of it are?

Paradox | ParaNodes.io@paradoxxx:matrix.org
Z: A para validator is one of 200 validators randomly selected (per epoch) to participate in validation of parachain blocks.
These validators will work in groups of 5 to validate parachain blocks and will be rewarded with 20 era points for each parachain block that they've validated.
Z
OK, thank you. Any idea why 97 validators don't participate in validating parachain blocks?
Paradox | ParaNodes.io@paradoxxx:matrix.org
I can't find a reference to this term specifically on the Polkadot Wiki but if you'll like to know technically what's happening under the hood, please read this article -> https://medium.com/polkadot-network/the-path-of-a-parachain-block-47d05765d7a
I believe the number of 200 was determined from technical parameters.  On Kusama even though there's 1000 validators, 200 validators are still selected to be Paravalidators each epoch.
97 in this case is just the remainder (297-200) as in Kusama 800 is the remainder (1000-200)

From watercooler

**Comment by salmad3** [comment]
Thanks, we recently added para-validators in the description for era points on https://wiki.polkadot.network/docs/maintain-guides-validator-payout#era-points

- will update https://wiki.polkadot.network/docs/learn-validator
- will edit and tweak https://wiki.polkadot.network/docs/maintain-guides-validator-payout
- will update "taking the case for one parachain" on https://wiki.polkadot.network/docs/learn-collator to refer to para-validators
