### ISSUE TITLE
Society Pallet / Kappa Sigma Mu

### ISSUE THREAD

**Issue by lsaether** [w3f/polkadot-wiki#300]

**Comment by Swader** [comment]
Do we need to document this? I see it as a throwaway pallet that was a fun experiment but isn't really kicking ass. Isn't this better suited for the pallet's documentation itself, in particular because it's not possible to create multiple societies right now?

**Comment by lsaether** [comment]
Needs an entry in the Kusama guide for sure. I don't think there's any plans to throw away the Kappa Sigma Mu fraternity or stop the Kusama human blockchain project.
