### ISSUE TITLE
Update Parity Signer Instructions & Add Info for Latest Version 

### ISSUE THREAD

**Issue by DrW3RK** [w3f/polkadot-wiki#3012]
Update the parity signer instructions with latest app interface and create a Video tutorial for the same

**Comment by salmad3** [comment]
Thanks @DrW3RK. We had this recently opened and was addressing it to also include a new tutorial: https://github.com/w3f/polkadot-wiki/issues/2987. In this case, let's combine both issues.

**Comment by salmad3** [comment]
Since we've created this: https://github.com/w3f/w3f-education, we can track the new video with a separate issue and keep this issue limited to Wiki content.

**Comment by DrW3RK** [comment]
@DannyS03 Was not aware of this issue https://github.com/w3f/polkadot-wiki/issues/2987 Yeah, makes sense to move the video to education repo, which I already did. Were you already working on the new version? I was not aware of this learning curve and signed up to update the instructions for the (legacy) app, now only available on Android.

**Comment by DrW3RK** [comment]
The scope for issue #2987 seems more than what I mentioned here. I would close this issue (as I moved it to Tech Ed repo) and reopen the original issue. I am happy to contribute to it when making the video.
