### ISSUE TITLE
Add Root Origin to Glossary

### ISSUE THREAD

**Issue by DrW3RK** [w3f/polkadot-wiki#3014]
From the watercooler - elshigori
There are not much information on ["root origin" at wiki](https://wiki.polkadot.network/search?q=Root%20origin). Where is it possible to read a description of it? Wiki gives only intuition about this concept.

Rob's answer: Root is a special origin that, by convention, can do anything. It has 'admin' permissions in several modules

**Comment by salmad3** [comment]
Saw this, my concern is that we aren't treating the glossary as a glossary. 

EDIT: Appendix misleads the idea. Idea is to have something like a Miscellaneous doc
~We should consider adding an Appendix and expand on certain topics. @DrW3RK @emresurmeli what do you think about adding an Appendix?~

**Comment by DrW3RK** [comment]
Glossary needs to be updated with definitions of the jargon used in the Wiki. If we plan on adding a Miscellaneous topics doc for all the topics that cannot live on a dedicated Wiki doc, some of the Glossary terms can be elaborated there. IMO, Appendix does not make sense to Wiki where there is no limitation on how much you can elaborate on a given topic in a doc.
