### ISSUE TITLE
Explain how long a lock period is in voluntary locking / conviction voting section

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#3041]
Here: 
https://wiki.polkadot.network/docs/learn-governance#voluntary-locking

It just sys how many lock periods ( = launch periods). We should either grab the value directly from the same variable as the parameters page gets it or link the parameters page ( https://wiki.polkadot.network/docs/kusama-parameters or https://wiki.polkadot.network/docs/maintain-polkadot-parameters)

**Comment by alfarok** [comment]
Hey @emresurmeli, I have been reading up on governance a bit this morning and want to double check my understanding on the locking period for voting. 

If I commit my tokens to a lock period of 32, I am agreeing to lock for 896 days (32 * 28) and my voting power is multiplied by 6 compared to someone committing to a single lock period (28 days)?

**Comment by laboon** [comment]
Correct @alfarok . You can see this when you vote for something https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.polkadot.io#/democracy -

![Screenshot 2022-06-17 at 18 25 47](https://user-images.githubusercontent.com/1417717/174338647-9c7d9bc1-3164-4823-aee2-745f8a4ca15a.png)

**Comment by alfarok** [comment]
Thanks @laboon! I will starting working on a PR for this one.
