### ISSUE TITLE
Account Generation Page

### ISSUE THREAD

**Issue by lsaether** [w3f/polkadot-wiki#307]
We have account generation instructions on the [Claims page](claims.polkadot.network) and some walkthrough on the Kusama guide. We need to migrate this information into its own dedicated page on the wiki so we have somewhere to link people to when they ask how to generate an account.

**Comment by Swader** [comment]
There's some talk of accounts in [learn-accounts](https://wiki.polkadot.network/docs/en/learn-accounts#obtaining-and-managing-an-address) too - did you want to go more specific? Like a full walkthrough? If so, which method(s)?

**Comment by lsaether** [comment]
Yeah, basically we want to incorporate all the information that currently lives on the Claims page into an account generation page. So we would expand a lot on that section in accounts. I'll have a PR in a bit that does this.

**Comment by lsaether** [comment]
Right now we have Polkadot.js plugin, Polkadot.js Browser, subkey, Coinbase, and Parity Signer (coming soon). Is there anything else we should include?

**Comment by Swader** [comment]
Nothing comes to mind

**Comment by Swader** [comment]
Though soon there will be a metamask plugin to do the same thing
