### ISSUE TITLE
Fix CI link detection

### ISSUE THREAD

**Issue by lsaether** [w3f/polkadot-wiki#309]
Right now our builds are "failing" because the link detection is picking errors for valid links. 

Related #270 was not finished but merged. 

@fgimenez is there some quick fix we can do in the mean time to get green builds on link detection job?

**Comment by fgimenez** [comment]
We can go back to the previous detection system until we find a way to work with the new requirements (tracked here https://github.com/w3f/infrastructure/issues/124), i'll propose a PR for that.

**Comment by fgimenez** [comment]
@lsaether proposed here https://github.com/w3f/polkadot-wiki/pull/310
