### ISSUE TITLE
Lazy Payouts

### ISSUE THREAD

**Issue by Swader** [w3f/polkadot-wiki#313]
Update staking, nominating, and validating with references to Lazy Payouts.

**Comment by lsaether** [comment]
Vesting is likewise lazy now too

**Comment by laboon** [comment]
So re: vesting, you have to "claim" your vested tokens now?

**Comment by laboon** [comment]
We don't have a section on vesting, so I will add a separate issue for that.

**Comment by laboon** [comment]
https://github.com/w3f/polkadot-wiki/issues/320
