### ISSUE TITLE
Audit Links and Redirects

### ISSUE THREAD

**Issue by salmad3** [w3f/polkadot-wiki#3136]
Periodic check for all links, references & redirects

**Comment by alfarok** [comment]
The following audit was performed by parsing the tree of markdown elements for all `.md` files under `polkadot-wiki/docs`.  The parser returns all of the http and https href elements from the recursive search.  A `GET` request is made to each result to see if a successful `200` response is returned.  If not, the url and documentation source are logged.  This audit does not check for local links within a single markdown file such as `[Local Link](#local-link)`.  This test revealed 22 links that are failing or redirecting to generic pages.

**Results:**
|File|Error|Tag|Url|
|---|---|---|---|
|[learn-keys.md](https://github.com/w3f/polkadot-wiki/blob/master//docs/learn/learn-keys.md)|**404**|`original forum post`|https://forum.web3.foundation/t/account-signatures-and-keys-in-polkadot/70/2|
|[learn-keys.md](https://github.com/w3f/polkadot-wiki/blob/master//docs/learn/learn-keys.md)|**404**|`Key discovery attack on BIP32-Ed25519`|https://forum.web3.foundation/t/key-recovery-attack-on-bip32-ed25519/44|
|[learn-keys.md](https://github.com/w3f/polkadot-wiki/blob/master//docs/learn/learn-keys.md)|**404**|`Account signatures and keys in Polkadot`|https://forum.web3.foundation/t/account-signatures-and-keys-in-polkadot/70|
|[learn-validator.md](https://github.com/w3f/polkadot-wiki/blob/master//docs/learn/learn-validator.md)|**404**|`Other Useful Links`|https://forum.web3.foundation/t/useful-links-for-validators/20|
|[learn-phragmen.md](https://github.com/w3f/polkadot-wiki/blob/master//docs/learn/learn-phragmen.md)|**404**|`off-chain worker`|https://docs.substrate.io/v3/concepts/off-chain-workers|
|[learn-phragmen.md](https://github.com/w3f/polkadot-wiki/blob/master//docs/learn/learn-phragmen.md)|**404**|`W3F Research Page on Sequential Phragmén Method`|https://research.web3.foundation/en/latest/polkadot/NPoS/4.%20Sequential%20Phragm%C3%A9n%E2%80%99s%20method.html|
|[learn-account-restore.md](https://github.com/w3f/polkadot-wiki/blob/master//docs/learn/learn-account-restore.md)|**404**|`this document`|https://github.com/paritytech/parity-signer/blob/master/docs/tutorials/Recover-Account-Polkadotjs.md|
|[learn-accounts.md](https://github.com/w3f/polkadot-wiki/blob/master//docs/learn/learn-accounts.md)|**404**|`Rust source`|https://github.com/paritytech/polkadot/blob/master/runtime/polkadot/src/constants.rs#L26|
|[learn-accounts.md](https://github.com/w3f/polkadot-wiki/blob/master//docs/learn/learn-accounts.md)|**404**|`Utility Scripts`|https://github.com/w3f/utility-scripts|
|[learn-accounts.md](https://github.com/w3f/polkadot-wiki/blob/master//docs/learn/learn-accounts.md)|**404**|`pubkeyToAddress.js`|https://github.com/w3f/utility-scripts/blob/master/src/misc/pubkeyToAddress.js|
|[contributors.md](https://github.com/w3f/polkadot-wiki/blob/master//docs/general/contributors.md)|**404**|`quest for developer health`|https://bruno.id/an-endomorphs-journey-to-health-part-2/|
|[grants.md](https://github.com/w3f/polkadot-wiki/blob/master//docs/general/grants.md)|**404**|`Darwinia Grants Program`|https://docs.darwinia.network/docs/en/dev-bounty#grant-program|
|[kusama-community.md](https://github.com/w3f/polkadot-wiki/blob/master//docs/general/kusama/kusama-community.md)|**404**|`Polkadot's Latest Research`|https://research.web3.foundation/en/latest/polkadot/|
|[maintain-guides-how-to-validate-kusama.md](https://github.com/w3f/polkadot-wiki/blob/master//docs/maintain/kusama/maintain-guides-how-to-validate-kusama.md)|**301**|`hasKey`|https://polkadot.js.org/api/substrate/rpc.html#haskey-publickey-bytes-keytype-text-bool|
|[maintain-guides-how-to-validate-kusama.md](https://github.com/w3f/polkadot-wiki/blob/master//docs/maintain/kusama/maintain-guides-how-to-validate-kusama.md)|**301**|`hasSessionKeys`|https://polkadot.js.org/api/substrate/rpc.html#hassessionkeys-sessionkeys-bytes-bool|
|[maintain-guides-how-to-validate-kusama.md](https://github.com/w3f/polkadot-wiki/blob/master//docs/maintain/kusama/maintain-guides-how-to-validate-kusama.md)|**404**|`Kusama forum`|https://forum.kusama.network/|
|[build-protocol-info.md](https://github.com/w3f/polkadot-wiki/blob/master//docs/build/build-protocol-info.md)|**404**|`Lock Withdraw Reasons`|https://docs.substrate.io/rustdocs/latest/frame_support/traits/enum.WithdrawReason.html|
|[build-protocol-info.md](https://github.com/w3f/polkadot-wiki/blob/master//docs/build/build-protocol-info.md)|**404**|`Vesting`|https://docs.substrate.io/rustdocs/latest/pallet_vesting/struct.Vesting.html|
|[build-tools-index.md](https://github.com/w3f/polkadot-wiki/blob/master//docs/build/build-tools-index.md)|**301**|`@polkadot/keyring`|https://polkadot.js.org/common/keyring/|
|[build-tools-index.md](https://github.com/w3f/polkadot-wiki/blob/master//docs/build/build-tools-index.md)|**301**|`@polkadot/util`|https://polkadot.js.org/common/util/|
|[build-tools-index.md](https://github.com/w3f/polkadot-wiki/blob/master//docs/build/build-tools-index.md)|**301**|`@polkadot/util-crypto`|https://polkadot.js.org/common/util-crypto/|
|[build-tools-index.md](https://github.com/w3f/polkadot-wiki/blob/master//docs/build/build-tools-index.md)|**404**|`Haskell`|https://github.com/airalab/hs-web3/tree/master/src/Codec|

@DrW3RK

**Comment by alfarok** [comment]
Ran another audit with some updated logic and found a few more.  Some additions could be intermittent failures on 3rd party sites (such as dotleap.com - their site is currently down but the org still seems to be active).

|File|Error|Tag|Url|
|---|---|---|---|
|[build-storage.md](https://github.com/w3f/polkadot-wiki/blob/master/docs/build/build-storage.md)|**404**|``Storage Value``|https://docs.substrate.io/rustdocs/latest/frame_support/storage/trait.StorageValue.html|
|[build-storage.md](https://github.com/w3f/polkadot-wiki/blob/master/docs/build/build-storage.md)|**404**|``Storage Map``|https://docs.substrate.io/rustdocs/latest/frame_support/storage/trait.StorageMap.html|
|[build-storage.md](https://github.com/w3f/polkadot-wiki/blob/master/docs/build/build-storage.md)|**404**|``Storage Double Map``|https://docs.substrate.io/rustdocs/latest/frame_support/storage/trait.StorageDoubleMap.html|
|[build-smart-contracts.md](https://github.com/w3f/polkadot-wiki/blob/master/docs/build/build-smart-contracts.md)|**404**|`contract pallet`|https://docs.substrate.io/rustdocs/latest/pallet_contracts/index.html|
|[build-smart-contracts.md](https://github.com/w3f/polkadot-wiki/blob/master/docs/build/build-smart-contracts.md)|**404**|`Patract Labs`|https://patract.io/|
|[build-node-interaction.md](https://github.com/w3f/polkadot-wiki/blob/master/docs/build/build-node-interaction.md)|**404**|`Substrate RPC API`|https://docs.substrate.io/rustdocs/latest/sc_rpc_api/index.html|
|[build-tools-index.md](https://github.com/w3f/polkadot-wiki/blob/master/docs/build/build-tools-index.md)|**404**|`Tutorials`|https://dotleap.com/tag/tutorial/|
|[build-protocol-info.md](https://github.com/w3f/polkadot-wiki/blob/master/docs/build/build-protocol-info.md)|**404**|``AccountData``|https://docs.substrate.io/rustdocs/latest/pallet_balances/struct.AccountData.html|
|[build-protocol-info.md](https://github.com/w3f/polkadot-wiki/blob/master/docs/build/build-protocol-info.md)|**404**|`reference a previous transaction`|https://docs.substrate.io/rustdocs/latest/pallet_multisig/struct.Timepoint.html|
|[community.md](https://github.com/w3f/polkadot-wiki/blob/master/docs/general/community.md)|**404**|`Dotleap.com Tutorials`|https://dotleap.com|
|[faq.md](https://github.com/w3f/polkadot-wiki/blob/master/docs/general/faq.md)|**404**|`networking documentation`|https://docs.substrate.io/rustdocs/latest/sc_network/index.html|
|[kusama-community.md](https://github.com/w3f/polkadot-wiki/blob/master/docs/general/kusama/kusama-community.md)|**404**|`Dotleap.com Tutorials`|https://dotleap.com|
|[learn-common-good-chains.md](https://github.com/w3f/polkadot-wiki/blob/master/docs/learn/learn-common-good-chains.md)|**404**|`Statemint`|https://github.com/paritytech/cumulus/tree/master/polkadot-parachains/statemint|
|[learn-nft.md](https://github.com/w3f/polkadot-wiki/blob/master/docs/learn/learn-nft.md)|**403**|`NFT on Ethereum`|https://opensea.io/assets/0x2127fe7ffce4380459cced92f2d4793f3af094a4/12598|
|[learn-phragmen.md](https://github.com/w3f/polkadot-wiki/blob/master/docs/learn/learn-phragmen.md)|**404**|`W3F Research Page on Sequential Phragmén Method`|https://research.web3.foundation/en/latest/polkadot/NPoS/4.%20Sequential%20Phragm%C3%A9n%E2%80%99s%20method.html|
|[learn-treasury.md](https://github.com/w3f/polkadot-wiki/blob/master/docs/learn/learn-treasury.md)|**404**|`Docs`|https://docs.substrate.io/rustdocs/latest/pallet_treasury/index.html|

**Comment by alfarok** [comment]
One more find that reveals several more redirects that do not redirect to the correct page:

Some references to `docs.substrate.io` don't return `404` but redirect (possibly a `302` check could be used).  The issue is they don't redirect to the correct section but instead go to the [Substrate Quick Start Doc](https://docs.substrate.io/quick-start/).  Scanning the repo this occurs roughly 49 time in 26 files after the broken links listed above have already been corrected.

I am going to look into tackling this next.  All of these links should be available under `paritytech.github.io/substrate/...`

**Comment by alfarok** [comment]
Addressed with #3442 and #3437
