### ISSUE TITLE
Transaction fee changes

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#314]
jsamol
Hi, I've noticed that the transferFee and creationFee constants are missing from Metadata in the latest release. I though that a transaction fee was calculated as baseFee + byteFee * tx.bytes + transfer/creationFee but probably I was mistaken. How do you calculate it then?

Jaco
All fees are only weight based now. You can retrieve an estimate via the payment_queryInfo RPC

**Comment by joepetrowski** [comment]
Yes, transferFee and creationFee are gone. But baseFee and byteFee still indeed exist: https://github.com/paritytech/polkadot/blob/c03658d/runtime/polkadot/src/lib.rs#L197L211

I wrote the transaction fee page after the removal of transferFee and creationFee. It is correct.
