### ISSUE TITLE
Explain Bags on Polkadot JS UI

### ISSUE THREAD

**Issue by DrW3RK** [w3f/polkadot-wiki#3156]
From Kusama Validator Lounge - 
> Hi. What does this new "Bags" selection do on polkadot.js? Anyone able to point me to the documentation?
![image](https://user-images.githubusercontent.com/86818441/161238780-f9244a70-0c77-4529-805a-9b528b553e78.png)

**Comment by DrW3RK** [comment]
Waiting for the changes in https://github.com/polkadot-js/apps/pull/7179 to be pushed to the UI

**Comment by salmad3** [comment]
Additional context: https://github.com/w3f/polkadot-wiki/issues/3239#issue-1211958088
