### ISSUE TITLE
balances.existentialDeposit missing?

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#3159]
https://wiki.polkadot.network/docs/build-protocol-info#existential-deposit

_"You can always verify the existential deposit by checking the [chain state](https://polkadot.js.org/apps/#/chainstate) for the constant balances.existentialDeposit."_

This query seems to be missing now. 

CC @joepetrowski do you know what happened to it? 

<img width="955" alt="Screenshot 2022-04-02 at 09 56 57" src="https://user-images.githubusercontent.com/1417717/161373215-29c1733e-fea3-4915-a5f4-b2d42296456f.png">

**Comment by DrW3RK** [comment]
I see it in the constants tab. I think you are on the storage tab

<img width="1376" alt="image" src="https://user-images.githubusercontent.com/86818441/161373306-30990b18-0160-4263-8b5a-35ea9c0ec004.png">

**Comment by laboon** [comment]
My mistake, thanks
