### ISSUE TITLE
[Issue] yarn build is failing with error for algolia

### ISSUE THREAD

**Issue by muddlebee** [w3f/polkadot-wiki#3169]
I took a latest pull and ran the commands mentioned here https://github.com/w3f/polkadot-wiki#running-locally
Looks like algolia has made some updates in the latest version...

**command** : yarn polkadot:build

**error** : 
> [INFO] [en] Creating an optimized production build...
[ERROR] Unable to build website for locale en.
[ERROR] ValidationError: "algolia.appId" is required. If you haven't migrated to the new DocSearch infra, please refer to the blog post for instructions: https://docusaurus.io/blog/2021/11/21/algolia-docsearch-migration

According to the doc mentioned in the logs above, a new parameter appId to be add at **polkadot-wiki/docusaurus.config.js**

**Comment by DrW3RK** [comment]
We are aware of this issue and are working with Algolia for docsearch upgrade https://github.com/w3f/polkadot-wiki/issues/3094

Meanwhile, skip updating the Master branch. Directly build the master branch on your machine

**Comment by muddlebee** [comment]
thank you so much @DrW3RK 🥳   I did what you suggested and its working :)

**Comment by salmad3** [comment]
closing this due to the temporary fix in place and the pending update to add to the configuration, please reopen if otherwise
