### ISSUE TITLE
New Page: Staking Miner

### ISSUE THREAD

**Issue by kianenigma** [w3f/polkadot-wiki#3195]
See: 

- https://github.com/paritytech/devops/wiki/Staking-Miner
- https://github.com/paritytech/polkadot/tree/master/utils/staking-miner
- https://paritytech.github.io/substrate/master/pallet_election_provider_multi_phase/index.html#signed-phase

Some notes: 

- At the end of this, please mention that this is still experimental, and the staking-miner software that comes with polkadot is not very advance and might lose some funds.

**Comment by laboon** [comment]
I can't access the first link, private repo?

**Comment by kianenigma** [comment]
ahh yeah the first one is private, I will paste the content here

**Comment by kianenigma** [comment]
> This page is still work in progress.

# Staking Miner

This is a brief intro into staking miner, what it does and how to maintain it. 

For any further assistance and/or requests, contact @kianenigma or @emostov (@zeke in Matrix).

### Functionality

The staking miner is a binary that is mostly passive, and is only activated whenever a network wants to elect a new validator set. In a sense, it *mines a validator set* (which is a computationally intense task, ergo *mining*). In principle, if the miner ever fails, the same process will happen by validators of the network in their [offchain worker API](https://substrate.dev/recipes/off-chain-workers/index.html). In the long term, we want to rely as much as possible on the staking-miner, and NOT the offchain workers. The most obvious reason for this is that the offchain workers have limited computational resources. Moreover, the incur a rather unnecessary CPU cost on validators.  

The submitted solution is packed in the form of the [`submit` transaction](https://crates.parity.io/pallet_election_provider_multi_phase/pallet/struct.Pallet.html#method.submit) and is submitted to the chain as a normal signed extrinsic. A relatively large [deposit](https://crates.parity.io/pallet_election_provider_multi_phase/pallet/trait.Config.html#associatedtype.SignedDepositBase) and transaction fee is charged as a result. If the solution is correct, the deposit is returned and [a reward](https://crates.parity.io/pallet_election_provider_multi_phase/pallet/trait.Config.html#associatedtype.SignedRewardBase) is given to the submitted, which should always, at the minimum, cover the basic transaction fee.

See [`pallet-election-provider-multi-phase`'s documentation on signed phase](https://crates.parity.io/pallet_election_provider_multi_phase/index.html#signed-phase) for more info

**Comment by emresurmeli** [comment]
Started putting this together, and just a heads up @kianenigma in the private document(https://github.com/paritytech/devops/wiki/Staking-Miner) I think the hyperlink for [offchain worker API](https://substrate.dev/recipes/off-chain-workers/index.html) might be deprecated.

Just have one question, since the staking-miner is optimizing election results using seqPhragmén, is it also used for Council elections? To be more granular, does council elections use [pallet_election_provider_multi_phase](https://paritytech.github.io/substrate/master/pallet_election_provider_multi_phase/index.html#)?

**Comment by kianenigma** [comment]
Good question: no, it does not use [pallet_election_provider_multi_phase](https://paritytech.github.io/substrate/master/pallet_election_provider_multi_phase/index.html#) it, and ergo the staking miner is not used there.

**Comment by emresurmeli** [comment]
#3357 takes care of this, @kianenigma please review when you get a chance.

**Comment by alfarok** [comment]
The above mentioned PR was reviewed and merged :+1:, closing
