### ISSUE TITLE
Create a dedicated community page with logos

### ISSUE THREAD

**Issue by lsaether** [w3f/polkadot-wiki#32]
Right now, we have a bare bones community page with links. Instead we should have a dedicated page that projects can submit their logos with links. Similar to what Docusaurus does in the "Who's using Docusaurus" section.

![image](https://user-images.githubusercontent.com/25539605/65955247-05f17800-e448-11e9-97e9-224c4ef1df98.png)

**Comment by krichard410** [comment]
This could be added to the current community page? It might fit well there along with the other social media links. Or we could place this in the landing page, perhaps?

**Comment by Swader** [comment]
Sounds good re community page, yes.

**Comment by krichard410** [comment]
Could we grab these logos from the lightpaper and place them onto the community page to start? Or are these outdated?

<img width="771" alt="Screen Shot 2020-08-25 at 8 57 32 AM" src="https://user-images.githubusercontent.com/36748441/91142415-04a8e980-e6b1-11ea-9c60-384299b33f89.png">

**Comment by krichard410** [comment]
Perhaps we could also link to this page http://polkaproject.com/

**Comment by Swader** [comment]
Likely outdated logos, and you can't grab from PDF easily. All the projects have their logos as vectors so we can ask them to provide some.

**Comment by laboon** [comment]
I'd actually like to push back against this a bit.  We don't want to imply that we _endorse_ any of these projects, and I can imagine it would be difficult to keep up to date.  And others are already providing this information for specific projects. I think the wiki should be for lower-level or abstract Polkadot topics.  This seems more like marketing.

I am closing, but I could be persuaded to re-open.
