### ISSUE TITLE
Multiple Images are missing on Contributing guidelines page

### ISSUE THREAD

**Issue by DrW3RK** [w3f/polkadot-wiki#3229]
Scroll down on https://guide.kusama.network/docs/contributing/

**Comment by salmad3** [comment]
Thanks, noticed this too when doing the asset check - it is because the images are not available in the img/ dir for kusama guide. Right now the doc is not included on the Kusama guide

**Comment by DrW3RK** [comment]
Should we remove that entire section? We are currently not supporting multiple languages on the Wiki nor accepting translations

**Comment by salmad3** [comment]
I'm not opposed to removing, it is just that we still have the service available via crowdin
