### ISSUE TITLE
Add "Querying Storage and Constants" page?

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#3235]
Not sure where exactly this would go, but can we add some more instructions on reading storage and constants and what the results mean? Something like the following exchange on Reddit I had:

W3F_Bill

Note what it says:

const balances.existentialDeposit: u128
10,000,000,000

const means that it is a constant.

balances.existentialDeposit is name of the variable (actually a constant in this case )

"u128" is the variable type - an unsigned 128-bit integer. https://doc.rust-lang.org/std/primitive.u128.html

Below it is the value, 10,000,000,000, in Plancks ( https://wiki.polkadot.network/docs/learn-DOT#polkadot ). 10 billion Plancks = 1 DOT, so the existential deposit is 1 DOT.

Meggi-Online:

enlightening.

just WHY is such an explaination not in the dot/wiki/ed ?

maybe the devs -like the kathelic church useing latein- dont want the simpletons like me to lose the admiration and praise of their knowledge advantage ;-)

https://www.reddit.com/r/dot/comments/u2vgbp/existentialdeposit_u128_under_js/

**Comment by DannyS03** [comment]
Would be good - in the meantime, will add the concepts mentioned (and other key concepts) to the misc page so they are available somewhere

**Comment by DrW3RK** [comment]
Already resolved in https://github.com/w3f/polkadot-wiki/pull/3458
