### ISSUE TITLE
Bags info example

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#3239]
Can we add an example of bags (like the one I posted on Reddit here: https://www.reddit.com/r/dot/comments/u8j2ys/staking_am_i_doing_this_right/i5q1zha/?utm_source=reddit&utm_medium=web2x&context=3) along with more information to the Staking page?  https://wiki.polkadot.network/docs/learn-staking There's no mention of bags on that page at all that I see.

Or if bags are described in depth somewhere else on the wiki, it should be linked from that page.

**Comment by salmad3** [comment]
Duplication of https://github.com/w3f/polkadot-wiki/issues/3156, will reference the above comment in the older issue
