### ISSUE TITLE
Explain information on Targets page on Polkadot-JS App

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#3240]
This should go here: https://wiki.polkadot.network/docs/maintain-guides-how-to-nominate-polkadot and/or https://wiki.polkadot.network/docs/learn-nominator

Add descriptions of what all the columns mean on the Targets (https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fpolkadot.api.onfinality.io%2Fpublic-ws#/staking/targets) page - specifically,

payout | nominators | comm. | total stake | own stake | other stake | return

Especially note that the Nominators column has two fields, Active and All, which we should explain, preferably with an example like this one I did in Matrix:

_The left column is the number of active nominators, the right all nominators. So if Nominator X has nominated validators A, B, C, and D, but is actively nominating B, then nominator X counts for both the left and right numbers for Validator B, and the right number for validators A, C, and D._

I think there may be something similar (with a screenshot, which may be out of date at this point) in the Knowledge Base that Anja did, but I couldn't find it. If it does exist, we should put a link to it on the page as well.

**Comment by wellfitness** [comment]
Thanks for the suggestion, you have solved one of my doubts. 
I support your proposal

**Comment by salmad3** [comment]
The Knowledge Base guide which explains the target's page: https://support.polkadot.network/support/solutions/articles/65000150130-how-do-i-know-which-validators-to-choose-

As the guide exists, the above can be used to enhance the already existing Knowledge Base guide where the Wiki can link to it and add more context to the https://wiki.polkadot.network/docs/learn-nominator#what-to-take-into-consideration-when-nominating section

**Comment by alfarok** [comment]
Addressed in #3423
