### ISSUE TITLE
Change screenshot in the Endorsing section - old image.

### ISSUE THREAD

**Issue by rrtti** [w3f/polkadot-wiki#3245]
If you visit the endorsing section to understand why and how a proposal is endorsed:

https://wiki.polkadot.network/docs/maintain-guides-democracy#endorsing-a-proposal

You will see all mentions of the action as "seconding" were replaced by "endorsing" but the screenshot still reads "seconding": I suggest to change this with a new screenshot.

**Comment by salmad3** [comment]
Thanks @rrtti 

The doc is listed under https://github.com/w3f/polkadot-wiki/issues/2390 which would update [all] images on the page. We intended to use the issue as one of the first contribution methods for https://github.com/w3f/1KC but has been stale thus far. Should prioritize

**Comment by rrtti** [comment]
Thank you @DannyS03 - can you let me know once the images are updated?

**Comment by salmad3** [comment]
> Thank you @DannyS03 - can you let me know once the images are updated?

Sure thing, I believe Bill and Radha are on it and it will be updated shortly
