### ISSUE TITLE
Images missing - Governance page

### ISSUE THREAD

**Issue by DrW3RK** [w3f/polkadot-wiki#3248]
Two images (Latex equations) are not rendering well - https://wiki.polkadot.network/docs/learn-governance#super-majority-approve

<img width="813" alt="image" src="https://user-images.githubusercontent.com/86818441/165089854-0bcf6de4-2999-4f25-9091-f972d3756667.png">

Refreshing the page multiple times is fixing the issue. Needs a closer look

**Comment by salmad3** [comment]
Checked on my end on the public site and seems okay: 
<img width="797" alt="image" src="https://user-images.githubusercontent.com/25497083/165222356-a9b64ce0-42dc-471b-b298-8f92766c23c4.png">

**Comment by salmad3** [comment]
Checked again and they are rendering okay. Will also be looked at as per https://github.com/w3f/polkadot-wiki/issues/3160. Please reopen if otherwise
