### ISSUE TITLE
Kusama Guide not filling page

### ISSUE THREAD

**Issue by salmad3** [w3f/polkadot-wiki#3281]
Whitespaces from webpage not "fit to screen"

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/25497083/166619689-9d0c047a-bc40-4ccc-bb4e-bf512efe1dd7.png">

**Comment by emresurmeli** [comment]
Addressed in #3290 

Danny it seems that this was due to some custom css added last summer, do you remember by chance why it was added?

**Comment by salmad3** [comment]
Cool and right there were changes made to the Kusama Guide landing page, but strange as I have been viewing it on the same ratio and browser where it fit to screen

**Comment by emresurmeli** [comment]
Currently fixed, but Roman says that it wasn't a permanent fix to change the custom CSS. Keeping this issue open till there is a permanent fix.

**Comment by DrW3RK** [comment]
Fixed with this PR https://github.com/w3f/polkadot-wiki/pull/3424
