### ISSUE TITLE
Further Context and FAQs for Asset Creation/Management on Statemine

### ISSUE THREAD

**Issue by salmad3** [w3f/polkadot-wiki#3282]
https://guide.kusama.network/docs/kusama-statemine/
- Can I delete an Asset? (How to delete an asset). Keep SEO in mind and keywords "How to delete an Asset on Statemine"; burn, mint, etc. 
- Advanced section with info and examples for multisig and proxy
- Outline if the official Polkadot Support assists with Statemine asset issues and queries

**Comment by DrW3RK** [comment]
To be tracked on this issue https://github.com/w3f/polkadot-wiki/issues/2719
