### ISSUE TITLE
Document error for not having enough free account funds

### ISSUE THREAD

**Issue by salmad3** [w3f/polkadot-wiki#3286]
I don't believe this is explicitly covered 

<img width="631" alt="image" src="https://user-images.githubusercontent.com/25497083/166632328-363fd894-7072-430b-8987-e0b1450facad.png">

**Comment by DrW3RK** [comment]
The error prompt already explains it in full detail. Closing the issue. If there is any ambiguity with the warning message displayed, it is useful to create a PR on the Apps UI.
