### ISSUE TITLE
Typo: "Polkasembly" instead of "Polkassembly"

### ISSUE THREAD

**Issue by Elodie-w3f** [w3f/polkadot-wiki#3295]
Hello,

On [this page](https://wiki.polkadot.network/docs/build-hrmp-channels), Polkassembly is misspelled several times. I attached a screenshot.

![Screenshot 2022-05-05 at 16 14 36](https://user-images.githubusercontent.com/83287807/166942905-fc46ccbb-ae03-4469-9b53-8c5f4a6f0221.png)

**Comment by DrW3RK** [comment]
Thanks Elodie! fixing it
