### ISSUE TITLE
[Feature Request] Enhance Approach to Data Analytics Page

### ISSUE THREAD

**Issue by salmad3** [w3f/polkadot-wiki#3310]
**Is your feature request related to a problem? Please describe.**

Current page on data analytics misses helpful points on data analytics and would be better presented as a general page on DeData (decentralized data).

**Describe the solution you'd like**

- Other projects can be added here in the ecosystem that offer a solution for decentralized data (e.g. data monetization, knowledge graphs). Consider changing the name of the page to Decentralized Data (or something similar) and using Data Analytics as a sub-heading.
- Add additional key concepts such as data-as-a-service.
- Point out specifics. e.g. Is SubSquid the same as The Graph, do all these solutions qualify as data-as-a-service, why is SubQuery considered data-as-a-service, and so on.
- Consider listing main explorers under "Polkadot-based Explorers"

**Comment by DrW3RK** [comment]
Thanks for the suggestions. A PR is welcome.
