### ISSUE TITLE
Update Kusama ID bonding amounts on ledger page

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#3321]
_You should now see the sub-identity displayed on-chain. You need to aware that 20.258 KSM is reserved for setting identity and 20.053 KSM for each sub-identity. This reserved account balance is freed once you [clear the identities](https://wiki.polkadot.network/docs/learn-identity#clearing-and-killing-an-identity) on the account._

I'm not sure exactly what the amount is now, but I do know it's much less than this. I think it's 1/50th of this amount after Shawn's PR last year which reduced a bunch of KSM amounts for activities on Kusama.

https://wiki.polkadot.network/docs/kusama-ledger

**Comment by DrW3RK** [comment]
This is a super weird side-effect of conditional rendering. Those are DOT amounts. Ideally, that page should not be accessible on Polkadot Wiki. The amount displayed is appropriate on Kusama guide https://guide.kusama.network/docs/kusama-ledger/

Needs a deeper look on how we do conditional rendering

**Comment by DrW3RK** [comment]
Solved it by using dedicated Kusama params variables.
