### ISSUE TITLE
Add disclaimer for Nova wallet

### ISSUE THREAD

**Issue by michalisFr** [w3f/polkadot-wiki#3345]
There's another Nova wallet, unrelated to our ecosystem:
https://novawallet.co.uk/
that links to this web wallet:
https://novawallet.net/
in which users can restore their wallet.

It doesn't _seem_ like it's a scam (despite its appearance), but it's definitely unrelated to the Polkadot ecosystem. We should put an asterisk next to Nova [here](https://wiki.polkadot.network/docs/build-wallets#treasury-funded-wallets) that explains this wallet exists, but it has nothing to do with the Polkadot ecosystem and shouldn't be confused with the treasury-funded Nova and users shouldn't restore their accounts in it.

**Comment by DrW3RK** [comment]
Fixed by https://github.com/w3f/polkadot-wiki/pull/3347
