### ISSUE TITLE
Migration of how-to guides in the General and Basics sections to the Support page

### ISSUE THREAD

**Issue by michalisFr** [w3f/polkadot-wiki#3346]
We can use this issue to find and settle on the how-to guides in the wiki that need to migrate to the Support page and track the progress of the migration. I'll update this post with a task list for each guide as we find them.

- [X] Find all how-to guides in the General and Basics wiki sections that need to migrate to the support page
- [X] Settle on the list of articles to migrate below
- [x] Prepare (create/update) all articles below
- [x] Remove/update corresponding wiki articles

### Articles to migrate
---
- [x] [Polkadot claims](https://wiki.polkadot.network/docs/claims): The whole article can be removed. Update the support article with steps of the claim process. Remove account creation material and instead link to relevant articles. (Low priority) ✅
---
- [X] [Using the Polkadot Ledger Application](https://wiki.polkadot.network/docs/learn-ledger): I propose this article be removed entirely from the wiki (the devs release isn't really supposed to be used). 

Each section has/needs its own article basically:
- [X] Ledger Live: [Article](https://support.polkadot.network/support/solutions/articles/65000175822-how-to-use-polkadot-and-stake-with-ledger-live) exists ✅
- [X] Loading your account: Articles exist for the [UI](https://support.polkadot.network/support/solutions/articles/65000170812-how-to-add-ledger-account-through-the-polkadot-js-ui) and the [extension](https://support.polkadot.network/support/solutions/articles/65000175387-how-to-add-your-ledger-through-the-polkadot-js-extension) ✅
- [x] Confirming the address on your device: We need to **create** this article. **[New article](https://support.polkadot.network/support/solutions/articles/65000181854-how-to-confirm-your-account-address-on-your-ledger-device)** ✅
- [X] Checking the balance: [Article](https://support.polkadot.network/support/solutions/articles/65000169332-where-can-i-see-the-balance-of-my-account-) exists (for all types of accounts) ✅
- [X] Sending a transfer: Article exists. **Update** with instructions on how to sign based on the specific account type (see Balance Transfers below). **[New article](https://support.polkadot.network/support/solutions/articles/65000181994)** ✅
- [x] Receiving a transfer: We need to **create** an article for types of accounts. **[New article](https://support.polkadot.network/support/solutions/articles/65000181866-how-to-receive-dot-to-my-account-on-polkadot-js-ui)** ✅
- [X] Staking: [Article](https://support.polkadot.network/support/solutions/articles/65000168057-how-do-i-stake-nominate-on-polkadot-) exists ✅
- [x] Removing expired democracy locks: We need to **create** that article for all types of accounts with specific mention to Ledger (we need to check if the batch call is supported first). **[New article](https://support.polkadot.network/support/solutions/articles/65000181870-how-to-remove-expired-democracy-locks)** ✅
----
- [x] [Statemint](https://wiki.polkadot.network/docs/learn-statemint): We need to **create** that article that refers both to Statemine and Statemint with short explanation of sufficient and non-sufficient and the scams warning (to migrate transferring assets). Leave Creating assets on the wiki. There is also [this article](https://support.polkadot.network/support/solutions/articles/65000181118-how-to-transfer-tether-usdt-on-statemine) about transferring USDT. **[New article](https://support.polkadot.network/support/solutions/articles/65000181800-what-is-statemint-and-statemine-and-how-do-i-use-them-)**✅
- [x] [Teleporting](https://wiki.polkadot.network/docs/learn-teleport): **Update** [support article](https://support.polkadot.network/support/solutions/articles/65000181119-how-to-teleport-dot-or-ksm-between-statemint-or-statemine) with the remarks at the top of the [Teleport section](https://wiki.polkadot.network/docs/learn-teleport#teleporting-tokens-using-polkadot-js-apps-ui) before migration.✅
---
- [x] [Multisig creation and usage](https://wiki.polkadot.network/docs/learn-accounts#example-with-polkadotjs): We need to **create** that article. Migrate that section only + the Decode data section (because it's specifically useful for multisigs). **[New article](https://support.polkadot.network/support/solutions/articles/65000181826-how-to-create-and-use-a-multisig-account)** ✅
---
- [X] [Account generation](https://wiki.polkadot.network/docs/learn-account-generation): The whole article can be removed. ✅

Specifically for each section:
- [X] Key security: **Create** article with basic security practices for mnemonic phrases and link to "learn scams" for more info. **[New article](https://support.polkadot.network/support/solutions/articles/65000181874-how-to-store-your-mnemonic-phrase-and-backup-file-safely)** ✅
- [X] Extension: **Update** article with step-by-step instructions. **[Updated article](https://support.polkadot.network/support/solutions/articles/65000098878-how-to-create-a-dot-account)** ✅
- [X] Subkey: [Article](https://support.polkadot.network/support/solutions/articles/65000180519-how-to-create-an-account-in-subkey) exists ✅
- [X] Polkadot-JS UI: [Article](https://support.polkadot.network/support/solutions/articles/65000180529) exists (multisig accounts will be covered in the other article above) ✅
- [X] Parity Signer: [Article](https://support.polkadot.network/support/solutions/articles/65000180512-how-to-create-an-account-in-parity-signer) exists ✅
- [X] Ledger: Articles exist for the [UI](https://support.polkadot.network/support/solutions/articles/65000170812-how-to-add-ledger-account-through-the-polkadot-js-ui) and the [extension](https://support.polkadot.network/support/solutions/articles/65000175387-how-to-add-your-ledger-through-the-polkadot-js-extension) ✅
- [X] Vanity generator: Article existed. **[Updated article](https://support.polkadot.network/support/solutions/articles/65000171416)** ✅
---
- [X] [Backing up and restoring accounts](https://wiki.polkadot.network/docs/learn-account-restore): All the sections exist as support articles (with different structure) so this whole article can be removed. Keep on the wiki only the last one `Transferring accounts from one computer to the other` but as its own article. ✅

Specific articles:
- [X] Polkadot extension: [Article](https://support.polkadot.network/support/solutions/articles/65000169952-how-to-restore-your-account-in-the-polkadot-extension) ✅
- [X] Polkadot-JS UI: [Article](https://support.polkadot.network/support/solutions/articles/65000180110-how-to-restore-your-account-in-polkadot-js-ui) ✅
- [X] Parity Singer: [Article](https://support.polkadot.network/support/solutions/articles/65000167901-how-to-restore-an-account-in-parity-signer) ✅
---
- [X] [Balance transfers](https://wiki.polkadot.network/docs/learn-balance-transfers): Article exists. Replace the section after the transfer button with links to new articles on how to sign depending on the type of account. **[Updated article](https://support.polkadot.network/support/solutions/articles/65000170304-how-to-send-transfer-funds-out-of-your-dot-account-on-the-polkadot-js-ui)** ✅

More specifically:
- [X] Polkadot-JS UI: Move information from [current article](https://support.polkadot.network/support/solutions/articles/65000170304-how-to-send-transfer-funds-out-of-your-dot-account-on-the-polkadot-js-ui) to **new article** on signing with an account on Polkadot-JS UI. **[New article] (https://support.polkadot.network/en/support/solutions/articles/65000181993)** ✅
- [X] Polkadot extension: Move information from [current article](https://support.polkadot.network/support/solutions/articles/65000170304-how-to-send-transfer-funds-out-of-your-dot-account-on-the-polkadot-js-ui) to **new article** on signing with an account in the Polkadot extension. **[New article](https://support.polkadot.network/en/support/solutions/articles/65000181989)** ✅
- [X] Parity Signer: **Create** new article on how to sign with Parity Signer, with both options `injected` (extension) and `external` (UI). **[New article](https://support.polkadot.network/en/support/solutions/articles/65000182000)** ✅
- [X] Ledger: **Create** article on how to send with your Ledger, with both options `injected` and `ledger` that includes instructions for actions on the device too. **[New article](https://support.polkadot.network/en/support/solutions/articles/65000181994)** ✅
---
- [X] [Staking FAQ](https://wiki.polkadot.network/docs/learn-staking-faq): This whole article can be migrated to the support page (and enriched) and removed from the wiki. So we need to **create** a Staking FAQ article that may also serve as a central point to staking questions/problems with links to other articles. **[New article](https://support.polkadot.network/support/solutions/articles/65000181959)** ✅
- [X] [Nomination Pools](https://wiki.polkadot.network/docs/learn-nomination-pools): Migrate only the `Pool member lifecycle` and leave the rest (intro and `Pool administration`. **Create** a new article ("How to nominate with nomination pools"). **[New article](https://support.polkadot.network/support/solutions/articles/65000181401)** ✅
---
- [X] [Identity](https://wiki.polkadot.network/docs/learn-identity): 

Migrate the following sections (and create a new folder for them):
- [X] Setting an identity: **Create** new article that includes the UI way with the supported fields, but excludes the custom fields and format caveats. These parts should remain on the wiki. **[New article](https://support.polkadot.network/support/solutions/articles/65000181981)** ✅
- [X] Requesting judgement & cancelling judgement: **Create** new article. The intro section should remain on the wiki. **[New article](https://support.polkadot.network/support/solutions/articles/65000181990)** ✅
- [X] Sub accounts: **Create** new article and migrate. **[New article](https://support.polkadot.network/support/solutions/articles/65000181991)** ✅
- [X] Clearing identity: **Create** new article and migrate. **Section added to "Setting identity" article** ✅
- [X] W3F registrar: [Article](https://support.polkadot.network/support/solutions/articles/65000179747-how-to-use-the-w3f-registrar-page) exits. ✅
---
- [X] [Treasury](https://wiki.polkadot.network/docs/learn-treasury): **Don't** migrate but **create** an article on how to tip and link to it from the corresponding wiki example. **[New article](https://support.polkadot.network/support/solutions/articles/65000181971)** ✅

**Comment by keeganquigley** [comment]
General Section

[Polkadot Claims](https://support.polkadot.network/support/solutions/articles/65000138217-how-to-claim-your-dot-tutorial) - We have an article for this already, however, it is outdated. The support article is mostly comprised of how to create an actual account. I think we could migrate this and update the guide. Although I don't know how much this is needed since most have claimed by now. Personally it's been a long time since I've seen a claims ticket.

[Polkadot Ambassador Programme](https://wiki.polkadot.network/docs/ambassadors) - Not a guide, but this could perhaps be migrated to a support article.

[Using ENS w/ DOT/KSM accounts](https://wiki.polkadot.network/docs/ens) - In my opinion this should stay on the wiki - too advanced/specific.

[Using the Polkadot Ledger Application](https://wiki.polkadot.network/docs/learn-ledger) - Parts of this article can be migrated, as we already have support articles for both adding Ledger to extension and Polkadot-JS UI. However, "using the dev release" section should stay on the wiki, along with the section on democracy locks.

[Programmes](https://wiki.polkadot.network/docs/grants) - I believe this section should stay on the wiki as it pertains to programs rather than support.

**Comment by keeganquigley** [comment]
Tokens and Assets Section

[DOT](https://wiki.polkadot.network/docs/learn-DOT) - the How To Obtain Westies guide could be migrated to a support article. Everthing else can stay on the wiki.

[Statemint](https://wiki.polkadot.network/docs/learn-statemint) - the Transferring Assets on Statemint guide could be migrated to an article. I would argue though, that creating assets is an advanced topic, therefore the Creating Assets guide can stay on the wiki.

[Teleporting Assets](https://wiki.polkadot.network/docs/learn-teleport) - there is already [an article](https://support.polkadot.network/support/solutions/articles/65000181119-how-to-teleport-ksm-to-or-from-statemine) for this which links to the wiki for more advanced info. I don't think anything needs to be added to this currently, as the wiki gives more in-depth information on how teleporting works.

**Comment by alineherzman** [comment]
**Accounts section**
[The guide on creating a multisig account on Polkadot-JS UI](https://wiki.polkadot.network/docs/learn-accounts#example-with-polkadotjs) can be migrated to a support article.

[Recommendations on storing your key and JSON file securely](https://wiki.polkadot.network/docs/learn-account-generation#disclaimer-key-security) can be combined with similar [recommendations](https://wiki.polkadot.network/docs/learn-scams#keep-your-data-secure) from the General section about scams and reworked into a support article.

The guides on creating accounts in the [extension](https://wiki.polkadot.network/docs/learn-account-generation#polkadotjs-browser-extension), [Subkey](https://wiki.polkadot.network/docs/learn-account-generation#subkey), [Polkadot-JS UI](https://wiki.polkadot.network/docs/learn-account-generation#polkadot-js-apps), and [Parity Signer](https://wiki.polkadot.network/docs/learn-account-generation#parity-signer) can be migrated. There already are support articles about creating an account in the [extension](https://support.polkadot.network/support/solutions/articles/65000098878-how-to-create-a-dot-account) (certainly can be expanded), [Subkey](https://support.polkadot.network/support/solutions/articles/65000180519-how-to-create-an-account-in-subkey) (it's more informative than in the Wiki), [Polkadot-JS UI](https://support.polkadot.network/support/solutions/articles/65000180529-how-to-create-an-account-in-the-polkadot-js-ui-), and [Parity Signer](https://support.polkadot.network/support/solutions/articles/65000180512-how-to-create-an-account-in-parity-signer).

The guides on exporting your backup file and restoring your account with it [in the extension](https://wiki.polkadot.network/docs/learn-account-restore#polkadotjs-browser-plugin) and [Polkadot-JS UI](https://wiki.polkadot.network/docs/learn-account-restore#polkadot-js) can be migrated, but probably also need a change of structure. There is a separate support article that cover [export of backup file](https://support.polkadot.network/support/solutions/articles/65000177677-how-to-export-your-json-backup-file) both in the extension and UI. Restoring with your backup file is part B of the articles about restoring in the [extension](https://support.polkadot.network/support/solutions/articles/65000169952-how-to-restore-your-account-in-the-polkadot-extension) and [UI](https://support.polkadot.network/support/solutions/articles/65000180110-how-to-restore-your-account-in-polkadot-js-ui).

The guide on restoring your account with its seed in the [extension](https://wiki.polkadot.network/docs/learn-account-restore#using-an-existing-mnemonic-seed-to-restore-an-account-with-polkadotjs-extension-preferred) and [UI](https://wiki.polkadot.network/docs/learn-account-restore#using-an-existing-mnemonic-seed-to-restore-an-account-with-polkadotjs-ui) can also be migrated. It's part A of the articles mentioned above: restoring in the [extension](https://support.polkadot.network/support/solutions/articles/65000169952-how-to-restore-your-account-in-the-polkadot-extension) and [UI](https://support.polkadot.network/support/solutions/articles/65000180110-how-to-restore-your-account-in-polkadot-js-ui).

[The guide on restoring in Parity Signer](https://wiki.polkadot.network/docs/learn-account-restore#parity-signer) can be a link to the [corresponding support article](https://support.polkadot.network/support/solutions/articles/65000167901-how-to-restore-an-account-in-parity-signer).

The guide on sending funds comes in two parts: from [Transfer](https://wiki.polkadot.network/docs/learn-balance-transfers#using-the-transfer-tab) and from [Accounts](https://wiki.polkadot.network/docs/learn-balance-transfers#from-the-accounts-page). We have [one support article](https://support.polkadot.network/support/solutions/articles/65000170304-how-to-send-transfer-funds-out-of-your-dot-account-on-the-polkadot-js-ui) for both ways.

**Staking section**
[The staking guide on Polkadot-JS UI](https://wiki.polkadot.network/docs/learn-nomination-pools#1-how-do-i-stake-my-dot) can be migrated to the [support article](https://support.polkadot.network/support/solutions/articles/65000168057-how-do-i-stake-nominate-on-polkadot-) we already have.

It's not a guide, but the [list of reasons for not receiving staking rewards](https://wiki.polkadot.network/docs/learn-nomination-pools#3-why-am-i-not-receiving-staking-rewards) can be migrated too, we have a [support article](https://support.polkadot.network/support/solutions/articles/65000170805-why-am-i-not-getting-staking-rewards-) about it.

**Comment by michalisFr** [comment]
[Identity](https://wiki.polkadot.network/docs/learn-identity): The guides on how to set an identity, requesting judgement, creating a subidentity and clearing an identity should be migrated. The registrars sections should stay on the wiki. We have a [How to use the W3F registrar](https://support.polkadot.network/support/solutions/articles/65000179747-how-to-use-the-w3f-registrar-page) that should accompany these articles (and perhaps create a section about identity).

[Nominator](https://wiki.polkadot.network/docs/learn-nominator): There is some overlap with the [bags list](https://support.polkadot.network/support/solutions/articles/65000181018-i-have-more-than-the-minimum-bonded-but-i-m-not-getting-rewards) article and the [active/inactive/waiting](https://wiki.polkadot.network/docs/learn-nominator) article, but I don't think there are any guides needing migration. Instead we should link to these wiki articles in the support articles.

[W3F Registrar](https://wiki.polkadot.network/docs/learn-registrar): This is an empty article. We can remove it entirely or link to [W3F Registrar](https://support.polkadot.network/support/solutions/articles/65000179747-how-to-use-the-w3f-registrar-page) article on the Support page.

[Transaction fees](https://wiki.polkadot.network/docs/learn-transaction-fees): This doesn't need migration, but perhaps we could write an article _in the future_ about this, if transaction ever become an issue. For now I don't think any action is needed.

[Treasury](https://wiki.polkadot.network/docs/learn-treasury): Hmm, that's a tough one. I'd say let's create an article on how to tip. We want people to participate more in the spending of treasury and tipping is an easy entry point compared to spending proposals or bounties, which should remain on the wiki. The "Tipping" section should also remain in the wiki as is, but in the "Example" section we can add a link to the support article. And in the Support article a link to the "Tipping" section and the "Treasury" article overall for "learn more".

All the other articles of the "Components" section don't have anything that could be migrated to the Support page.

**Comment by DrW3RK** [comment]
Reviewed the list of articles to be migrated. Agreeing with all the proposed actions.

Although, **complete removal** of docs like "Staking FAQ", "Polkadot claims" etc. which may have been referenced by external parties may not be a good idea. We could update the articles to have a summary and the respective forwarding links to Support page. For instance, the Staking FAQ could include questions pertaining to Phragmen algorithm, Polkadot runtime limitations etc. and a forwarding link to the support article on Staking FAQ.

The Wiki articles can be updated to answer "Why?" more than "How to?"

BTW, updated the W3F registrar doc with a forwarding link to Support page https://github.com/w3f/polkadot-wiki/pull/3366

**Comment by michalisFr** [comment]
@DrW3RK I've updated the list. All checked articles are ready to be migrated and I've added links to the specific support articles. The `Restore` section is ready for migration in its entirety. 

I didn't change the language about "removing" articles, but I agree with your point, so let's have these mean what you proposed. And I agree with this too:
> The Wiki articles can be updated to answer "Why?" more than "How to?"

@keeganquigley Please divide the remaining articles between you, me and @alineherzman. I've bolded keywords like **update** or **create** to specify what each article needs. New articles or articles that need a serious update should be done in accordance with the style guide, so that we don't need to go over them again.

I'd recommend that we tackle them section by section so that we finish with the migration of one section before moving to the next. So, we could start with `Balance transfers`, do that, then move to Ledger and so on.

**Comment by keeganquigley** [comment]
Thanks @michalisFr I have tried to divide as evenly as possible. There are 17 creates and 5 updates so far, so I have split up tasks as follows:

@michalisFr 
[Using the Polkadot Ledger Application](https://wiki.polkadot.network/docs/learn-ledger)
[Statemint](https://wiki.polkadot.network/docs/learn-statemint)
[Teleporting](https://wiki.polkadot.network/docs/learn-teleport)
[Multisig creation and usage](https://wiki.polkadot.network/docs/learn-accounts#example-with-polkadotjs)

@alineherzman 
[Account generation](https://wiki.polkadot.network/docs/learn-account-generation)
[Balance transfers](https://wiki.polkadot.network/docs/learn-balance-transfers)

@keeganquigley 
[Staking FAQ](https://wiki.polkadot.network/docs/learn-staking-faq)
[Nomination Pools](https://wiki.polkadot.network/docs/learn-nomination-pools)
[Identity](https://wiki.polkadot.network/docs/learn-identity)
[Treasury](https://wiki.polkadot.network/docs/learn-treasury)

This way we each have a total of (7) subtasks. I skipped the [Polkadot claims](https://wiki.polkadot.network/docs/claims) for now. I'm aiming to have the style guide finished by the end of this week. Let me know if this works and if you have any comments/questions!

**Comment by DrW3RK** [comment]
For Identity instructions, check if this feature request can be addressed. Thanks https://github.com/w3f/polkadot-wiki/issues/3353 and for Statemint, this one https://github.com/w3f/polkadot-wiki/issues/3282

**Comment by michalisFr** [comment]
@keeganquigley @DrW3RK @alineherzman
My parts are done.

For [this article](https://support.polkadot.network/support/solutions/articles/65000170304-how-to-send-transfer-funds-out-of-your-dot-account-on-the-polkadot-js-ui) on how to send funds, once we have created separate articles for each account type, like [this one for Ledger](https://support.polkadot.network/support/solutions/articles/65000181872-how-to-send-dot-from-your-ledger-account-on-polkadot-js-ui), as described in the Balance Transfers section, we need to rewrite it with clear numbered steps for the part that is common for all account types and then link to each separate article from then on. And in each separate article we'll have a "Initiate the transfer as described in this article" step, like step 2 in the Ledger article.

**Comment by keeganquigley** [comment]
@michalisFr @alineherzman my sections are complete! 

Note: I didn't end up creating a separate article for Clearing an Identity, as it is so short; I combined it with the Set Identity article.

**Comment by DrW3RK** [comment]
@keeganquigley As you were working on Identity section, can you find a home for this caution as well https://github.com/w3f/polkadot-wiki/issues/3516

**Comment by michalisFr** [comment]
@keeganquigley Can you please post links to the articles in your sections so I can update the OP?

**Comment by keeganquigley** [comment]
Here you go! @michalisFr 

[Staking FAQs](https://support.polkadot.network/support/solutions/articles/65000181959)
[Nomination Pools](https://support.polkadot.network/support/solutions/articles/65000181401)
[How to Set/Clear an Identity](https://support.polkadot.network/support/solutions/articles/65000181981)
[How to Request/Cancel Identity Judgement](https://support.polkadot.network/support/solutions/articles/65000181990)
[How to set Identities for Sub Accounts](https://support.polkadot.network/support/solutions/articles/65000181991)
[How to Submit a Tip from the Treasury](https://support.polkadot.network/support/solutions/articles/65000181971)

**Comment by michalisFr** [comment]
@DrW3RK All articles are ready except the claims one. You can remove content and add the links to the wiki at your convenience.

**Comment by DrW3RK** [comment]
Thank you! We will get started with the content removal beginning next week.

**Comment by michalisFr** [comment]
@keeganquigley @alineherzman Do any of you want to grab the claims article? It's the only one left in our list

**Comment by keeganquigley** [comment]
> @keeganquigley @alineherzman Do any of you want to grab the claims article? It's the only one left in our list

Sure no prob, I can grab this.

**Comment by keeganquigley** [comment]
[Claims article](https://support.polkadot.network/a/solutions/articles/65000138217) has been published. @DrW3RK I left out the Parity Signer section, this can stay on the wiki, although the UIs are outdated.

**Comment by DrW3RK** [comment]
@keeganquigley Yeah, the PR to update Parity Signer doc is blocked 

The last update on Parity Signer was that it is still being reviewed -

Gav (Jun 28th)  "i had time to reevaluate signer (5.1.0). there's still some important stuff which needs to be addressed.
should i write up here or would a call be more useful?"

Should probably follow up

https://github.com/w3f/polkadot-wiki/pull/3059

**Comment by alfarok** [comment]
I believe the final bullet point in this issues description is now complete 

- [x] `Remove/update corresponding wiki articles`

There are still a couple open PRs in review.  Please let me know if there are any outstanding items that still require action.

I am going to start on https://github.com/w3f/polkadot-wiki/issues/3597 next.
