### ISSUE TITLE
Update set identity section with latest instructions to include transaction fees pop-up

### ISSUE THREAD

**Issue by muddlebee** [w3f/polkadot-wiki#3353]
**Is your feature request related to a problem? Please describe.**
https://wiki.polkadot.network/docs/learn-identity#setting-an-identity
Certain steps like, it asks for a transaction fee pop-up when you set up identity is missing from the linked page above..

**Describe the solution you'd like**
Add the below steps for transaction fee pop-up in the identity section

![Screenshot 2022-05-19 at 3 44 35 AM](https://user-images.githubusercontent.com/8139783/169830117-4ee55725-39be-4b77-b67c-363762326128.png)

**Comment by keeganquigley** [comment]
I have added this screenshot to the migrated support article.

**Comment by DrW3RK** [comment]
@keeganquigley Is that article live on the support website? If so, please share it here and we can close this issue

**Comment by keeganquigley** [comment]
@DrW3RK It is now published [here](https://support.polkadot.network/support/solutions/articles/65000181981-how-to-set-and-clear-an-identity). Thanks! You can close.
