### ISSUE TITLE
A more hands on guide on stash vs controller accounts

### ISSUE THREAD

**Issue by Swader** [w3f/polkadot-wiki#336]
Right now the docs mention controllers and stashes in a lot of the places and make a note that it's more secure to use them, and the UI is also referencing this, but we don't have a guide on how to actually set a controller for a stash account anywhere. We should have one that uses both the UI and the CLI.

**Comment by lsaether** [comment]
Yeah we do, it was just merged in for the [nominator page](https://wiki.polkadot.network/docs/en/maintain-guides-how-to-nominate-kusama#step-2-bond-your-ksm). We need to update the UI instructions and the image above that though.

**Comment by Swader** [comment]
Indeed, I just reviewed that 🤦‍♂️ I'll update those parts.
