### ISSUE TITLE
Update Cross-Consensus Messaging Content

### ISSUE THREAD

**Issue by salmad3** [w3f/polkadot-wiki#3370]
- XCM Page doesn't really explain XCM under the hood; material is meant to be advanced
- Breakdown the tech stack
- More specifics: cross-consensus protocols as transport protocols, multilocation, etc.
- Should provide real examples

**Comment by emresurmeli** [comment]
Things to add:
- [ ] XCM high level blurb
- [ ] XCM analogies and philosophy
- [ ] XCMP
- [ ] VMP
- [ ] DMP
- [ ] UMP
- [ ] XCVM
- [ ] Encoding rules
