### ISSUE TITLE
substrate.dev scrub

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#340]
We will soon (~ one week) have to update our substrate.dev links.

List of files to update:

```bash
(1058) ~/web3/polkadot-wiki/docs $ find . -name "*.md" | xargs grep -l "substrate\.dev" 
./maintain-sync.md
./build-index.md
./maintain-networks.md
./build-build-with-polkadot.md
./kusama-claims.md
./learn-accounts.md
./build-hackathon.md
./learn-comparisons-cosmos.md
./learn-treasury.md
./mirror-build-build-with-polkadot.md
./learn-faq.md
./kusama-faucet.md
./learn-transaction-fees.md
./build-smart-contracts.md
./build-exchange-integration.md
./learn-relevant-links.md
./build-tools-index.md
```

**Comment by Swader** [comment]
Should stay open due to substrate.io

**Comment by joepetrowski** [comment]
This is going to be a highly manual task as I completely reorganized devhub into a flatter directory structure. If someone wants to get started on this, you could make a branch and:

1. Find all the devhub links and their corresponding new location in [knowledge-base](https://github.com/substrate-developer-hub/knowledgebase)
1. Change the link to the github URL (minus the .md at the end)
1. Wait...
1. When substrate.io launches, just find all the `github.com/substrate-developer-hub/knowledgebase/` instances and replace them with `substrate.io/kb/`
1. Merge

Step 4 will be much faster than 1 and 2 so it will just be flicking the switch.

**Comment by joepetrowski** [comment]
Partially addressed by https://github.com/w3f/polkadot-wiki/pull/423 but there are still the rustdocs and a few tutorials that haven't made their way over.

**Comment by Swader** [comment]
@joepetrowski are you working on this?

**Comment by joepetrowski** [comment]
Funny story now that we've moved back to .dev. Would be good for @danforbes or @wheresaddie to pick up.

**Comment by Swader** [comment]
I'll wait a day to see if anyone picks it up, will grab it otherwise, thanks

**Comment by wheresaddie** [comment]
@Swader if you want to pick this up- @danforbes and I will happily review when you're done w the PR 
thanks!
