### ISSUE TITLE
nomination-pools: How to migrate from normal staking <-> Pools 

### ISSUE THREAD

**Issue by kianenigma** [w3f/polkadot-wiki#3434]
A simple guide about how to do this, so we can propagate it around. We can also reuse it in polkadot.network. 

The reason being, Polkadot has now around 30k nominators, and ideally once the pools become active there, a bug chunk of that 7500 who are not electing need to be notified and given guidance about how they should go about migrating to pools.

**Comment by DrW3RK** [comment]
Sounds good! If I understand this correctly, you are asking for a simple how to guide that summarizes the two articles below

- [Why have I stopped nominating? Staking limits explained](https://support.polkadot.network/support/solutions/articles/65000180708-why-have-i-stopped-nominating-staking-limits-explained)
- [How to Join Nomination Pools](https://support.polkadot.network/support/solutions/articles/65000181401-how-to-join-nomination-pools)

Also, we decided to move all the "How to?" guides from the Polkadot Wiki to the Polkadot support page https://github.com/w3f/polkadot-wiki/issues/3346

Is it okay if we place this article on the support page instead of the Wiki? cc: @michalisFr

**Comment by kianenigma** [comment]
This is purely a how-to, just saying that if you are a nominator now, and you want to switch to pools, this is the steps you need to take. I don't think it is important to get into the details of `Staking limits explained again`, a link would be enough.

**Comment by michalisFr** [comment]
Actually after re-reading [Why have I stopped nominating? Staking limits explained](https://support.polkadot.network/support/solutions/articles/65000180708-why-have-i-stopped-nominating-staking-limits-explained) I plan to unpublish it, as it's outdated and not really relevant any more (to the average user).

I created [this article](https://support.polkadot.network/support/solutions/articles/65000181716-i-have-less-than-the-minimum-dot-needed-for-staking) for people that have less than the min needed to stake. Is this what you had in mind @kianenigma?

Once you've checked it I'll unpublish it until pools are in Polkadot.

cc @DrW3RK

**Comment by DrW3RK** [comment]
@michalisFr For a nominator who is already staking (and probably not receiving rewards), there needs be instructions on how to unbond their stake, (wait for 28 days), claim the unbonded tokens and then join the pool with unbonded funds

**Comment by DrW3RK** [comment]
Probably link to this article https://support.polkadot.network/support/solutions/articles/65000181716-i-have-less-than-the-minimum-dot-needed-for-staking in the note you provided early in this article about transferable balance https://support.polkadot.network/support/solutions/articles/65000181401-how-to-join-nomination-pools

**Comment by kianenigma** [comment]
On a related note, we should start a sweep and remove everything along the lines of 

> The way the [Nominated Proof of Stake (NPoS) consensus mechanism](https://wiki.polkadot.network/docs/learn-consensus#nominated-proof-of-stake) works is that it uses [Phragmén algorithm](https://wiki.polkadot.network/docs/learn-phragmen) to map the nominators to their selected validators and produce the active set of validators based on some criteria.

This is factually incorrect. There is nothing in the polkadot protocol that says phragmen. The main bottleneck in the new system is that the chain allows for any algorithm to come up with a solution, submitted to the chain, and verifies it. This is the main bottleneck and the reason that NPoS won't scale. 

More accurate would have been to state: The NPoS system allows an algorithm to efficiently distribute the nominator stakes among validators, such that the economic security of the chain is optimized, and properties such as PJR are satisfied. An example of this algorithm is the Phragmen algorithm.

**Comment by michalisFr** [comment]
> @michalisFr For a nominator who is already staking (and probably not receiving rewards), there needs be instructions on how to unbond their stake, (wait for 28 days), claim the unbonded tokens and then join the pool with unbonded funds

@DrW3RK That's what the article I created talks about, but not very useful atm since pools are not in Polkadot.

> Probably link to this article https://support.polkadot.network/support/solutions/articles/65000181716-i-have-less-than-the-minimum-dot-needed-for-staking in the note you provided early in this article about transferable balance https://support.polkadot.network/support/solutions/articles/65000181401-how-to-join-nomination-pools

For the above reason, I'm hesitant to link to that article.
