### ISSUE TITLE
Add links to validator stat websites

### ISSUE THREAD

**Issue by keorn** [w3f/polkadot-wiki#346]
@Noc2 should know some from grants, like https://labs.hashquark.io/#/polka/strategy/nominator

**Comment by Noc2** [comment]
Others grant receivers are: 
https://polkastats.io/
https://polkanalytics.com/ (the future name will be yieldscan) 

But both are currently still under a lot of development. 
Depending on what you count as validator stat website, you could also add https://kusama.subscan.io/validator. Additionally, wallets will integrate similar interfaces.
