### ISSUE TITLE
Refactro: Don't mention Phragmen as if it is a core part of the Polkadot NPoS protocol.

### ISSUE THREAD

**Issue by kianenigma** [w3f/polkadot-wiki#3461]
On a related note, we should start a sweep and remove everything along the lines of 

> The way the [Nominated Proof of Stake (NPoS) consensus mechanism](https://wiki.polkadot.network/docs/learn-consensus#nominated-proof-of-stake) works is that it uses [Phragmén algorithm](https://wiki.polkadot.network/docs/learn-phragmen) to map the nominators to their selected validators and produce the active set of validators based on some criteria.

This is factually incorrect. There is nothing in the polkadot protocol that says phragmen. The main bottleneck in the new system is that the chain allows for any algorithm to come up with a solution, submitted to the chain, and verifies it. This is the main bottleneck and the reason that NPoS won't scale. 

More accurate would have been to state: The NPoS system allows an algorithm to efficiently distribute the nominator stakes among validators, such that the economic security of the chain is optimized, and properties such as PJR are satisfied. An example of this algorithm is the Phragmen algorithm.
_Originally posted by @kianenigma in https://github.com/w3f/polkadot-wiki/issues/3434#issuecomment-1172286864_

**Comment by DrW3RK** [comment]
The Wiki itself does not imply that Phragmen algorithm is an integral part of Polkadot NPoS, but the wording can be improved to make this point clear. I will create a PR for that.

I made the update to the support article you cited in the issue https://support.polkadot.network/support/solutions/articles/65000180708-why-have-i-stopped-nominating-staking-limits-explained

> The [Nominated Proof of Stake (NPoS) system](https://wiki.polkadot.network/docs/learn-consensus#nominated-proof-of-stake) allows an algorithm to efficiently distribute the nominator stakes across the validator set, such that the economic security of the chain is optimized, and properties such as Proportionally Justified Representation (PJR) are satisfied. An example of such algorithm is the [Phragmén algorithm](https://wiki.polkadot.network/docs/learn-phragmen). These algorithms are computationally intensive and are implemented off-chain, but their solution must be evaluated on-chain within a single block, meaning in 6 seconds.

cc: @michalisFr

**Comment by michalisFr** [comment]
Thanks @kianenigma. I wasn't aware that we use other algorithms besides Phragmen. We'll make sure to remove any mentions of Phragmen in our articles and our responses.

> There is nothing in the polkadot protocol that says phragmen.

Well, there is the `phragmenElection` pallet 😁 But that's not related to staking.

**Comment by kianenigma** [comment]
> Well, there is the phragmenElection pallet 😁 But that's not related to staking.

Indeed, that's only for the council.

**Comment by DrW3RK** [comment]
The support article already removed the direct reference of Phragmen https://support.polkadot.network/support/solutions/articles/65000180708-why-have-i-stopped-nominating-staking-limits-explained

I've removed its direct references on Polkadot Wiki.

https://github.com/w3f/polkadot-wiki/pull/3466
