### ISSUE TITLE
Remove legacy code related to the yarn 'inject' command

### ISSUE THREAD

**Issue by alfarok** [w3f/polkadot-wiki#3473]
`yarn polkadot:inject` or `yarn kusama:inject` at some point in time was used to visualize (diff) the changes generated throughout all the html documents after running a `build`.  This is at least how it is described in the README.  It doesn't seem like `inject` works anymore as the constant values are replaced during the build process.  This means the values will already be up-to-date so no changes are visualized.

See the following comment/PR for additional details: https://github.com/w3f/polkadot-wiki/pull/3464#issuecomment-1175413459

**Comment by DrW3RK** [comment]
Makes sense! Update the README with accurate info after you merge the PR related to this issue. Thanks!

**Comment by alfarok** [comment]
addressed in #3474
