### ISSUE TITLE
Create wiki page for Governance v2

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#3476]

**Comment by DrW3RK** [comment]
Resources: https://github.com/paritytech/polkadot/pull/5205
https://www.youtube.com/watch?v=EF93ZM_P_Oc

**Comment by emresurmeli** [comment]
This document could also be useful:
https://docs.google.com/document/d/11ZVe89SgdIGDkDUZ6ld2e7_xp-A812UNIsqb7psKTJ8/edit

**Comment by alfarok** [comment]
Adding the medium article @emresurmeli pointed out at the latest Polkadot update:
https://medium.com/polkadot-network/gov2-polkadots-next-generation-of-decentralised-governance-4d9ef657d11b

**Comment by DrW3RK** [comment]
https://wiki.polkadot.network/docs/learn-gov2
