### ISSUE TITLE
Move Polkadot Open Stack doc to the Wiki from Grants repo

### ISSUE THREAD

**Issue by DrW3RK** [w3f/polkadot-wiki#3491]
Add this doc (or split it into multiple docs) to the Wiki

https://github.com/w3f/Grants-Program/blob/master/docs/polkadot_stack.md

The badges are generated through https://github.com/w3f/status-badges

**Comment by alfarok** [comment]
There is some type of formatting issue with this page that docusaurus doesn't like.  When I copy the raw markdown directly into a new page on the wiki I get this formatting error:

![image](https://user-images.githubusercontent.com/13341935/181782184-a8440840-a08d-4f65-a1fc-5144a3d42494.png)

Looking through it now to see if there is a missing closing tag somewhere but it is a little challenging to quickly see in such a large table.

**Comment by alfarok** [comment]
Got it, there are 4 instances of `<>` used in link titles.  The markdown renders fine as-is in the standard GitHub flavor but not in JSX.  The `<>` gets read as the opening/closing of an element tag causing the rest of the doc to shift tags.  I will replace these with a `-`.

**Comment by alfarok** [comment]
addressed in #3584
