### ISSUE TITLE
Remove wiki revamp message from README

### ISSUE THREAD

**Issue by alfarok** [w3f/polkadot-wiki#3496]
Is the note below from the [README](https://github.com/w3f/polkadot-wiki/commit/07f32033cfc56332342c96e2ad31198630e09e13#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R17-R22) still relevant?  It was added Dec 29, 2021.

 :high_brightness: **Please Note**: The Wiki will undergo a major revamp over the next several weeks in an attempt 
 to improve its configuration, functionality, relevancy, adequacy, and overall design. 
 The new Wiki will exist in a new repository, still under `w3f`.

Or can it be removed?

**Comment by DrW3RK** [comment]
Updated.
