### ISSUE TITLE
[Bug]: broken links in the learn-accounts section

### ISSUE THREAD

**Issue by muddlebee** [w3f/polkadot-wiki#3537]
**Is your feature request related to a problem? Please describe.**
Broken links present in the section https://wiki.polkadot.network/docs/learn-accounts#decoding-call-data at the end of this section.

![image](https://user-images.githubusercontent.com/8139783/179318862-76a4074b-ced0-48ae-adb3-2a3037a47ef7.png)
**Describe the solution you'd like**

Link : https://github.com/w3f/utility-scripts/

**Comment by DrW3RK** [comment]
Looks like the visibility of this repo is changed to private. Will get back on this soon

**Comment by alfarok** [comment]
@DrW3RK this is a good example of why the CICD test for broken links shouldn't prevent merging as we were discussing in #3511.  This link likely worked recently when we audited and I've seen this before with other intermittent failures with 3rd party links that come back online.  Some type of daily or weekly check that produces a report of broken links may be the better option and won't block unrelated PRs.

**Comment by DrW3RK** [comment]
Links work now
