### ISSUE TITLE
Update Internationalization section in Readme

### ISSUE THREAD

**Issue by DrW3RK** [w3f/polkadot-wiki#3545]
The readme file of the repo needs to be updated to reflect the current status on Translations

**Comment by DrW3RK** [comment]
Closed this issue and keeping this one https://github.com/w3f/polkadot-wiki/issues/2398

**Comment by emresurmeli** [comment]
Will check with Parity what the status is on in-house translations. If nothing has changed on their end we can just keep this as is.

**Comment by DrW3RK** [comment]
@emresurmeli Sure! In the context of the Wiki, none of the translations are making it to the Wiki anymore (The language dropdown is disabled). Also, with the Wiki revamp and reorg, the work will be duplicated over time. Please consider these for providing accurate information for the contributors
