### ISSUE TITLE
Broken Discord link used in translated md docs (community pages) 

### ISSUE THREAD

**Issue by carinaluise** [w3f/polkadot-wiki#3548]
An old/broken Kusama discord link is being used in **translated markdown docs**, both community and kusama-community pages. 

Link currently used: https://discord.gg/JSJcRwz8fp 
New Kusama discord link: https://discord.com/invite/9AWjTf8wSk 

@DrW3RK

**Comment by DrW3RK** [comment]
Will fix them! FYI, Translated markdown docs are no longer rendered on the Wiki.

**Comment by carinaluise** [comment]
Thanks @DrW3RK! Ah good to know 👍
