### ISSUE TITLE
Remove/Replace How to Guides on the Wiki to point to Support pages

### ISSUE THREAD

**Issue by DrW3RK** [w3f/polkadot-wiki#3570]
https://github.com/w3f/polkadot-wiki/issues/3346

This will need multiple PRs. The most logical thing to do is to limit updates to 4 Wiki docs in each PR for a seamless review pipeline

**Comment by alfarok** [comment]
Is this related to #3597?

**Comment by DrW3RK** [comment]
This one https://github.com/w3f/polkadot-wiki/issues/3346 I have it referenced in the issue description right at the beginning, but it is not very clearly referenced, sorry :)

**Comment by michalisFr** [comment]
@DrW3RK I'm assuming you'll open a new issue for #3597 when it's completed?

cc @alfarok

**Comment by DrW3RK** [comment]
@michalisFr Yeah!
