### ISSUE TITLE
Grants info in the wiki is outdated

### ISSUE THREAD

**Issue by alxs** [w3f/polkadot-wiki#3592]
The link [here](https://wiki.polkadot.network/docs/build-index#grants) doesn't point to what it describes, and the information in the [grants page](https://wiki.polkadot.network/docs/grants) is outdated (we don't have limits for follow-up applications, links are outdated etc). This is duplicate info from our README so it's always gonna be hard to keep it in sync.

I would delete the page and send people to the repo/new grants website when we have it rom the first link.

**Comment by DrW3RK** [comment]
I created a PR to fix the issue. IMO, the grants page should still be there as it provides information about the funding sources in the ecosystem.
