### ISSUE TITLE
Migration of how-to guides for remaining Learn sections

### ISSUE THREAD

**Issue by keeganquigley** [w3f/polkadot-wiki#3597]
- [x] Find & identify necessary migrations for the remaining 4 Learn sections
- [x] Settle on list of articles to migrate
- [x] Prepare (create/update) articles below
- [x] Remove/update corresponding wiki articles

There are 4 remaining Learn sections:
[Advanced](https://wiki.polkadot.network/docs/learn-availability)
[Cryptography](https://wiki.polkadot.network/docs/learn-cryptography)
[Paraobjects](https://wiki.polkadot.network/docs/learn-parachains)
[Polkadot Comparisons](https://wiki.polkadot.network/docs/learn-kusama-vs-polkadot)

We can split them up as follows:

@keeganquigley
[Advanced](https://wiki.polkadot.network/docs/learn-availability)
[Cryptography](https://wiki.polkadot.network/docs/learn-cryptography)

@michalisFr 
[Paraobjects](https://wiki.polkadot.network/docs/learn-parachains)

@alineherzman
[Polkadot Comparisons](https://wiki.polkadot.network/docs/learn-kusama-vs-polkadot)

## Articles to migrate

- [x] [Proxy Accounts](https://wiki.polkadot.network/docs/learn-proxies): Migrate existing article. **[New Article](https://support.polkadot.network/support/solutions/articles/65000182179-how-to-create-a-proxy-account)** ✔️
- [x] [Anonymous Proxies](https://wiki.polkadot.network/docs/learn-proxies#creating-anonymous-proxies-on-polkadot-js-ui): **Create** new article for setting up anon proxy. Include a warning about loss of funds, and use only UI screenshots. **[New Article](https://support.polkadot.network/support/solutions/articles/65000182196-how-to-create-an-anonymous-proxy)** ✔️

- [x] [Parachain Slots Auction](https://wiki.polkadot.network/docs/learn-auction): **Create** an article to briefly sum up[ how auctions work](https://wiki.polkadot.network/docs/learn-auction) and include a video tutorial. **[New Article](https://support.polkadot.network/support/solutions/articles/65000182287-how-does-a-parachain-slots-auction-work-)** ✔️

- [x] [Comparing Polkadot and Kusama](https://wiki.polkadot.network/docs/learn-kusama-vs-polkadot): **Create** an article about Polkadot vs Kusama that summarizes the one in the wiki, and links to the more comprehensive one which will stay on the wiki. **[New Article](https://support.polkadot.network/support/solutions/articles/65000182146-kusama-and-polkadot-what-s-the-difference-)** ✔️

**Comment by michalisFr** [comment]
@keeganquigley I didn't find anything that warrants a migration in Paraobjects.

[Parachain Crowdloans](https://wiki.polkadot.network/docs/learn-crowdloans) already links to the support article on how to contribute. [Starting a Crowdloan Campaign](https://wiki.polkadot.network/docs/learn-crowdloans#starting-a-crowdloan-campaign) is meant for parachain teams, so not suited for the support page. [Withdraw Crowdloaned Tokens](https://wiki.polkadot.network/docs/learn-parachains#withdraw-crowdloaned-tokens) is also technical, and done by the parachain teams.

Perhaps we could create an article that's a simplified summary of [how the auctions work](https://wiki.polkadot.network/docs/learn-auction) that includes that nice video. It won't substitute any of the content on that wiki page though.

[Teleporting Assets](https://wiki.polkadot.network/docs/learn-teleport) was already covered because it's a duplicated entry from Basics.

**Comment by keeganquigley** [comment]
[Advanced](https://wiki.polkadot.network/docs/learn-availability) - the only guide here that could possibly be migrated is how to create proxy accounts. @michalisFr Do you think it would be appropriate to create a basic article on setting proxies and link to the wiki? Or should we consider proxies as advanced and out of scope?

[Cryptography](https://wiki.polkadot.network/docs/learn-cryptography) - didn't find anything to migrate in here. We have existing article on how to properly store seeds which briefly explains the cryptography from a user perspective.

**Comment by alineherzman** [comment]
From [Polkadot Comparisons](https://wiki.polkadot.network/docs/learn-kusama-vs-polkadot), maybe we can migrate the ["Polkadot vs Kusama"](https://wiki.polkadot.network/docs/learn-kusama-vs-polkadot) part. It's not too technical.

I don't think comparing Polkadot to other projects belongs to the support page.

**Comment by michalisFr** [comment]
@keeganquigley Yes, let's create an article for proxies and migrate the method that uses the UI. 

For anonymous proxies let's create a separate article with a disclaimer that this is an advanced topic and a big warning that setting up an anonymous proxy incorrectly can result in loss of funds. Although it makes use of the extrinsics page (which we should avoid in the support page), it might become a more trending topic as more community members get interested in bounties. So, it's good to have a clear guide on how to set up an anon proxy on the support page.

@alineherzman Yes, let's create an article about Polkadot vs Kusama, that's a summary of the one in the wiki, but leave that one in the wiki too.

**Comment by keeganquigley** [comment]
Thanks @alineherzman and @michalisFr tasks have been updated.

**Comment by keeganquigley** [comment]
@alfarok @michalisFr articles have been updated and the last task is ready to be completed by the tech ed team. Thanks!

**Comment by alfarok** [comment]
This should be complete with the merging of #3715 and #3723 which are currently in review.
