### ISSUE TITLE
Complete IPFS deployment for the Polkadot and Kusama docs

### ISSUE THREAD

**Issue by alfarok** [w3f/polkadot-wiki#3651]
### Description
This issue builds off of https://github.com/w3f/polkadot-wiki/issues/2338.

I am just getting up to speed on IPFS, IPNS, and DNS linking, but think I have enough resources to attempt completing the deployment.

The initial scope for this task should cover the following:
- Get access to CloudFlare credentials
- Check if the team has access to a private gateway in CloudFlare or use a public gateway such as `cloudflare-ipfs.com` or `gateway.ipfs.io` etc
- Ensure the name servers are set to CloudFlare for the appropriate sub-domains (`ipfs.wiki.polkadot.network` and `ipfs.guide.kusama.network`)
- Sites must have SSL certs issued by CloudFlare to enable HTTPS ( request them if not already available as HTTP will not suffice)
- Update the DNS records to point to the appropriate Gateway (`CNAME` or `A`/`AAAA`)
- Add _dnslink. `TXT` record pointing to either the IPFS or IPNS build folder (better for automated updating, otherwise hash must be updated manually here on each deployment)
- Add CICD action for running build and pushing updated build to IPFS (can likely leverage [this existing script](https://github.com/w3f/polkadot-wiki/blob/master/scripts/ipfs-cluster-pin.js))

### Resources
- https://developers.cloudflare.com/web3/ipfs-gateway/concepts/dnslink/
- https://docs.ipfs.tech/concepts/dnslink/
- https://docs.ipfs.tech/concepts/ipns/
- https://dnslink.io/

**Comment by DrW3RK** [comment]
Not a priority at this time
