### ISSUE TITLE
Polkadot Accounts does not mention the password derivation

### ISSUE THREAD

**Issue by pepyakin** [w3f/polkadot-wiki#3672]
The article about [Polkadot Accounts](https://wiki.polkadot.network/docs/learn-accounts#derivation-paths) mentions only soft and hard derivations. AFAIK, there is another type of derivation which is referred to as "password". 

Was it overlooked, or is this deliberate? 

If it was overlooked, then it should be mentioned. If it was deliberate, there should probably be a notice about it anyway.

**Comment by DrW3RK** [comment]
@pepyakin Would you like to review this PR https://github.com/w3f/polkadot-wiki/pull/3691 and ensure that the content meets the expectations? Thanks
