### ISSUE TITLE
Review Polkadot overview paper; make sure wiki is in line

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#368]
https://github.com/w3f/research/tree/master/docs/polkadot/Polkadot-OverviewPaper

**Comment by Swader** [comment]
I'm noticing typos and non-native phrasing. Is this going to be edited for language before publication, should we ignore these? Should we focus on content only instead?

**Comment by laboon** [comment]
Yes, ignore those, this is not the final version.  I've already reviewed for content once, and I (and others) will do a second review for content, phrasing, typos, etc.  You are also welcome to review once it's in a reviewable state if you like.

**Comment by Swader** [comment]
Is this still relevant? If so, is there a more readable version of the paper than tex?

**Comment by krichard410** [comment]
Is this the final version? https://arxiv.org/pdf/2005.13456.pdf, it was listed as the first version published on May 29, 2020. Found on this site: https://research.web3.foundation/en/latest/Publications.html
