### ISSUE TITLE
Comparison of blockchain projects based on expectation and delivery

### ISSUE THREAD

**Issue by lsaether** [w3f/polkadot-wiki#37]
This issue is a replication of [this one](https://github.com/w3f/polkadot-wiki-old/issues/269) from the old wiki. The idea is that we compare projects that have promised certain features or capabilities to what they have delivered in practice, or at least what progress they have made toward the delivery. 

This is to dispel some of the myths that projects create about the functionality of their chain.

All we need to close this issue is a table that compares features of each project. All detailed information should be in the individual comparison articles for each project, if they exist.

See the table on Wikipedia's [Comparison of Linux](https://en.wikipedia.org/wiki/Comparison_of_Linux_distributions) for an example of what this table should look like.

**Comment by Swader** [comment]
Recommend closing this, seems irrelevant and confrontational and too much work to stay on top of actual work done by competitors.
