### ISSUE TITLE
Reorg of proxies page with focus on anon proxies

### ISSUE THREAD

**Issue by filippoweb3** [w3f/polkadot-wiki#3710]
## The points below must be fixed

- [x] Rearrange subtitles: anon and time-delayed proxies are not proxy types
- [x] Remove the part about how-to remove proxies, as already present in this [support article](https://support.polkadot.network/support/solutions/articles/65000182196)
- [x] [This](https://www.youtube.com/watch?v=iWq53zXo7dw&list=PLOyWqupZ-WGuAuS00rK-pebTMAOxW41W8&index=29) video seems to be outdated, I propose to add a new video tutorial
- [x] Errors in anon proxies definition
- [x] Reorganise the page to make it more clear and easy to follow

**Comment by nuke-web3** [comment]
FYI the name of anon proxies may change, most recently `Pure Proxy` was suggested: https://github.com/paritytech/substrate/issues/7735

**Comment by DrW3RK** [comment]
Thanks Dan! @filippoweb3 Here is the PR on Substrate repo that tracks the renaming https://github.com/paritytech/substrate/pull/12283

**Comment by filippoweb3** [comment]
@NukeManDan @DrW3RK thank you, I added all relevant links about renaming anon proxies in the dedicated PR I am working on
