### ISSUE TITLE
bagsList pallet has been renamed voterList

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#3751]
https://wiki.polkadot.network/docs/learn-nominator#bags-list

This refers to the bagsList pallet (e.g. the extrinsics) but it has been renamed to voterList.

You can see a reference to it here: https://github.com/paritytech/polkadot/blob/b91e8efdde0a01981367cc18462d3613b1b8d3b7/runtime/kusama/src/lib.rs#L1059 and check it out via the extrinsics tab on Polkadot-JS UI, there is no bagsList.

There may be other references to bagsList that should be renamed to voterList elsewhere on the wiki.

**Comment by DrW3RK** [comment]
@laboon This was discussed earlier. Will change it to VoterList wherever it us appropriate.

<img width="813" alt="image" src="https://user-images.githubusercontent.com/86818441/188564686-1765451e-efaf-4c81-bb23-319bcc5d6f39.png">

**Comment by laboon** [comment]
I see. From a user perspective, it's only available as voterList, so we should be sure to make that clear for users trying to rebag / view bags / etc. manually.

**Comment by filippoweb3** [comment]
@laboon @DrW3RK I can probably take care of this issue. Let me know. As far as I understand, the pallet name is `voterList` with the possibility to create the `putInFrontOf` and `rebag` extrinsic. Still, we want to keep `bagsList` in the wiki, but specify that the pallet name differs. Is this right?

**Comment by laboon** [comment]
Exactly. For user-facing instructions, e.g. what extrinsic to send, be sure to use "voterList" but the actual pallet name is "bagsList".

**Comment by DrW3RK** [comment]
Was not aware of this issue being linked to the Staking reorg PR. My original plan was to make the changes after the big reorg PR is merged. Reopening the issue and creating the PR with the required edits

**Comment by filippoweb3** [comment]
I see, this has been updated on the staking page, but not on the Nominator Page. My fault, thanks for spotting this @DrW3RK.
