### ISSUE TITLE
Update deposit values for Kusama

### ISSUE THREAD

**Issue by Imod7** [w3f/polkadot-wiki#3761]
## Issue
Under the section [Making Transactions with a Multi-signature Account](https://wiki.polkadot.network/docs/learn-accounts#making-transactions-with-a-multi-signature-account) of the wiki, there is a table with the values of `DepositBase`and `DepositFactor` for the Polkadot and Kusama networks.
 
I was just double checking the values against Polkadot-js apps (_Developer > Chain State > Constants_) and it looks like the values for **Kusama** are different from what it is mentioned in the wiki.

### Deposit values for Kusama from p-js apps 
<img width="699" alt="Screenshot 2022-09-07 at 10 46 36" src="https://user-images.githubusercontent.com/12569221/188847808-dfe2368d-8707-468a-8c02-7b59ce068634.png">

### Deposit values for Kusama from the wiki
<img width="792" alt="Screenshot 2022-09-07 at 10 43 33" src="https://user-images.githubusercontent.com/12569221/188848041-6b7d2a37-f982-4775-a672-f40e25ac2930.png">

**Comment by laboon** [comment]
Thanks for noticing. These were updated on Kusama last February on-chain but we missed updating this page.

@alfarok can you update this page to use on-chain data directly?

**Comment by alfarok** [comment]
Addressed in #3797
