### ISSUE TITLE
Updates of Support articles and migrations from the Build and Maintain sections of the wiki.

### ISSUE THREAD

**Issue by michalisFr** [w3f/polkadot-wiki#3762]
In this issue we'll track the migrations and updates to the Support page of articles in the Build and Maintain sections of the wiki. Most of these articles in the wiki won't need to be migrated or changed, but simply add relevant information to existing or new support articles.

- [X] Find all how-to guides in the Build and Maintain wiki sections that need to migrate/duplicate to the support page
- [X] Settle on the list of articles to migrate/duplicate below
- [x] Prepare (create/update) all articles below
- [x] Remove/update corresponding wiki articles

#### Build

- [x] [Wallets](https://wiki.polkadot.network/docs/build-wallets): **Update** the [relevant article](https://support.polkadot.network/support/solutions/articles/65000068702-where-to-store-dot-polkadot-wallet-options) with the list of treasury funded wallets. **No migration needed** (Keegan)
- [x] [Types of balance](https://wiki.polkadot.network/docs/build-protocol-info#free-vs-reserved-vs-locked-vs-vesting-balance): **Create** an article to explain balances and how locks work. **No migration needed** (Keegan) **[New article](https://support.polkadot.network/support/solutions/articles/65000182717-account-balances-and-locks)**
- [x] [Tool index](https://wiki.polkadot.network/docs/build-tools-index): **Update** the [block explorers article](https://support.polkadot.network/support/solutions/articles/65000178909-what-block-explorers-can-i-use-for-the-polkadot-and-kusama-ecosystems-). **No migration needed** (Keegan)

#### Maintain

- [x] [Parameters](https://wiki.polkadot.network/docs/maintain-polkadot-parameters): **Update** [Polkadot vs Kusama article](https://support.polkadot.network/support/solutions/articles/65000182146-polkadot-and-kusama-what-s-the-difference-) with applicable side-by-side parameters. **No migration needed** (Alina)
- [x] [Nominate](https://wiki.polkadot.network/docs/maintain-guides-how-to-nominate-polkadot): **Update** information in [relevant article](https://support.polkadot.network/support/solutions/articles/65000168057-how-do-i-stake-nominate-on-polkadot-) as needed. **Migration needed** except the CLI instructions. (Michalis)
- [x] [Unbonding and Rebonding](https://wiki.polkadot.network/docs/maintain-guides-how-to-unbond): **Update** as needed the existing [unbond](https://support.polkadot.network/support/solutions/articles/65000167902-how-can-i-unstake-my-tokens-again-), [rebond](https://support.polkadot.network/support/solutions/articles/65000170241-how-to-rebond-tokens-during-the-unbonding-period), and [bags](https://support.polkadot.network/support/solutions/articles/65000181018-i-have-more-than-the-minimum-bonded-but-i-m-not-getting-rewards) articles. **Migration needed** (Michalis)

**Comment by michalisFr** [comment]
#### Build

[Wallets](https://wiki.polkadot.network/docs/build-wallets): We should add/duplicate the list of treasury funded wallets to the [relevant article](https://support.polkadot.network/support/solutions/articles/65000068702-where-to-store-dot-polkadot-wallet-options). **No migration needed**

[Types of balance](https://wiki.polkadot.network/docs/build-protocol-info#free-vs-reserved-vs-locked-vs-vesting-balance): We could create an article that explains a bit the different balances and how locks work (I don't think there's a relevant article now that this info could be added to). **No migration needed**

[Tool index](https://wiki.polkadot.network/docs/build-tools-index): We should update the [block explorers article](https://support.polkadot.network/support/solutions/articles/65000178909-what-block-explorers-can-i-use-for-the-polkadot-and-kusama-ecosystems-) to add polkaholic and we could also add another section for other tools everyday users might find useful (like Polkawatch). **No migration needed**

#### Maintain

[Parameters](https://wiki.polkadot.network/docs/maintain-polkadot-parameters): We could create an article with most relevant parameters for everyday users and put them side-by-side with Kusama parameters. Or perhaps they could be added to the [Polkadot vs Kusama article](https://support.polkadot.network/support/solutions/articles/65000182146-polkadot-and-kusama-what-s-the-difference-)? **No migration needed**

[Nominate](https://wiki.polkadot.network/docs/maintain-guides-how-to-nominate-polkadot): This is a how-to guide that should be migrated up to the point of the CLI instructions. We need to check if there's any info not mentioned in the [relevant article](https://support.polkadot.network/support/solutions/articles/65000168057-how-do-i-stake-nominate-on-polkadot-) that should be added. 

[Unbonding and Rebonding](https://wiki.polkadot.network/docs/maintain-guides-how-to-unbond): This is a how-to guide that should be migrated. Articles exist: [Unbond](https://support.polkadot.network/support/solutions/articles/65000167902-how-can-i-unstake-my-tokens-again-), [Rebond](https://support.polkadot.network/support/solutions/articles/65000170241-how-to-rebond-tokens-during-the-unbonding-period), and [Bags](https://support.polkadot.network/support/solutions/articles/65000181018-i-have-more-than-the-minimum-bonded-but-i-m-not-getting-rewards). Plus the new articles with the staking dashboard: [Stake](https://support.polkadot.network/support/solutions/articles/65000182133-how-to-use-the-staking-dashboard-staking-your-dot), [Unbond](https://support.polkadot.network/support/solutions/articles/65000182201-how-to-use-the-staking-dashboard-unbonding-your-tokens), [Rebond](https://support.polkadot.network/support/solutions/articles/65000182221-how-to-use-the-staking-dashboard-rebonding). Plus a dozen more about nominating, changing nominations, bonding more, pools, etc.

[Participate in democracy](https://wiki.polkadot.network/docs/maintain-guides-democracy): From this article I think the sections: Endorsing, Voting, Unlocking, Delegating and Undelegating, should be migrated. The introductory info in each should remain on the wiki and migrate the how-to's. We have articles for [voting](https://support.polkadot.network/support/solutions/articles/65000180836-how-to-vote-in-governance-referenda) and [unlocking](https://support.polkadot.network/support/solutions/articles/65000181870-how-to-remove-expired-democracy-locks). Let's see if there's any other info from the wiki we should add to them.

[Voting for Councillors](https://wiki.polkadot.network/docs/maintain-guides-how-to-vote-councillor): This too should be migrated in a new article.

For these last two, I'm wondering if perhaps it's not worth it to migrate them now, but instead wait to do it once Gov 2.0 is live...

**Comment by keeganquigley** [comment]
Hey team, I started the first few. Should we split these up as follows?

UPDATE: I believe these are complete.

@keeganquigley

**Build**

- [x] [Wallets](https://wiki.polkadot.network/docs/build-wallets): add/duplicate list of treasury funded wallets.

- [x] [Types of balance](https://wiki.polkadot.network/docs/build-protocol-info#free-vs-reserved-vs-locked-vs-vesting-balance): create an article to explain balances and how locks work.

- [x] [Tool Index](https://wiki.polkadot.network/docs/build-tools-index): update block explorers article.

@alineherzman would you want to work on:

**Maintain**

- [x] [Parameters](https://wiki.polkadot.network/docs/maintain-polkadot-parameters): Updating [Polkadot vs Kusama article](https://support.polkadot.network/support/solutions/articles/65000182146-polkadot-and-kusama-what-s-the-difference-) with applicable side-by-side parameters?

@michalisFr could then work on:

**Maintain**

- [x] [Nominate](https://wiki.polkadot.network/docs/maintain-guides-how-to-nominate-polkadot): update information in [relevant article](https://support.polkadot.network/support/solutions/articles/65000168057-how-do-i-stake-nominate-on-polkadot-).

- [x] [Unbonding and Rebonding](https://wiki.polkadot.network/docs/maintain-guides-how-to-unbond): update any relevant info in existing [unbond](https://support.polkadot.network/support/solutions/articles/65000167902-how-can-i-unstake-my-tokens-again-), [rebond](https://support.polkadot.network/support/solutions/articles/65000170241-how-to-rebond-tokens-during-the-unbonding-period), and [bags](https://support.polkadot.network/support/solutions/articles/65000181018-i-have-more-than-the-minimum-bonded-but-i-m-not-getting-rewards) articles.

**Comment by michalisFr** [comment]
@keeganquigley @alineherzman OP updated with checklist

**Comment by alineherzman** [comment]
I've updated [Polkadot vs Kusama article](https://support.polkadot.network/support/solutions/articles/65000182146-polkadot-and-kusama-what-s-the-difference-) with parameters (haven't published yet)

**Comment by michalisFr** [comment]
> I've updated [Polkadot vs Kusama article](https://support.polkadot.network/support/solutions/articles/65000182146-polkadot-and-kusama-what-s-the-difference-) with parameters (haven't published yet)

@alineherzman This looks good to me

**Comment by michalisFr** [comment]
@keeganquigley Checked mine as well. Very minor changes made. Nothing really on the wiki that we don't already cover, so I removed the link to the wiki article in the "how to nominate" article.

**Comment by keeganquigley** [comment]
All set with my sections! Check these over if you'd like before checking the tasks as complete.
