### ISSUE TITLE
Polkadot max nominators variable not being interpolated

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#3774]
https://wiki.polkadot.network/docs/learn-nominator#staking-election-stages

This shows:

"Staking rewards are received by top {{ polkadot_max_nominators }} nominators, but when slashing occurs, all the active nominators backing the validator get slashed."

The variable should have been replaced with 22500.

**Comment by alfarok** [comment]
Nice catch @laboon!  I recently addressed a few of these in #3735 but seems like I missed `learn-nominator.md`.  There are 5 instances in the doc that need to be replaced with the RPC component.

@DrW3RK pointed out in the PR above that {{ polkadot_max_nominators }} was used for several different chain values based on the context.  The ambiguity seemed to be between these chain values for Polkadot:
- maxNominatorRewardedPerValidator - 256
- maxNominatorsCount - 50,000
- maxNominations - 16

Prior to using the RPC components, [inject-dict.json](https://github.com/w3f/polkadot-wiki/blob/752df56f9b602d93b1f19ad8a33d2970b49b9785/scripts/inject-dict.json#L67) file held a value of 256 for this key:
![image](https://user-images.githubusercontent.com/13341935/189195520-5896b438-8942-4e1e-8a47-e075988a81ab.png)
