### ISSUE TITLE
Deprecate all `curl` usage in wiki examples that connect to nodes

### ISSUE THREAD

**Issue by nuke-web3** [w3f/polkadot-wiki#3792]
see: https://github.com/substrate-developer-hub/substrate-docs/issues/1518

**Comment by alfarok** [comment]
Performing a quick search on the wiki/guide, I see `curl` references in the following docs:
- build-node-interaction.md
- build-node-management.md
- kusama-claims.md
- maintain-guides-how-to-use-polkadot-validator-setup.md
- maintain-guides-how-to-validate-polkadot,md
- maintain-sync.md
- maintain-wss.md

@NukeManDan would you recommend updating all these references or is this deprecation strictly related to substrate interactions?

**Comment by nuke-web3** [comment]
I think this is strictly related to anything that connects to a node, the idea here is that the HTTP endpoint will be deprecated from all substrate nodes, so eventually all `curl` calls will fail.

If `curl` is used to, say, install a software or something else unrelated to a node, then no change is needed.

**Comment by alfarok** [comment]
addressed in #3838
