### ISSUE TITLE
Update the Treasury Funded wallets section

### ISSUE THREAD

**Issue by DrW3RK** [w3f/polkadot-wiki#3798]
- Update the "Supports" column with relevant details for wach wallet
- Add treasury funding details for Talisman wallet https://polkadot.polkassembly.io/treasury/148

**Comment by filippoweb3** [comment]
@DrW3RK what do you mean with "update the supports column"? I can see that all have staking, which is true. Should I add other details such as ledger? Other things you have in mind?

**Comment by DrW3RK** [comment]
Yeah! Check the newly added row (Polkadot JS Plus) as a reference

I always wanted to change that, but never got a chance to. If we were just going to talk about support for staking, then the column name should have been "Staking Support" and the table values would be "Yes/No".

**Comment by filippoweb3** [comment]
Done, see linked PR
