### ISSUE TITLE
Parachain section

### ISSUE THREAD

**Issue by lsaether** [w3f/polkadot-wiki#38]
As we progress closer to the launch of the main Polkadot network, and more soon the availability of Kusama as a network for parachain developers to start experimenting with launching parachains on, the wiki should evolve a whole new section that contains parachain specific information.

Since parachain content currently lives across the three main sections of the wiki, in the Build, Learn, and Maintain sections, the Parachain section would be on the same level as these headers. 

```
Parachains
  |
  |-- Collators
  |-- Parachain Development Kits
  |-- Parachain Economics
  |-- Parachain Standards
```

The biggest question if we do this is how much it overlaps with what we currently have in the Build section, since the build section focuses on parachains. Smart contracts and tooling would still live in the build section; also tutorials and materials for workshops and hackathons.

**Comment by laboon** [comment]
We have the "Build" section which has all the necessary parachain information for making one.

Other information on parachains are in appropriate places - people running a collator have different info needs than people learning academically or building a chain.
