### ISSUE TITLE
Reorg Accounts Page

### ISSUE THREAD

**Issue by filippoweb3** [w3f/polkadot-wiki#3804]
**Problem**
- The page contains advanced information (such as hashing, and account derivation) that increases its size and could scare the average reader.
- Some chain data are not fetched

**Potential solution**
I propose to migrate the advanced information to an advanced page, as we did for the staking page. I also propose to reorganise the content a bit.

**Comment by filippoweb3** [comment]
@laboon @DrW3RK, let me know what your thoughts are about this issue. I read through the page and believe we can better explain the concepts concisely and leave the advanced content on another page.

**Comment by laboon** [comment]
Agreed
