### ISSUE TITLE
Clarification on involuntary chilling

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#3828]
https://wiki.polkadot.network/docs/maintain-guides-how-to-chill#involuntary-chills

"Involuntary Chills
If a validator was unresponsive or found to have committed a slashable offense within two eras, the validator will be removed from the active set in a process known as involuntary chilling. When a validator has been involuntarily chilled, it is necessary for the nominators that were previously nominating that validator to re-issue the nominate call."

What does this mean "within two eras"?

And do slashable offenses mean any offense which could be slashed, or only ones which resulted in a slash? For example, if my validator is offline for an epoch, but it is the only one, it could have been slashed, but it wasn't. Is that still a "slashable event" and will that validator be involuntarily chilled? We should clarify this.

**Comment by DrW3RK** [comment]
Fixed with https://github.com/w3f/polkadot-wiki/pull/3829
