### ISSUE TITLE
Polkadot Spec and Parachain Implementer's Guide - Add content summary and references to the Wiki

### ISSUE THREAD

**Issue by DrW3RK** [w3f/polkadot-wiki#3861]
The WIki docs need to be augmented with the content summary of Polkadot Spec and Parachain Implementer's guide wherever appropriate with references to the spec docs

- [x] https://spec.polkadot.network/
- [x] https://paritytech.github.io/polkadot/book/

**Comment by alfarok** [comment]
https://spec.polkadot.network/ knowledge integration addressed in #4009 and #4087

**Comment by filippoweb3** [comment]
@DrW3RK @alfarok, in my opinion, this can be closed. I will provide to unify the content spread across multiple pages in a future PR. At this stage, the content in the two documents has been added to the wiki either as text or links for advanced users.
