### ISSUE TITLE
Multi-sig account generation with Polkadot-JS is missing?

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#3874]
https://wiki.polkadot.network/docs/learn-account-multisig only includes instructions for doing it via CLI. There is a link to https://wiki.polkadot.network/docs/learn-account-generation#multi-signature-accounts for doing it via Polkadot-JS, but this link seems to be missing the anchor text and I can't find it anywhere on the linked page.

**Comment by laboon** [comment]
It's actually on https://support.polkadot.network/support/solutions/articles/65000181826-how-to-create-and-use-a-multisig-account

Please update link

**Comment by DrW3RK** [comment]
Yes. The new Wiki section is here https://wiki.polkadot.network/docs/learn-account-multisig#example-with-polkadot-js

Probably need to update the section title to "Multisig Account Management with Polkdot-JS" for the search bar to pick it up

We devised a plan to fix broken markdown links. Let me create a new issue for that.

**Comment by filippoweb3** [comment]
@laboon @DrW3RK there is an open PR on the reorg of multisigs, I linked it here is open for review
