### ISSUE TITLE
Fix broken markdown links due to the Wiki Reorg

### ISSUE THREAD

**Issue by DrW3RK** [w3f/polkadot-wiki#3875]
The first step of this issue is identifying the PRs that create broken markdown links elsewhere in the Wiki.
Here are a few to get started with. Populate the list below

- [ ] https://github.com/w3f/polkadot-wiki/pull/3841/
- [ ] https://github.com/w3f/polkadot-wiki/pull/3825/
- [ ] https://github.com/w3f/polkadot-wiki/pull/3787
- [ ] https://github.com/w3f/polkadot-wiki/pull/3817
... more

The next step is to create a single PR for each single list item above. Helps the reviewer to thoroughly verify and validate.

**Comment by alfarok** [comment]
I recently created https://github.com/w3f/polkadot-wiki/issues/3970 which I think would help make this investigation much easier.  I have a simple strategy for doing this for all external links but it would be useful to have a similar process for internal markdown references.

**Comment by DrW3RK** [comment]
@alfarok Agreed! Spares everyone from the tedious work. One less thing to worry about when merging PRs

**Comment by alfarok** [comment]
https://github.com/w3f/polkadot-wiki/pull/4002 should have hopefully picked up any of these issues.  I fixed several broken errors in the PR the were uncovered while building the tool.
