### ISSUE TITLE
Update wallets

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#390]
https://wiki.polkadot.network/docs/en/build-tools-index#wallets

There are more wallets out there now, and we may want to review if the ones we link to are still supported / are safe.

**Comment by laboon** [comment]
Mo has a list of wallets on the drive, you can ask him for a link if you don't have it.

**Comment by ansonla3** [comment]
@laboon sorry, who is Mo?

**Comment by ansonla3** [comment]
@krichard410 can we close this? #528 ?
