### ISSUE TITLE
Ideal inflation rate is not always 50%

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#3913]
https://wiki.polkadot.network/docs/learn-staking-advanced#inflation

"An ideal staking rate of 50% stabilizes the network"

This is not true. The ideal staking rate varies based on the number of parachains. It is 50% in the example we give but it is not true globally.

**Comment by DrW3RK** [comment]
This issue was already resolved with https://github.com/w3f/polkadot-wiki/pull/3656/files but was overwritten by a PR later. Sorry about that! @filippoweb3 could you incorporate the changes from this https://github.com/w3f/polkadot-wiki/pull/3656/ back to the staking page?
