### ISSUE TITLE
Can we get the latest (v0.7.30) binary please?

### ISSUE THREAD

**Issue by pkrasam** [w3f/polkadot-wiki#392]
### Fast Install Instructions (Linux)

> Not recommended if you're a validator. Please see [secure validator setup](maintain-guides-secure-validator)

- Download Polkadot binary by running: `curl -sL https://github.com/paritytech/polkadot/releases/download/v0.7.30/polkadot -o polkadot`
- Run the following: `sudo chmod +x polkadot`
- Run the following: `./polkadot --name "Your Node Name Here"`
- Find your node at https://telemetry.polkadot.io/#list/Kusama

**Comment by Swader** [comment]
Will be closed in #394

**Comment by lsaether** [comment]
closed in #394
