### ISSUE TITLE
Add Fathom for Analytics

### ISSUE THREAD

**Issue by Swader** [w3f/polkadot-wiki#393]
https://usefathom.com/

Is privacy friendly.

**Comment by lsaether** [comment]
So I forgot about this - but we actually have Google Tag Manager half way implemented.

I.E. it's implemented but was never activated or maybe it's broken in some way? https://github.com/w3f/polkadot-wiki/blob/master/website/static/js/load.js

**Comment by Swader** [comment]
I recommend removing anything Google-tracky.
