### ISSUE TITLE
[Feature Request] Support for non-conditional plugins

### ISSUE THREAD

**Issue by mrcnski** [w3f/polkadot-wiki#3932]
**Is your feature request related to a problem? Please describe.** 

At https://wiki.polkadot.network/docs/learn-kusama-vs-polkadot under "Cost and Speed" you can see that there is some messed-up formatting due to plugins lacking conditionals. 

---

<img width="899" alt="Screen Shot 2022-10-16 at 15 04 01" src="https://user-images.githubusercontent.com/6035856/196053257-189bef84-c5ec-42c0-8fd3-3bed34a5c640.png">

---

I believe we don't want conditionals in this case, as the plugin is intended to be displayed regardless of whether the mode is `kusama` or `polkadot`.

**Describe the solution you'd like**

I believe `scripts/injectPlugin.js` would have to be modified to add support beyond just the `kusama:` and `polkadot:` conditionals. Maybe by adding a new e.g. `none:` conditional. 

The readme should be modified with information on how to add plugins without conditionals.

**Describe alternatives you've considered**

Good question. I've considered having the plugins on the same line as the text, which fixes the formatting issue; but `prettier` obliterates those changes. Also, the readme says that plugins should always be on their own line.

**Comment by alfarok** [comment]
Hey @m-cat, thanks for bringing this to our attention.  

This is expected behavior because the team wants to force prettier to be executed on commits to maintain formatting consistency.  This requires RPC components to always be wrapped in conditional rendering (even if it's redundant - meaning the same for both Polkadot and Kusama pages) to prevent prettier from butchering the formatting.  It's a bit annoying but a trade-off to keep both systems working together, accurately.  I will take a closer look this afternoon but I believe the formatting here should be something like:

```
Another key technical difference between Polkadot and Kusama is that Kusama has modified governance
parameters that allow for faster upgrades. Kusama is up to four times faster than Polkadot. On
Polkadot, the voting period on referendums lasts
{{ polkadot: <RPC network="polkadot" path="consts.democracy.votingPeriod" defaultValue={403200} filter="blocksToDays"/> :polkadot }}
{{ kusama:  <RPC network="polkadot" path="consts.democracy.votingPeriod" defaultValue={403200} filter="blocksToDays"/> :kusama }}
days, followed by an enactment period of
{{ polkadot: <RPC network="polkadot" path="consts.democracy.enactmentPeriod" defaultValue={403200} filter="blocksToDays"/> :polkadot }}
{{ kusama: <RPC network="polkadot" path="consts.democracy.enactmentPeriod" defaultValue={403200} filter="blocksToDays"/> :kusama }}
days before the changes are enacted on-chain. On Kusama, voting lasts
{{ polkadot: <RPC network="kusama" path="consts.democracy.votingPeriod" defaultValue={100,800} filter="blocksToDays"/> :polkadot }}
{{ kusama: <RPC network="kusama" path="consts.democracy.votingPeriod" defaultValue={100,800} filter="blocksToDays"/> :kusama }}
days, followed by an
{{ polkadot: <RPC network="kusama" path="consts.democracy.enactmentPeriod" defaultValue={115,200} filter="blocksToDays"/> :polkadot }}
{{ kusama: <RPC network="kusama" path="consts.democracy.enactmentPeriod" defaultValue={115,200} filter="blocksToDays"/> :kusama }}
day enactment period. This means stakeholders need to stay active and vigilant if they want to keep
up with all the proposals, referenda, and upgrades, and validators on Kusama often need to update on
short notice.
```

I thought we addressed all of the `RPC` components that weren't wrapped in https://github.com/w3f/polkadot-wiki/pull/3732 but must have missed this one. :+1:

**Comment by alfarok** [comment]
https://github.com/w3f/polkadot-wiki/pull/3945

![image](https://user-images.githubusercontent.com/13341935/196331174-a955d428-b89c-4b1a-b07d-e00f92caa1bc.png)

and

![image](https://user-images.githubusercontent.com/13341935/196331327-4e39a1c8-d729-4833-9207-5f2f01ac8199.png)

**Comment by mrcnski** [comment]
Nice, thank you!
