### ISSUE TITLE
Explain how to "chill" validators and what happens to nominations

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#397]
Brought up by Adrian on Riot, there's no explanation of chilling anywhere on the wiki.

```bash
(1870) ~/web3/polkadot-wiki $ find . -name *.md | xargs grep chill | wc -l
0
```

**Comment by Swader** [comment]
In progress via #178

**Comment by Swader** [comment]
There's a mention of chilling now, but there is still no guide on HOW to chill yourself. That's up next.
