### ISSUE TITLE
As a wiki maintainer, I would like a CI job that runs regularly to audit non-external broken links

### ISSUE THREAD

**Issue by alfarok** [w3f/polkadot-wiki#3970]
See https://github.com/w3f/polkadot-wiki/pull/3442, https://github.com/w3f/polkadot-wiki/issues/3962 and https://github.com/w3f/polkadot-wiki/issues/3875 for recent use-cases.

Docusaurus claims to have this feature and occasionally reports broken links when building but I suspect it is not exhaustive as it currently claims there is only a single broken link:

```
Exhaustive list of all broken links found:

- On source page path = /docs/learn-staking:
   -> linking to learn-cross-consensus.md (resolved as: /docs/learn-cross-consensus.md)
```

The 3 linked PR's above point to many more broken links.  A simple node or python script that could run once a month or so would be very useful in delivering an automated audit on a regular interval.

For a first iteration I would like to focus strictly on internal links as we already have a semi-automated routine for finding 400 & 500 level response codes for external links.  This could later be integrated into a single pipeline.

**Comment by muddlebee** [comment]
+1

**Comment by alfarok** [comment]
@DrW3RK, I have been working on adapting my external link checker script to also work for local references.  Quick progress update:

|Status|File|Url|Code|
|---|---|---|---|
|✔️|build-storage.md|https://wiki.polkadot.network/docs/build-storage#ipfs-interplanetary-file-system|200|
|✔️|build-smart-contracts.md|https://wiki.polkadot.network/docs/build-smart-contracts#ink|200|
|✔️|build-parachains.md|https://wiki.polkadot.network/docs/build-pdk###cumulus|200|
|✔️|build-parachains.md|https://wiki.polkadot.network/docs/build-pdk##future-pdks|200|
|✔️|build-integrate-assets.md|https://wiki.polkadot.network/docs/build-integrate-assets#integration|200|
|✔️|build-open-source.md|https://wiki.polkadot.network/docs/build-open-source#contributing|200|
|✔️|build-open-source.md|https://wiki.polkadot.network/docs/build-open-source#about|200|
|✔️|build-open-source.md|https://wiki.polkadot.network/docs/build-open-source#layers-of-polkadot-stack|200|
|✔️|build-open-source.md|https://wiki.polkadot.network/docs/build-open-source#user-interface|200|
|✔️|build-open-source.md|https://wiki.polkadot.network/docs/build-open-source#tools-apis-and-languages|200|
|✔️|build-open-source.md|https://wiki.polkadot.network/docs/build-open-source#ink-smart-contracts|200|
|✔️|build-open-source.md|https://wiki.polkadot.network/docs/build-open-source#chains-and-pallets|200|
|✔️|build-open-source.md|https://wiki.polkadot.network/docs/build-open-source#host|200|
|✔️|build-open-source.md|https://wiki.polkadot.network/docs/build-open-source#network-maintenance-tools|200|
|✔️|build-open-source.md|https://wiki.polkadot.network/docs/build-open-source#signatures|200|
|✔️|build-open-source.md|https://wiki.polkadot.network/docs/build-open-source#consensus|200|
|✔️|build-open-source.md|https://wiki.polkadot.network/docs/build-open-source#networking|200|
|✔️|build-open-source.md|https://wiki.polkadot.network/docs/build-open-source#contributing|200|
|✔️|build-protocol-info.md|https://wiki.polkadot.network/docs/build-protocol-info#existential-deposit|200|
|✔️|scams.md|https://wiki.polkadot.network/docs/learn-scams#i-got-scammed---what-can-i-do|200|
|✔️|ledger.md|https://wiki.polkadot.network/docs/learn-ledger#using-on-polkadot-js-apps|200|
|✔️|ledger.md|https://wiki.polkadot.network/docs/learn-ledger#confirming-the-address-on-your-device|200|
|✔️|thousand-contributors.md|https://wiki.polkadot.network/docs/thousand-contributors#1kc-evaluators|200|
|✔️|glossary.md|https://wiki.polkadot.network/docs/glossary#testnet|200|
|✔️|glossary.md|https://wiki.polkadot.network/docs/glossary#grandpa-finality-gadget|200|
|✔️|glossary.md|https://wiki.polkadot.network/docs/glossary#grandpa-finality-gadget|200|
|✔️|glossary.md|https://wiki.polkadot.network/docs/glossary#session|200|
|✔️|glossary.md|https://wiki.polkadot.network/docs/glossary#grandpa-finality-gadget|200|
|✔️|glossary.md|https://wiki.polkadot.network/docs/glossary#inherent|200|
|✔️|glossary.md|https://wiki.polkadot.network/docs/glossary#transaction|200|
|✔️|glossary.md|https://wiki.polkadot.network/docs/glossary#grandpa-finality-gadget|200|
|✔️|glossary.md|https://wiki.polkadot.network/docs/glossary#runtime|200|
|✔️|glossary.md|https://wiki.polkadot.network/docs/glossary#testnet|200|
|✔️|glossary.md|https://wiki.polkadot.network/docs/glossary#root-origin|200|
|✔️|glossary.md|https://wiki.polkadot.network/docs/glossary#substrate|200|
|✔️|glossary.md|https://wiki.polkadot.network/docs/glossary#sdk|200|
|✔️|glossary.md|https://wiki.polkadot.network/docs/glossary#parachain|200|
|✔️|glossary.md|https://wiki.polkadot.network/docs/glossary#polkadot-host|200|
|✔️|glossary.md|https://wiki.polkadot.network/docs/glossary#babe|200|
|✔️|glossary.md|https://wiki.polkadot.network/docs/glossary#testnet|200|
|✔️|glossary.md|https://wiki.polkadot.network/docs/glossary#Substrate|200|
|✔️|glossary.md|https://wiki.polkadot.network/docs/glossary#grandpa-finality-gadget|200|
|✔️|glossary.md|https://wiki.polkadot.network/docs/glossary#grandpa-finality-gadget|200|
|✔️|glossary.md|https://wiki.polkadot.network/docs/glossary#mainnet|200|
|✔️|glossary.md|https://wiki.polkadot.network/docs/glossary#Horizontal-Relay-routed-Message-Passing|200|
|✔️|glossary.md|https://wiki.polkadot.network/docs/glossary#webassembly|200|
|✔️|kusama-ledger.md|https://wiki.polkadot.network/docs/kusama-ledger#using-on-polkadot-js-apps|200|
|✔️|kusama-ledger.md|https://wiki.polkadot.network/docs/kusama-ledger#confirming-the-address-on-your-device|200|
|✔️|kusama-claims.md|https://wiki.polkadot.network/docs/kusama-claims#kusama-from-substrate-address|200|
|✔️|kusama-claims.md|https://wiki.polkadot.network/docs/kusama-claims#kusama-from-substrate-address|200|
|✔️|kusama-statemine-ledger.md|https://wiki.polkadot.network/docs/kusama-statemine-ledger#installing-the-ledger-application|200|
|✔️|kusama-statemine-ledger.md|https://wiki.polkadot.network/docs/kusama-statemine-ledger#using-on-polkadot-js-apps|200|
|✔️|kusama-statemine-ledger.md|https://wiki.polkadot.network/docs/kusama-statemine-ledger#working-on-both-kusama-and-statemine|200|
|✔️|kusama-statemine-ledger.md|https://wiki.polkadot.network/docs/kusama-statemine-ledger#teleporting|200|
|✔️|kusama-statemine-ledger.md|https://wiki.polkadot.network/docs/kusama-statemine-ledger#confirming-the-address-on-your-device|200|
|✔️|kusama-statemine-ledger.md|https://wiki.polkadot.network/docs/kusama-statemine-ledger#sending-a-transfer|200|
|✔️|maintain-guides-how-to-validate-polkadot.md|https://wiki.polkadot.network/docs/maintain-guides-how-to-validate-polkadot#note-about-vps|200|
|✔️|maintain-guides-validator-payout.md|https://wiki.polkadot.network/docs/maintain-guides-validator-payout#era-points|200|
|✔️|maintain-sync.md|https://wiki.polkadot.network/docs/maintain-sync#clone-and-build|200|
|✔️|maintain-sync.md|https://wiki.polkadot.network/docs/maintain-sync#using-docker|200|
|✔️|maintain-sync.md|https://wiki.polkadot.network/docs/maintain-sync#types-of-nodes|200|
|✔️|learn-DOT.md|https://wiki.polkadot.network/docs/learn-DOT#lazy-vesting|200|
|✔️|learn-parachains.md|https://wiki.polkadot.network/docs/learn-parachains#common-good-parachains|200|
|✔️|learn-common-good-chains.md|https://wiki.polkadot.network/docs/learn-common-goods#statemint|200|
|✔️|learn-staking-advanced.md|https://wiki.polkadot.network/docs/learn-staking-advanced#pallets-and-extrinsics|200|
|✔️|learn-staking-advanced.md|https://wiki.polkadot.network/docs/learn-staking-advanced#pallets-and-extrinsics|200|
|✔️|learn-staking-advanced.md|https://wiki.polkadot.network/docs/learn-staking-advanced#chilling|200|
|✔️|learn-identity.md|https://wiki.polkadot.network/docs/learn-identity#registrars|200|
|✔️|learn-identity.md|https://wiki.polkadot.network/docs/learn-identity#judgements|200|
|✔️|learn-identity.md|https://wiki.polkadot.network/docs/learn-identity#sub-accounts|200|
|✔️|learn-nominator.md|https://wiki.polkadot.network/docs/learn-nominator#staking-election-stages|200|
|✔️|learn-xcm.md|https://wiki.polkadot.network/docs/learn-xcm#resources|200|
|✔️|learn-account-generation.md|https://wiki.polkadot.network/docs/learn-account-generation#polkadot-js-browser-extension|200|
|✔️|learn-account-generation.md|https://wiki.polkadot.network/docs/learn-account-generation#subkey|200|
|✔️|learn-account-generation.md|https://wiki.polkadot.network/docs/learn-account-generation#polkadot-js-apps|200|
|✔️|learn-account-generation.md|https://wiki.polkadot.network/docs/learn-account-generation#parity-signer|200|
|✔️|learn-account-generation.md|https://wiki.polkadot.network/docs/learn-account-generation#vanity-generator|200|
|✔️|learn-account-generation.md|https://wiki.polkadot.network/docs/learn-account-generation#ledger-hardware-wallet|200|
|✔️|learn-account-generation.md|https://wiki.polkadot.network/docs/learn-account-generation#reset-password-using-the-browser-extension|200|
|✔️|learn-auction.md|https://wiki.polkadot.network/docs/learn-auction#rationale|200|
|✔️|learn-auction.md|https://wiki.polkadot.network/docs/learn-auction#network-implementation|200|
|✔️|learn-auction.md|https://wiki.polkadot.network/docs/learn-auction#examples|200|
|✔️|learn-account-multisig.md|https://wiki.polkadot.network/docs/learn-account-multisig#example-using-multi-signature-accounts|200|
|✔️|learn-account-advanced.md|https://wiki.polkadot.network/docs/learn-account-advanced#address-conversion-tools|200|
|✔️|learn-phragmen.md|https://wiki.polkadot.network/docs/learn-phragmen#understanding-phragmén|200|
|✔️|learn-phragmen.md|https://wiki.polkadot.network/docs/learn-phragmen#phragmms-fka-balphragmms|200|
|✔️|learn-phragmen.md|https://wiki.polkadot.network/docs/learn-phragmen#external-resources|200|
|✔️|learn-phragmen.md|https://wiki.polkadot.network/docs/learn-phragmen#rationale-for-maintaining-an-even-distribution-of-stake|200|
|✔️|learn-proxies.md|https://wiki.polkadot.network/docs/learn-proxies#non-transfer-proxy|200|
|✔️|learn-proxies.md|https://wiki.polkadot.network/docs/learn-proxies#anonymous-proxy-pure-proxy|200|
|✔️|learn-keys.md|https://wiki.polkadot.network/docs/learn-keys#appendix-a-on-the-security-of-curves|200|
|✔️|learn-availability.md|https://wiki.polkadot.network/docs/learn-availability#erasure-codes|200|
|✔️|learn-staking.md|https://wiki.polkadot.network/docs/learn-staking#chilling|200|
|✔️|learn-staking.md|https://wiki.polkadot.network/docs/learn-staking#slashing|200|
|✔️|learn-architecture.md|https://wiki.polkadot.network/docs/learn-architecture#collators|200|
|✔️|learn-governance.md|https://wiki.polkadot.network/docs/learn-governance#council|200|
|✔️|learn-governance.md|https://wiki.polkadot.network/docs/learn-governance#adaptive-quorum-biasing|200|
|✔️|learn-governance.md|https://wiki.polkadot.network/docs/learn-governance#voluntary-locking|200|
|✔️|learn-governance.md|https://wiki.polkadot.network/docs/learn-governance#technical-committee|200|
|✔️|learn-governance.md|https://wiki.polkadot.network/docs/learn-governance#canceling|200|
|✔️|learn-governance.md|https://wiki.polkadot.network/docs/learn-governance#council|200|
|✔️|learn-consensus.md|https://wiki.polkadot.network/docs/learn-consensus#nakamoto-consensus|200|
|✔️|learn-consensus.md|https://wiki.polkadot.network/docs/learn-consensus#casper-ffg|200|
|✔️|learn-assets.md|https://wiki.polkadot.network/docs/learn-assets#advanced-techniques|200|
|✔️|learn-treasury.md|https://wiki.polkadot.network/docs/learn-treasury#creating-a-treasury-proposal|200|
|✔️|learn-treasury.md|https://wiki.polkadot.network/docs/learn-treasury#announcing-the-proposal|200|

**Comment by alfarok** [comment]
Still missing links that use a fully qualified local reference, working on getting them added now.

**Comment by alfarok** [comment]
addressed in https://github.com/w3f/polkadot-wiki/pull/4002
