### ISSUE TITLE
Update sentry node setup

### ISSUE THREAD

**Issue by Swader** [w3f/polkadot-wiki#399]
The `--sentry` flag now takes a list of validator node addresses, it's no longer needed to add them as reserved nodes.

[Source](https://github.com/paritytech/polkadot/issues/923)

**Comment by ansonla3** [comment]
it is still required to use the `reserved-nodes` flag on the validator side to accept the connection only from the sentries. While for the sentry, it has been removed by the [last commit](https://github.com/w3f/polkadot-wiki/commit/01d3beda1650ac4a027585db987c4633bcdf13be#diff-90d04b5aa6eb73970619578c765fa973)

**Comment by Swader** [comment]
Okay
