### ISSUE TITLE
Update Kusama validator page (no Controller = Stash) once PoS is live

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#40]
After PoS goes live, we'll want to eliminate any talk of Controller being the same as Stash.

https://github.com/w3f/polkadot-wiki/blob/master/docs/maintain-guides-how-to-validate-kusama.md

**Comment by lsaether** [comment]
done sometime in the past

**Comment by lsaether** [comment]
Fixed in aeeb0ced6bf7e30a347e822e8ca1817c8796bf1f
