### ISSUE TITLE
Section on Session Keys needs updating

### ISSUE THREAD

**Issue by paradox-tt** [w3f/polkadot-wiki#4007]
https://wiki.polkadot.network/docs/learn-keys#session-keys

The above section references 4 keys but there are 6 keys.  Note that reference of 4 keys was also mentioned in one of the EDX tutorials as well.

**Comment by laboon** [comment]
It used to be 4 keys... thanks, we'll update this.

**Comment by laboon** [comment]
Now it's: 

authority_discovery, babe, grandpa, im_online, para_assignment, para_validator

@filippoweb3 or @alfarok could you make a quick update here?

**Comment by filippoweb3** [comment]
@laboon Are they all sr25519 except GRANDPA right?
