### ISSUE TITLE
Storage section is confusing

### ISSUE THREAD

**Issue by sacha-l** [w3f/polkadot-wiki#4032]
The [Storage]( https://wiki.polkadot.network/docs/build-storage) section in "Build" is a little strange. It starts off with a clear path about storage solutions using IPFS and decentralized storage layers. But then it steers off into [Substrate Storage](https://wiki.polkadot.network/docs/build-storage) which seems to confuse blockchain storage with libraries / interfaces to interact with it as well as how cloud storage and IPFS fits in.

Concretely:
* The "Substrate Storage" section in general seems out of place. The article starts with the direction of "storage solutions" and then suddenly we're learning about storage for Substrate nodes? These are two very different things. Some comments on this section:
   > When building on Substrate, runtime developers can utilize of Substrate's FRAME Storage pallet which gives access to Substrate's storage APIs.
   
   There is no such thing as a "Storage pallet" in Substrate. It's the FRAME support pallet that provides APIs to interact with the storage layers (rocks/parity DB + Patricia merkle trie) [here](https://paritytech.github.io/substrate/master/frame_support/storage/index.html). But I'm not sure that going into detail is relevant here, it's only duplicating information already in the Substrate docs.
(update: did you mean to reference [this](https://github.com/paritytech/substrate/tree/master/frame/transaction-storage) pallet?)
   
* PolkadotJS Storage: this isn't really a concept. IIUC the author is saying "here's how you can query the storage of a Substrate node using this tool". It would be more suitable to rename in as "PolkadotJS APIs for querying storage". The way it's currently presented is a little confusing.
* Substrate Files: this is more of a Crust and Polkadot JS Apps UI concept IIUC. I understand that the author is trying to show how the Polkadot Apps UI makes it easy to interact with IPFS and compatible storage solutions, but this sits completely outside of Substrate. The name makes it sound like there's a module in the Substrate to manage files.

Happy to help fix - wanted to make an issue first to discuss, because my suggestions would imply removing a fair amount out of this article.

**Comment by DrW3RK** [comment]
Thanks for the feedback Sacha! This page does need improvement. I will create a PR and send it for your review.
