### ISSUE TITLE
Add more information on time-delay proxies

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#4048]
Reading through the section on time-delay proxies ( https://wiki.polkadot.network/docs/learn-proxies#time-delayed-proxy ) , it looks like you can just issue a call via the time-delay and it will occur after the time delay.

We should be explicit that there is a separate process for interacting with accounts via time-delay proxy than regular proxies, and it requires two steps (announcing and making the call).

Namely,

1. Create the extrinsic, calling from the target (not the proxy)
2. Get the hash of the extrinsic call
3. Call proxy.announce(HASH) from the proxy
4. Wait for the right number of blocks (as set when creating the proxy)
5. Call proxy.proxyAnnounced with the actual extrinsic set (like a regular proxy call, but set the delegate to the proxy and "real" to the target)

**Comment by laboon** [comment]
If you try to use a regular proxy.proxy call, you'll get a proxy.Unannounced error.

We should also mention the other possible errors you could get (e.g. bad hash, trying to do proxyAnnounced with not enough blocks after the original announce call, etc.)

**Comment by filippoweb3** [comment]
@laboon I will create a tutorial about this, and update the wiki page. I will need to test it first myself on the UI. Thanks for testing it and giving me some guidelines! :)
