### ISSUE TITLE
Add how to set up the faucet

### ISSUE THREAD

**Issue by ansonla3** [w3f/polkadot-wiki#405]
We need to document how to set up the faucet.

**Comment by krichard410** [comment]
@ansonla3 is this still an issue? The Kusama Faucet page says it's been shut down [here](https://wiki.polkadot.network/docs/en/kusama-faucet).

**Comment by laboon** [comment]
Yeah, we've shut down the faucet.  Somebody else may want to raise it from the dead or run their own but I haven't seen any indication of anyone wanting to do it. 

We can probably close it for now, it's definitely not a high priority.  If we decide later that we want to bring it back to life, we can always re-open.
