### ISSUE TITLE
Edit Bags List in Advanced Staking

### ISSUE THREAD

**Issue by filippoweb3** [w3f/polkadot-wiki#4056]
The bags list section can be improved with a better graphic making clear the order of the nodes within the bag and explaining why some nods might be out of the active nominators even if they have the min active bond.

The current figure using arrows is misleading and it is not clear which node comes first (the node with no pointing arrow towards it comes probably?). I propose to put a figure with actual bags and nodes inside it with nodes on the top of the bag being the latest joiners. Something like that.

Focus on the edge case of bags within the range of the minimum active bond, link to video tutorials and support pages. Mention nomination pools as a safe measure to get rewards if the balance is low.

**Comment by DrW3RK** [comment]
> The bags list section can be improved with a better graphic making clear the order of the nodes within the bag and explaining why some nods might be out of the active nominators even if they have the min active bond.

Agreed. A simple example that starts with completely empty bags followed by the sequence of nominations (can reuse the numbers in the given example) and where they would be added in the bags. For instance, the bags list figure shown could have been generated by nominations coming in.this order

5 - goes to the bag 0
15 - goes to the bag 1
12 - gets inserted after 15 in bag 1
23 - goes to the bag 2
7 - gets inserted after 5 in bag 0
19 - gets inserted after 15 in bag 1
8 - gets inserted after 7 in bag 0
....

> The current figure using arrows is misleading and it is not clear which node comes first (the node with no pointing arrow towards it comes probably?).

The text above the figure explains it. Probably can expand on it by mentioning that the nodes are traversed from left to right from the top most bag N to the last bag which is bag 0.

<img width="850" alt="image" src="https://user-images.githubusercontent.com/86818441/202494665-92336f1a-a4e2-40d5-9903-77da0ebf3c79.png">

> I propose to put a figure with actual bags and nodes inside it with nodes on the top of the bag being the latest joiners. Something like that.

By actual bags, do you mean the bags on-chain? It might be interesting to show a screenshot of bags list with the bag that contains the min-active nomination for that era and then showing the nodes in the bag above and below. This would be much easier to show in a video, that can be linked to the text that explains it on the Wiki.
