### ISSUE TITLE
nomination-pools: rename state-toggler to bouncer

### ISSUE THREAD

**Issue by DrW3RK** [w3f/polkadot-wiki#4068]
Nomination pools doc can benefit from a full review.

List of updates needed -
- [x] https://github.com/paritytech/substrate/issues/12747
- [x] https://github.com/w3f/polkadot-wiki/issues/3991

... add items here as necessary

**Comment by rossbulat** [comment]
The rename is now in the codebase, still awaiting it to take effect in the runtime.

**Comment by DrW3RK** [comment]
https://wiki.polkadot.network/docs/learn-nomination-pools#roles Done
