### ISSUE TITLE
The cyptography pages can be grouped and moved to Advanced

### ISSUE THREAD

**Issue by filippoweb3** [w3f/polkadot-wiki#4105]
The info in "Keys" page and "Cryptography Explainer" page can be grouped into one page. That page can be moved under the Advanced menu. The current "Cryptography Explainer"  is very short and does not make sense to keep it as a standalone page.

**Comment by DrW3RK** [comment]
I understand the motivation for this PR, but removing Wiki pages is not generally advised. Think of the external websites that may have linked to the page removed. They will not point the user to any relevant Wiki link.

To mitigate this, we can have two strategies -
1. Retain the old doc and have a note mentioning that the content now exists on a different page and link to it
2. Implement docusaurus redirects - https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-client-redirects#ex-config

You can decide which of these two mechanisms work better for this PR. Happy to help with docusaurus redirects, if needed. If you like to explore an example implemented on the Wiki, it is here https://github.com/w3f/polkadot-wiki/blob/30863e800dfcefc3b84de7b78a7dcfa848dfa27f/polkadot-wiki/docusaurus.config.js#L85 where a Wiki doc's label has been modified.
