### ISSUE TITLE
Split out the Kusama guide

### ISSUE THREAD

**Issue by lsaether** [w3f/polkadot-wiki#411]
The proposal is to build the Kusama guide as a separate site from the Polkadot wiki. One idea is to put two docusaurus sites that both build from the `docs` directory but had different configurations. The mirror script would then work across both sites. 

Could be combined with #369 to solve the issue of where to host the second site. 

Need to be careful not to break CrowdIn during the process.

**Comment by Swader** [comment]
Closing because of #612 et al being done
