### ISSUE TITLE
Fetch the `minimum active nomination` from  on-chain

### ISSUE THREAD

**Issue by alfarok** [w3f/polkadot-wiki#4123]
Via #4120 

Automatically fetch the `minimum active nomination` from the chain and display it in `./docs/general/getting-started.md`?

It adds a lot of value to this page and ensures that the reader is not misled into believing 10 DOT is enough to become an active nominator and earn rewards.

**Comment by DrW3RK** [comment]
@alfarok Looks like we can fetch this value on-chain after this PR https://github.com/paritytech/substrate/pull/12889

**Comment by alfarok** [comment]
@DrW3RK Awesome, that should make life for this task easier!  How long does it normally take for these changes to make their way over to Polkadot-JS or is this something we should request on GitHub now that it is available?

**Comment by alfarok** [comment]
I replaced all the hard-coded values in `Getting-Started` in https://github.com/w3f/polkadot-wiki/pull/4214 but still waiting for this specific value to be available via Polkadot-JS.  I also added this content to the `Kusama-Getting-Started` doc.

**Comment by DrW3RK** [comment]
It will be available after this runtime upgrade makes its way to the chain https://github.com/paritytech/polkadot/releases/tag/v0.9.36

**Comment by DrW3RK** [comment]
Available on chain now 

<img width="877" alt="image" src="https://user-images.githubusercontent.com/86818441/219035136-81329cb6-3d4c-465b-baa0-ef822e3ab363.png">

**Comment by alfarok** [comment]
Nice!  We should be able to use the RPC component w/ the `HumanReadable` filter to add this info to the wiki.  Let me know if you want me to add it.  From the initial linked PR it looks like this info would go on the getting started page?

**Comment by alfarok** [comment]
Addressed w/ https://github.com/w3f/polkadot-wiki/pull/4487
