### ISSUE TITLE
Learn-Staking / Validator Guide link broken

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#417]
https://wiki.polkadot.network/docs/en/learn-staking

"Nominator Guide" points to https://wiki.polkadot.network/docs/en/mirror-maintain-guides-how-to-nominate-kusama which 404s

**Comment by Swader** [comment]
This works just fine for me, you sure?

**Comment by lsaether** [comment]
Works for me as well

**Comment by laboon** [comment]
Sorry, I meant "Validator Guide", not "Nominator Guide"

https://wiki.polkadot.network/mirror-maintain-guides-how-to-validate-kusama

This 404s and sends you to the root https://wiki.polkadot.network/docs/en/
