### ISSUE TITLE
Add Polkadot-JS screenshots for understanding OpenGov (Gov2)

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#4193]
Jaco has made some really nice additions to Polkadot-JS App which help understand when referenda can pass. We should add some screenshots to the Wiki page (or use similar graphics, but why not just use screenshots?)

![Screenshot 2022-12-15 at 09 17 11](https://user-images.githubusercontent.com/1417717/207808491-68b151d5-64d4-4d31-8869-72e2e4eb7cb0.png)

![Screenshot 2022-12-15 at 09 20 33](https://user-images.githubusercontent.com/1417717/207808645-29bfb102-9401-4521-bbdf-e23f08c34cad.png)

**Comment by alfarok** [comment]
I am going to start working on this next week.  For reference here is the link to the graphs https://polkadot.js.org/apps/#/referenda (click the down arrow on the far right reveals the graphs)

**Comment by alfarok** [comment]
This also shares some overlap with #4302 as the metadata returned from invoking `consts.referenda.tracks` provides a lot of th information required to generate similar types of graphs.
