### ISSUE TITLE
add parathreads to polkadot builders guide & developer portal

### ISSUE THREAD

**Issue by jplatts12** [w3f/polkadot-wiki#42]
The parathread model is missing from our story. Now you can more easily and less expensively be a solo chain and access the relay chain when you need finalization/interoperability. People still believe getting a parachain/building on Polkadot is expensive. With the advent of parathreads, that's not true. So we should highlight that in our builders portal so builders know that it is economically viable to build a blockchain w/o running an initial parachain offering or buying a bunch of DOTs.

Polkadot abstracts away the infrastructure layer for blockchains
- choose your own security model
- seamlessly transition between Shared Security and Solo Chain Security (PoA/PoS/PoW) 
- pay for interoperability/finalization as-you-go (less DOTs) or all upfront (more DOTs)

Get interoperability, security, & finalization as a parathread for 50 DOTs [pay as you go model] or as a parachain [open auction, guaranteed-24/7 throughput]

**Comment by lsaether** [comment]
Will add this to #30
