### ISSUE TITLE
Allow user to set cookie settings

### ISSUE THREAD

**Issue by Swader** [w3f/polkadot-wiki#433]
Bottom of the page link for cookie settings is a draft link.

**Comment by Swader** [comment]
@fgimenez do we know where this was supposed to lead?

**Comment by lsaether** [comment]
It should have the similar behavior as the "Cookie settings" link on https://polkadot.network that allows the user to select their cookie preferences.

The Polkadot website uses [Klaro](https://klaro.kiprotect.com/).

**Comment by laboon** [comment]
Is this something we can do or must Federico do it? 

This is a real "ASAP" thing to do to make sure we're legally compliant.
