### ISSUE TITLE
Add Timeline Page for Polkadot launch

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#434]
- [ ] Explain terminology
- [ ] Describe steps and transitions 
- [ ] Explain what is possible in PoA phase
- [ ] Describe how we move from PoA to PoS
- [ ] Explain what is possible in PoS phase
- [ ] Include link from front page

**Comment by lsaether** [comment]
The [FAQ](https://wiki.polkadot.network/docs/en/learn-faq#polkadot-launch) page is a start on some of these points.

**Comment by laboon** [comment]
We can build on Logan's article here: https://polkadot.network/explaining-the-polkadot-launch-process/
