### ISSUE TITLE
Wiki Sweep

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#437]
Review wiki in preparation for mainnet launch.

Special attention should be paid to functionality available at launch:
- [ ] Staking (how to signal intention to validate, how to nominate)
- [ ] Sessions (how to set session keys)
- [ ] Claims (how to claim DOTs) [@lsaether, @ansonla3 ]

**Comment by lsaether** [comment]
Can this be marked as complete?

**Comment by laboon** [comment]
yes
