### ISSUE TITLE
Reorg Nominator Page

### ISSUE THREAD

**Issue by filippoweb3** [w3f/polkadot-wiki#4373]
[The page](https://wiki.polkadot.network/docs/learn-nominator) does not have a clear structure and is difficult to navigate. It can benefit from a revamp of the content so that nominators can use it as a manual for best practices. Some screenshots are old, some topics are already mentioned in other pages (see bags list).

**Comment by DrW3RK** [comment]
Are you referring to the this page or a different page? https://wiki.polkadot.network/docs/learn-validator

> It can benefit from a revamp of the content so that nominators can use it as a manual for best practices. Some screenshots are old, some topics are already mentioned in other pages (see bags list).

That Validator page aims to describe the validator's role in the overall network architecture. I do not see any screenshots and I don't see any topics related to bags-list.

**Comment by filippoweb3** [comment]
@DrW3RK I was wrong, this is about nominator page not validator

**Comment by DrW3RK** [comment]
Got it.
