### ISSUE TITLE
Reorg Availability and Validity Page

### ISSUE THREAD

**Issue by filippoweb3** [w3f/polkadot-wiki#4374]
[The page](https://wiki.polkadot.network/docs/learn-availability) can be merged within the new [Protocol Overview Page](https://wiki.polkadot.network/docs/learn-parachains-protocol) as essentially they are both on the same topic. This issue can also be used to collect any other content related to parachains' protocol and condense it.

**Comment by DrW3RK** [comment]
Sounds good!
