### ISSUE TITLE
Reorg Polkadot Launch Phases Page

### ISSUE THREAD

**Issue by filippoweb3** [w3f/polkadot-wiki#4375]
Content related to [this page](https://wiki.polkadot.network/docs/learn-launch) is scattered in other pages such as:
- [Claims](https://wiki.polkadot.network/docs/claims)
- [Redenomination of DOT](https://wiki.polkadot.network/docs/redenomination)
that in my opinion, are not important in getting started with the ecosystem.

I propose to unify the content on the same page, and eliminate those two pages in Getting Started Section (adding redirects of course).

**Comment by DrW3RK** [comment]
Sounds good!
