### ISSUE TITLE
Phragmen update

### ISSUE THREAD

**Issue by Swader** [w3f/polkadot-wiki#443]
Phragmen is no longer sequential as we described earlier. From Kian (parahprased):

> In the last quarter of each session leading to a new era, some staking operations are disallowed. This is to make sure election solutions that are submitted in the meanwhile stay valid. Most notably:
> 
> - bond_extra, unbond, withdraw_unbonded, rebond
> 
> - validate, nominate and chill
> 
> - payouts
> 
> are disallowed.
> 
> Furthermore, off-chain workers run an optimization on the output before submitting it to reduce the size, without changing any validator's backing stake (compared to the good old sequential phragmen, which is what you were getting prior to this update), but this will further change how the nominator's stake is distributed:
> 
> So far, in sequential Phragmen (old Phragmen), if you vote for two validators and both of them are winners, almost always your stake is distributed among the two of them. One might get more stake, but both get something. reduce() in new Phragmen is very likely to remove as many edges (i.e. votes) as possible. So all in all, it is likely that if I vote for two validators, both of whom are in the winners set, all of my stake will actually be given to one of them.

**Comment by laboon** [comment]
I'll add edge-reduce as a further optimization that we do.  Per Alistair, it's merely post-processing, so we don't have to edit the main Sequential Phragmen walkthrough (phew!).
