### ISSUE TITLE
KSM shown in Westend table on the DOT wiki page

### ISSUE THREAD

**Issue by GCrispino** [w3f/polkadot-wiki#4435]
There is a table that shows the Westend units in the [DOT wiki page](https://wiki.polkadot.network/docs/learn-DOT).

Its last row shows `KSM` as the name of the unit that corresponds to 1.000000000000 WND.
Was this a mistake and `WND` should be used instead?

See below a screenshot of the table:
<img width="714" alt="image" src="https://user-images.githubusercontent.com/8827509/216821301-1c1671a7-0c8d-4222-a168-26ff8f2d484f.png">

If this is indeed a mistake, I can happily open a PR fixing it 👍🏼

**Comment by DrW3RK** [comment]
Thank you! That was indeed a mistake!

**Comment by GCrispino** [comment]
Sure!
