### ISSUE TITLE
Error on OpenGov - Propose a referendum page

### ISSUE THREAD

**Issue by anaelleparity** [w3f/polkadot-wiki#4492]
Section: [OpenGov - Proposing a referendum](https://guide.kusama.network/docs/learn-opengov#proposing-a-referendum)

Issue: The whole section on “endorsing” needs to be labelled under Gov 1.0.

Proposed fix (*in italics*): 
“**Public Referenda**
*Anyone can propose a referendum by depositing the minimum amount of tokens for a certain period (number of blocks).*

*In Governance v1, people who agree with the proposal may deposit the same amount of tokens to show support* [...]
There can be a maximum of 100 public proposals in the proposal queue."

**Comment by DrW3RK** [comment]
Thank you @anaelleparity - A fix is in place to clarify the content https://github.com/w3f/polkadot-wiki/pull/4495

Also, we are working on refining the OpenGov documentation on the Wiki. If you have any feedback on what sections we can improve or add, that will be helpful.

**Comment by anaelleparity** [comment]
No problem, @DrW3RK! 
I will put my feedback together and post here when done.
