### ISSUE TITLE
learn-randomness: rendering issue for polkadot/kusama

### ISSUE THREAD

**Issue by muddlebee** [w3f/polkadot-wiki#4509]
![image](https://user-images.githubusercontent.com/8139783/221161405-520fb23e-94a2-4a4a-be60-48dd440ebb9a.png)

### Issue

Rendering issue for the sentence
**{{ polkadot: Polkadot :polkadot }}{{ kusama: Kusama :kusama }} uses VRF.**

at https://wiki.polkadot.network/docs/learn-randomness

**Comment by DrW3RK** [comment]
Thank you! FIxed it with this commit https://github.com/w3f/polkadot-wiki/commit/a6bf7fca6ca444b6f5ec6d5d4b172c3f371285db
