### ISSUE TITLE
Add Nominating and Validating on Polkadot pages

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#451]
Equivalent to our ["Be a Nominator (Kusama)"](https://wiki.polkadot.network/docs/en/mirror-maintain-guides-how-to-nominate-kusama) and ["Be a Validator (Kusama)"](https://wiki.polkadot.network/docs/en/mirror-maintain-guides-how-to-validate-kusama) pages

**Comment by Swader** [comment]
Ping Urban when ready. Needed for PoA landing page.
