### ISSUE TITLE
[Feature Request] Improve Metadata Explorer

### ISSUE THREAD

**Issue by DrW3RK** [w3f/polkadot-wiki#4516]
https://wiki.polkadot.network/docs/metadata

- it would be cool, to have possibility select "custom endpoint", lets say I am running some local node (ws://localhost:1234) and want to browse metadata - something like [polkadot.js.org/apps](http://polkadot.js.org/apps) does
- it would be nice if AccountNonce could be displayed in snake case: account_nonce as this is how it has to be typed when used as a parameter to the rpc State Call 'method' parameter.

**Comment by alfarok** [comment]
I added some thoughts on the second point in #4517.  For the first point, selecting a new dropdown option `Custom Endpoint` could reveal an addition input field below that would allow the user to enter a custom RPC source.  This would probably take a bit of effort to ensure entering various types of malformed inputs doesn't cause crashes or other issues.  Maybe something like a button next to the field that needs to be clicked which is responsible for validating the path and triggering the document update.
