### ISSUE TITLE
[Feature Request] XCM Documentation Elaboration & Restructure

### ISSUE THREAD

**Issue by CrackTheCode016** [w3f/polkadot-wiki#4541]
This issue is meant to keep track of any discussion and highlight the changes to be made to the [XCM](https://wiki.polkadot.network/docs/learn-xcm) section of the wiki.  

Currently, the wiki _does_ cover the most relevant concepts but could use much more elaboration and context for how to use XCM and where to look for resources.   

A set of guides centering around configuring XCM and relevant parameters would also be beneficial. 

As part of this effort, [`xcm-format`](https://github.com/paritytech/xcm-format) should also be updated, as it gives a good technical reference for the wiki to refer to when discussing instructions & registers.   I've already started a [refactor on my fork.](https://github.com/CrackTheCode016/xcm-format)

### Page Reorg - for "Learn"

In terms of reorganizing the docs, new pages should be added to highlight other aspects (similar to how [Parachains in the wiki are laid out](https://wiki.polkadot.network/docs/learn-parachains)): 

 - Introduction to XCM (Cross Consensus Messaging)
 - Transporting XCM Messages - XCMP, HRMP, & VMP
 - XCM Executor, XCVM, & the xcm-simulator
 - XCM Format Instruction & Register Specification

_...more may be added as needed!_

Each of these pages will hold domain-specific resources for further action (if applicable) and comprehensive info on how to use XCM.  

In the future, it may also be beneficial to include things more builder oriented in the "Build" section of the wiki.

### Outstanding issues 

- [x] Update XCM use cases to ensure accuracy (add as needed), add common ones
- [x] Cover XCM v3 changes
- [ ] Comprehensive table of XCM instructions and registers, what they do, and links to their source.
- [x] Deep dive into the XCM executor and XCVM
- [x] Document the xcm-pallet
- [ ] Document XCM transport methods
- [ ] Document how fees are handled in XCM
- [x] Document crucial XCM config aspects, i.e., transactors, traders, barriers, reserves
- [ ] Document XCM weight calculation
- [ ] Document how XCM messages are constructed for the means of transportation
- [x] Update `xcm-format` 
- [ ] Need more coverage on Asset trapping / claiming mechanisms
- [x] Discussing trust between chains, and how `xcm-config` reflects the trust levels.
- [x] Differences between teleportation, reserves, and which to use.
- [x] Covering `xcm-builder`

_...more may be added as needed!_

**Comment by DrW3RK** [comment]
We added the official XCM docs to the Wiki https://wiki.polkadot.network/docs/learn/xcm/introduction
