### ISSUE TITLE
help about refund Deposits

### ISSUE THREAD

**Issue by Nick-1979** [w3f/polkadot-wiki#4634]
It would be helpful If we have some explanation about the following extrincics regarding openGov:

- refundDecisionDeposit
- refundSubmissionDeposit
 
Do they have to be called when a proposal is approved or are they called automatically with approved proposal enactment? what happens when a proposal is rejected?

![refund](https://user-images.githubusercontent.com/46442452/228231697-d7904955-d4f2-4a50-8a7b-08c1b3216465.jpeg)

**Comment by DrW3RK** [comment]
https://github.com/w3f/polkadot-wiki/pull/5230
