### ISSUE TITLE
Add section or page about proxy, delegate, and proxy_delegate

### ISSUE THREAD

**Issue by joepetrowski** [w3f/polkadot-wiki#468]
We have really useful proxy/delegation features that allow stash/controller style relationships for voting. Add a section or page explaining the differences between them and between normal voting.

**Comment by lsaether** [comment]
We have this on the "Participate in Democracy" page but it could be spruced up. https://wiki.polkadot.network/docs/en/maintain-guides-democracy#delegate-a-vote

**Comment by joepetrowski** [comment]
Ah, didn't know about that. But indeed a lot of info is wrong since the March refactor.

**Comment by Swader** [comment]
Closed in #551
