### ISSUE TITLE
Add L2 comparisons to "comparisons" page

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#4685]
We should add L2 comparisons to the [Comparisons section](https://wiki.polkadot.network/docs/learn-comparisons) of the wiki (maybe not specific ones, but at least comparing parachains to optimistic and ZK rollups)

Shawn T. already put together a decent overview in [this slide deck](https://drive.google.com/file/d/1IKTxO5hlsu5Bct8ubB--KA6WtSEpfnt3/view).

**Comment by filippoweb3** [comment]
hey @laboon did you check if what has been done here --> https://github.com/w3f/polkadot-wiki/pull/3789 does not satisfy your request? The PR has been open for a while, I sent you a review request

**Comment by CrackTheCode016** [comment]
Addressed and merged here: https://github.com/w3f/polkadot-wiki/pull/4747
