### ISSUE TITLE
Fix Auction Tool on the Wiki

### ISSUE THREAD

**Issue by DrW3RK** [w3f/polkadot-wiki#4693]
<img width="750" alt="image" src="https://user-images.githubusercontent.com/86818441/231696603-71469977-3c57-4c0e-b31d-5adb9cf642e7.png">

> https://parachains.info/auctions/kusama - this says the next auction (Auction 78) starts today, but the Kusama Guide says the next auction is Auction 74 and starts 12 May. https://guide.kusama.network/docs/learn-auction/

- [ ] Replace the tool with a link to Parachains Info for the time being
- [ ] Fix the issue with the Auction Tool

**Comment by CrackTheCode016** [comment]
Being addressed in #4829
