### ISSUE TITLE
Add notice of shutdown on Kusama Faucet page if permanent

### ISSUE THREAD

**Issue by rrtti** [w3f/polkadot-wiki#470]
https://wiki.polkadot.network/docs/en/kusama-faucet needs a notice of shutdown at the beginning, maybe something in the direction of Bill's tweet:

"Due to high demand as well as spammers causing problems for regular users, the Kusama faucet has been shut down. Web3 Foundation will consider new ways to distribute KSM for people who need KSM to build."

**Comment by laboon** [comment]
Thanks! We're aware but just haven't had a chance to change the wiki yet, working on several other things today. =). But we'll get to it very shortly!

**Comment by laboon** [comment]
Fixed in https://github.com/w3f/polkadot-wiki/pull/472
