### ISSUE TITLE
Need clear section for new Kusama users to get started and set up account

### ISSUE THREAD

**Issue by dreecer1** [w3f/polkadot-wiki#475]
**Issue:** For users new to the Kusama ecosystem, as opposed to DOT holders, there is not currently a category that makes intuitive sense for “getting started”. The Getting Started section starts with Faucet (currently down for spammers), and now the account setup information is under “Claims” which doesn’t apply to people new to Kusama. We have already had a couple Ambassadors even come to us asking how to set up an account even after sending them the Wiki instructions.

**Proposed change:** Move or copy the “Create a Kusama account” steps to a new leading category called “Account Setup” under the Getting Started section, along with the wallets that we recommend for KSM. This way, a new user, who is not coming for the faucet or claims, has an intuitive page link to click to get started.

**Comment by Swader** [comment]
This might be resolved by #619 and the results of #612 et al for Kusama separation.

**Comment by Swader** [comment]
@krichard410 do you have bandwidth to put together a getting started page for Kusama like you did for Polkadot?

**Comment by krichard410** [comment]
@Swader Yup! I'll whip up a getting started page for Kusama today 👍
