### ISSUE TITLE
Add Polkassembly as proposal announcement tool

### ISSUE THREAD

**Issue by rrtti** [w3f/polkadot-wiki#480]
On https://wiki.polkadot.network/docs/en/mirror-learn-treasury 

Add Polkassembly as an announcement and discussion mechanism under "Announcing the Proposal", along with Kusama Riot channel, Kusama forum, KGP and Commonwealth.im

**Comment by Swader** [comment]
Note that this is a mirror page so warrants some tiptoeing - mirror pages are auto-copied from their clones in the main polkadot wiki. You can only enhance the original, and whatever is in the original will be copied to the mirror. I'm working on a way to include conditional Kusama content in sources.
