### ISSUE TITLE
Create a KodaDot section at Polkadot NFT wiki page 

### ISSUE THREAD

**Issue by poppyseedDev** [w3f/polkadot-wiki#4804]
Create a mention of KodaDot and the work they are doing at wiki page: https://wiki.polkadot.network/docs/learn-nft

Related to [KodaDot issue](https://github.com/kodadot/nft-gallery/issues/4847)

**Comment by DrW3RK** [comment]
Done! https://github.com/w3f/polkadot-wiki/pull/4817
