### ISSUE TITLE
[Feature Request] : update the ecosystem projects supporting ink contracts and evm smart contracts

### ISSUE THREAD

**Issue by muddlebee** [w3f/polkadot-wiki#4818]
https://wiki.polkadot.network/docs/build-smart-contracts#parity-tech

**Comment by CrackTheCode016** [comment]
@muddlebee I assume you're referring to new developments with parachains like Astar, is that correct>

**Comment by muddlebee** [comment]
@CrackTheCode016

I was referring to the new parachains supporting ink contracts and evm contracts.

like aleph zero, supporting ink contracts
https://testnet.alephzero.org/

**Comment by DrW3RK** [comment]
@muddlebee Thank you! AlephZero is a solochain which is bridging to Polkadot through the parachain slot. They are doing remarkable work with ink contracts, but not necessarily on the parachain on Polkadot (which is serving as the bridge). Please correct me if I am wrong.

We can add AlephZero to the doc, but probably under Substrate based solochains section. What do you think?

**Comment by muddlebee** [comment]
@DrW3RK oh is it? I wasn't sure either. I checked a few articles here, which mentions they have won a parachain slot 🤔 https://alephzero.org/blog/aleph-zero-polkadot-bridge-parachain/

although a section for solochains will be also great 👍

**Comment by muddlebee** [comment]
> First, let’s clarify one thing. Aleph Zero's AZERO does not become a parachain now. The slot will be used only for bridging purposes between Polkadot and Aleph Zero ecosystems, creating an intermediary parachain between these two networks.

https://twitter.com/Aleph__Zero/status/1621195169034010624

looks like you are right @DrW3RK

**Comment by muddlebee** [comment]
additionally https://contracts-ui.substrate.io/  mentions the mainnet and testnets where the ink contracts are live.

![image](https://github.com/w3f/polkadot-wiki/assets/8139783/70e31845-a168-480a-ba4f-a26beaa009bd)

**info on obtaining testnet tokens**
- https://use.ink/testnet
- https://testnet.alephzero.org/

**examples of ink- contracts**
- https://use.ink/examples/smart-contracts

It will be great if we can create more info around smart contracts, so it can guide to the links above. Initially I faced some challenges navigating and deploying the ink contracts , it was all confusing. Will be great if can add a nice guide :)

**Comment by DrW3RK** [comment]
Yeah, I'm fully with you on adding this to the doc. Just that we need a new section for content like this, is what I was highlighting earlier. (Given that this is Polkadot Wiki)
