### ISSUE TITLE
Create an alphabetical list of all NFT projects for better navigation

### ISSUE THREAD

**Issue by yangwao** [w3f/polkadot-wiki#4832]
> we will create an alphabetical list of all the projects for better navigation through a PR later.

So new order should be following if I get it right?

- Astar
- Basilisk
- Efinity
- Moonbeam
- Statemint
- KodaDot
- RMRK
- Unique Network

_Originally posted by @yangwao in https://github.com/w3f/polkadot-wiki/issues/4817#issuecomment-1559782190_

**Comment by DrW3RK** [comment]
indeed!

**Comment by yangwao** [comment]
> indeed!

@DrW3RK any updates on this? 
Because we want to make another PR that KodaDot has support for Statemint on Polkadot. 

- https://github.com/kodadot/nft-gallery/issues/6092

**Comment by DrW3RK** [comment]
Thanks for the follow up @yangwao The team is just back from the long weekend and we will get to this by the end of the day on Wednesday  (Jun 01st). Thanks for your patience!
