### ISSUE TITLE
Define "Confirming Period"

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#4837]
https://guide.kusama.network/docs/maintain-guides-opengov

We refer to the Confirming Period but don't define it. We should include it in the list here and explain it (I saw this on Kusama but should be on both Kusama Guide and Polkadot Wiki)

**Comment by CrackTheCode016** [comment]
Moonbeam defines it here, as far as I can tell it is accurate

> Confirm Period - a period of time within the Decide Period where the referendum needs to have maintained enough Approval and Support to be approved and move to the Enactment Period


https://docs.moonbeam.network/tokens/governance/voting/opengov-voting/
