### ISSUE TITLE
Please add Darwinia2 to the section on smart contracts in the Polkadot document.

### ISSUE THREAD

**Issue by 1022ranji** [w3f/polkadot-wiki#4839]
Please add [Darwinia2](https://darwinia.network/) to the section on [smart contracts](https://wiki.polkadot.network/docs/build-smart-contracts#parachains) in the Polkadot document.

One month ago, Darwinia completed an upgrade and is now presented to users as a cross-chain smart contract platform and message port network.
The official website is currently being updated, and you can find more details [here](https://github.com/darwinia-network/home/pull/346).

Technical documentation reference:

- GitHub: https://github.com/darwinia-network
- Docs: https://docs.darwinia.network/
- SDK: https://docs.darwinia.network/builder/solidity-sdk/api-reference

 
Others about Darwinia2:

- [Technical Feasibility Research And Test for Merging Solo Chain and Parachain](https://bit.ly/3UDOLgD)
- [ Darwinia 2.0 Merge Overview](https://medium.com/darwinianetwork/darwinia-2-0-merge-overview-96af96d668aa)
- [ Darwinia 2.0 Will Upgrade Staking Module, Which Allows Users To Earn Staking Rewards Via Nominating Collator](http://bit.ly/3hRR5Cf)
- [ Darwinia 2.0 Staking Mechanism Adjustments](https://bit.ly/3FMYo7V)
- [ Darwinia 2.0 Blockchain Data Migration](https://bit.ly/3C7ag2v)
- [First Successfully Merge Of Substrate Solo-Chain And Polkadot Parachain](https://bit.ly/3QLMFu2)
- [Darwinia 2.0 Has Been Successfully Upgraded](https://twitter.com/DarwiniaNetwork/status/1650462863507750914)

<img width="1330" alt="image" src="https://github.com/w3f/polkadot-wiki/assets/80877629/ea0df0d6-327c-4306-bd73-ea561447fbde">

**Comment by muddlebee** [comment]
@1022ranji I think you can open a PR directly.
