### ISSUE TITLE
[Feature Request] : add info about community events child bounty

### ISSUE THREAD

**Issue by muddlebee** [w3f/polkadot-wiki#4858]
To be added here : https://wiki.polkadot.network/docs/community#events

Community events child bounty info 
- https://polkadot.polkassembly.io/child_bounty/249
- https://www.notion.so/web3foundation/Community-Events-Working-Group-15aebfe73e934ff9991a5464ac10ba8e

**Comment by DrW3RK** [comment]
@muddlebee The Notion link is quite outdated. Do you know of any website that provides more up-to-date info about the ecosystem events?

**Comment by muddlebee** [comment]
@DrW3RK https://web3foundation.notion.site/Community-Events-Introduction-05199fe6556b41f48a3390b1868c9ae7

check this once

**Comment by DrW3RK** [comment]
Thanks! I'll get the logo updated on the notion document and then have it added to the Wiki
