### ISSUE TITLE
Rename Statemine/Statemint to AssetHub

### ISSUE THREAD

**Issue by DrW3RK** [w3f/polkadot-wiki#4883]
This is not a trivial find-and-replace task on the Wiki https://github.com/paritytech/cumulus/pull/2633

<img width="487" alt="image" src="https://github.com/w3f/polkadot-wiki/assets/86818441/60754659-ef68-4f19-a0bd-30dc0b982e52">

The conditional rendering aspect of the Wiki docs will pose some challenges, as well as fetching on-chain values and the respective JS component update. Better to do it across multiple PRs.

**Comment by filippoweb3** [comment]
@DrW3RK @CrackTheCode016  should we do it by sidebar category? Getting Started -> Learn -> Build -> Maintain ? Like 4 PRs?

**Comment by CrackTheCode016** [comment]
@filippoweb3 That sounds good, multiple PRs to ensure we don't miss anything 👍

**Comment by joepetrowski** [comment]
If you need any graphics/logos, they are in [Asset Hub Logo.zip](https://github.com/w3f/polkadot-wiki/files/11745027/Asset.Hub.Logo.zip)

**Comment by naresh63** [comment]
> @filippoweb3 That sounds good, multiple PRs to ensure we don't miss anything 👍

Hello, I want to work on this. please suggest me how to start.

**Comment by kpx001** [comment]
hay
