### ISSUE TITLE
Remove incorrect statements about account keys and session keys

### ISSUE THREAD

**Issue by lsaether** [w3f/polkadot-wiki#49]
Brings in this [open PR](https://github.com/w3f/polkadot-wiki-old/pull/275) from the old wiki. 

@burdges, any idea when the proxy key will be introduced? I'm a bit hesitant adding it to the wiki if it's not going to implemented during the Kusama cycle.

**Comment by burdges** [comment]
We've had proxy keys since March https://github.com/paritytech/substrate/pull/2137 but not sure when the key took it's current form https://github.com/paritytech/substrate/blob/master/srml/democracy/src/lib.rs#L288 see also https://github.com/paritytech/substrate/issues/3544
