### ISSUE TITLE
[Feature Request] : Add clarification for transaction per second(TPS) for Polkadot 

### ISSUE THREAD

**Issue by muddlebee** [w3f/polkadot-wiki#4908]
We frequently get this question at the discord/element channels 

Quoting Gavin's answer from #watercooler channels

>TPS, there is no accepted standard for how you actually measure it. E.g. one particularly unscrupulous project counts the discrete communications done within their consensus algorithm as a "transaction" (I believe on one occasion, they published a figure that even counted transactions that just happened to be sitting in the transaction pool under "TPS").

> TPS can also be inflated by counting derivative chains which are only partially secured by a main chain's consensus.

> So when measuring TPS you really need to look at a few things\: are the transactions actually part of the *utility* of the chain (and not simply its internal working)? At what point do such transactions become actually irrevertible? How much would it cost to revert a transaction or otherwise conduct an invalid state transition? Is this value uniform regardless of where and how the transaction happens?

**Comment by CrackTheCode016** [comment]
I think this would be good to include, perhaps in the https://wiki.polkadot.network/docs/faq.

TPS inherently, is a very subjective measurement that as Gavin mentions has a number of factors.  Not to mention that it's hard to gauge the usefulness of the metric anyways, as it's highly dependent on _what_ a transaction does for a particular network.

**Comment by DrW3RK** [comment]
Sounds good to me! Please add the relevant info to FAQ @CrackTheCode016
