### ISSUE TITLE
[Feature Request] : add info about comsos interchain security (latest feature)

### ISSUE THREAD

**Issue by muddlebee** [w3f/polkadot-wiki#4979]
https://wiki.polkadot.network/docs/learn-comparisons-cosmos
can compare with the shared security model of relay-parachains?

source article on comsos interchain security : https://blog.cosmos.network/interchain-security-begins-a-new-era-for-cosmos-a2dc3c0be63

**Comment by GauravDhak** [comment]
i want to work on this issue i already go through that medium blog please assign me this issue

**Comment by DrW3RK** [comment]
PRs (rather than Wiki issues) are encouraged for Polkadot-unrelated topics.
