### ISSUE TITLE
[Feature Request] : Update Polkadot 2.0 vision

### ISSUE THREAD

**Issue by muddlebee** [w3f/polkadot-wiki#4992]
https://wiki.polkadot.network/docs/learn-launch#polkadot-20

Context of Polkadot 2.0 : [Gavin Wood Outlines the Future of Polkadot | Polkadot Decoded 2023](https://youtu.be/GIB1WeVuJD0)

**Comment by filippoweb3** [comment]
Yep, this is in the plan and will be added in the Future Implementations category or elsewhere.
