### ISSUE TITLE
[Feature Request] chatbot for the wiki

### ISSUE THREAD

**Issue by polkatax** [w3f/polkadot-wiki#5018]
**Is your feature request related to a problem? Please describe.** 
A chatbot for the polkadot wiki might help users to quickly find the information they require.

I'm not sure if creating a feature request is the correct approach or where to pose the question.
I'm currently working on a chatbot for the polkadot wiki. It can be found [here](https://polkabot.org).

**Describe the solution you'd like** 
Is this something the maintainers of the wiki are interested in incorporating? It could be as simple
as adding a iframe or some html + javascript to call the API.

**Additional context** 
I created a referendum for funding https://polkadot.polkassembly.io/referenda/61.
The chatbot uses the openai API and performs calls to subscan.io to receive up to date information.

**Comment by filippoweb3** [comment]
Hi @loanMaster, the wiki is currently under major reorganization at least until EOY. If the chatbot meets the foundation's legal requirements and can adapt itself to the continuously changing content of the wiki, then I think this could be a valuable addition to the wiki. @DrW3RK any idea/opinion about this?

**Comment by DrW3RK** [comment]
Added a response here https://github.com/w3f/polkadot-wiki/discussions/5015#discussioncomment-6382155
