### ISSUE TITLE
Conviction Voting - Polkadot Params

### ISSUE THREAD

**Issue by DrW3RK** [w3f/polkadot-wiki#5049]
There is some ambiguity with the archived page section showing up in the search results that misleads readers about current params https://wiki.polkadot.network/docs/learn-governance#voluntary-locking Either remove the section or update it to point to the correct params for OpenGov

![image](https://github.com/w3f/polkadot-wiki/assets/86818441/c59c6414-b7ed-4d29-be22-a79a556ce2d8)

**Comment by filippoweb3** [comment]
this must have been updated already. Strange it isn't. The wiki is right, the JS apps are showing the wrong locking times. This issue was already notified to @jacogr if I remember well.

**Comment by DrW3RK** [comment]
Cool! 

The problem is that Wiki readers end up on the archived page section instead of OpenGov one when they search for conviction voting in the search bar. We need to ensure that they land on the OpenGov section. Hence, either remove this section or add Gov1 in the section title and add an info note to check out OpenGov section.

**Comment by filippoweb3** [comment]
Yeah, I can add the text to the OpenGov page and add a banner on the Gov1 page so that if people land on gov1, they can go and look at the OpenGov page to know more about conviction. Would this be a potential solution?
