### ISSUE TITLE
Chilling [Polkadot Wiki]

### ISSUE THREAD

**Issue by ma-florencia** [w3f/polkadot-wiki#5057]
Been researching about Chilling/Freezing/Jailing events.

Have been reading through the Polkadot Wiki but could not find any information on Chilling on Polkadot (as safety mechanism so validators don't continue getting slashed and not in regards to 'paused' but bonded staking). Had some side conversations and afaiu there is such a thing as chilling in Polkadot, but could not find any info on the wiki (apologies if I've missed it!). Would it be possible to add it?

**Comment by laboon** [comment]
@ma-florencia Have you seen this page? https://wiki.polkadot.network/docs/maintain-guides-how-to-chill

**Comment by ma-florencia** [comment]
thank you, yes! I believe then that what I was looking is explained under "involuntary chilling". Sorry if I've missed that before and thanks for the quick turnaround :)
