### ISSUE TITLE
Add warning about re-using reaped accounts

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#5066]
https://wiki.polkadot.network/docs/learn-accounts#existential-deposit-and-reaping

A re-activated reaped account is vulnerable to replay attacks, since it resets the nonce. We should add a warning to this section.

**Comment by michalisFr** [comment]
It's worth mentioning that this affects immortal extrinsics almost exclusively. Mortal transactions expire, so it's very unlikely that they're replayed.
