### ISSUE TITLE
Wiki Reorg: Revisit Validator Guides

### ISSUE THREAD

**Issue by filippoweb3** [w3f/polkadot-wiki#5112]
Validator Guides in the maintain section are outdated, and the following points can be improved:
- stress the importance of decentralizing the network and building nodes from home -> follow example of Ethereum pages https://ethereum.org/en/staking/solo/
- demystify worries related to validating without a cloud service provider -> pros and cons table
- clean the guides and show the quickest and safest way to set up a node, remove parts that present vulnerabilities or thing that are not recommended from security perspective
- add minimum specs and keep the current ones as "optimal"

All this needs testing before write-up.

**Comment by DrW3RK** [comment]
Create a new issue after discussing with validators,
