### ISSUE TITLE
Add Wireguard information to the "Using systemd for the Validator Node" section

### ISSUE THREAD

**Issue by m-saxemberg** [w3f/polkadot-wiki#513]
I'd like to propose adding a new subsection to the following page: 
https://wiki.polkadot.network/docs/en/maintain-guides-how-to-systemd

The new section should contain information about automatically restarting the wireguard VPN setup created in the "Set Up a Sentry Node" - configuration section.
https://wiki.polkadot.network/docs/en/maintain-guides-how-to-setup-sentry-node#3-configuration
So that the  tunnel interface also restarts automatically as a systemd process.

Concretely, it should look something like this:

### Wireguard systemd configuration for Validator - Sentries VPN.

You can also restart automatically your VPN configuration among validator and sentries using the configuration you have already created in [Set Up a Sentry Node - Public Node](https://wiki.polkadot.network/docs/en/maintain-guides-how-to-setup-sentry-node)

First create a new unit file called wireguard.service in /etc/systemd/system/.

`touch /etc/systemd/system/wireguard.service`

Then you will write the commands needed to start automatically the wireguard connection previously configured as `wg0` in the `wgo.conf` file  under the` /etc/wireguard/` directory.
```

[Unit]
Description=Wireguard VPN

[Service]
Type=forking
ExecStart=PATH_TO_WG-QUICK_BIN up wg0

Restart=always

[Install]
WantedBy=multi-user.target
```

To enable this to autostart on bootup run:

`systemctl enable wireguard.service`

Start it manually with:

`systemctl start wireguard.service`

You can check that it's working with:

`systemctl status wireguard.service`

You can tail the logs with journalctl like so:

`journalctl -f -u wireguard`

**Comment by Swader** [comment]
Good idea. Could you submit a PR with the fix please?

**Comment by m-saxemberg** [comment]
PR was merged into the wiki
