### ISSUE TITLE
[Feature Request] Document Fellowship Vote System & Associated Curves

### ISSUE THREAD

**Issue by CrackTheCode016** [w3f/polkadot-wiki#5147]
Currently, the only documented part of the fellowship's calculations for voting is the `Fellowship Admin` graph.  We should add more information pertaining to how a fellowship poll works, along with the exact way rankings correlate to the number of tallys, and finally how this would affect external referenda.

Pallet for reference: https://github.com/paritytech/polkadot-sdk/blob/a8468134932358abed247963a640877c550a2c64/substrate/frame/ranked-collective/src/lib.rs#L212

**Comment by DrW3RK** [comment]
Fellowship has a dedicated website https://polkadot-fellows.github.io/dashboard/ where this info can reside.
