### ISSUE TITLE
[Feature Request] Restructure ink!-related stuff

### ISSUE THREAD

**Issue by wottpal** [w3f/polkadot-wiki#5242]
Page: https://wiki.polkadot.network/docs/build-open-source

In the course of https://github.com/w3f/polkadot-wiki/pull/5241, I've noticed that, currently, there is a dedicated "[ink! Smart Contracts](https://wiki.polkadot.network/docs/build-open-source#ink-smart-contracts)" section but a lot of ink!-related stuff is also under "[Tools, APIs, and Languages](https://wiki.polkadot.network/docs/build-open-source#tools-apis-and-languages)". This should all be reorganized under the ink! section IMO. (At least that was the reason I've overseen a lot of the stuff there in the first place, because I'm mainly interested in ink!-stuff.)

Also, during reorganization make sure to clearly classify frontend- and/or contract-related stuff. E.g. `typechain-polkadot` is classified under "Easy Smart Contract Development" which is a bit misleading IMO.

**Comment by filippoweb3** [comment]
@wottpal thank you for this! Would you be able to propose a PR with the changes you are suggesting, from a user perspective?

**Comment by wottpal** [comment]
Ayye, of course. Will add it to https://github.com/w3f/polkadot-wiki/pull/5241, just wanted to ask before touching your structure. 🫡
