### ISSUE TITLE
[Feature Request] : Explain more on the inner workings of smoldot: light clients

### ISSUE THREAD

**Issue by muddlebee** [w3f/polkadot-wiki#5245]
Current section : https://wiki.polkadot.network/docs/build-substrate

Some resources on in-depth explanation of smoldot
- https://youtu.be/YjsLpfM6a7E
- https://hackmd.io/UPts8qymSjmY5IwZk2tv0w#Smoldot-Hello-world

**Comment by filippoweb3** [comment]
We will create a dedicated page in the Learn section about light clients, thanks! Some stuff is mentioned in this PR https://github.com/w3f/polkadot-wiki/pull/5187.

**Comment by DrW3RK** [comment]
Found this resource that we can link on the Wiki and close this issue https://hackmd.io/@s_iGZLIITG6WjSgnFX0pcg/rkmmcvBno
