### ISSUE TITLE
Asset Hub on Kusama Guide shows DOT instead of KSM

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#5273]
https://guide.kusama.network/docs/learn-guides-assets-create/#creating-assets-on-the-asset-hub

"To create an asset on the Asset Hub, you would need a deposit of 10 DOT and around 0.201 DOT for the metadata."

This should reference KSM, not DOT.

**Comment by DrW3RK** [comment]
Fixed https://github.com/w3f/polkadot-wiki/commit/cfe22d814ff94476a21b95f524e321be23027469
