### ISSUE TITLE
Re-word referendum canceling for arbitrary referenda

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#5285]
https://wiki.polkadot.network/docs/learn-guides-polkadot-opengov#cancel-or-kill-a-referendum

"To cancel a referendum, you need first to submit a preimage. Go to the [Polkadot-JS UI > Governance > Referenda](https://polkadot.js.org/apps/#/referenda) and click on the "Add Preimage" button. You must specify the specific call enacted if the proposal passes. To cancel a referendum, you must specify the referenda.cancel extrinsic of referendum 249."

Change the last sentence to:

"To cancel a referendum, you must specify the referenda.cancel extrinsic with the index equal to the Referendum you wish to cancel. In the screenshot below, the Referendum to be cancelled is 249."

**Comment by DrW3RK** [comment]
Perhaps, the wording could be improved, but we do need to create a preimage with the cancel extrinsic and then use it to create a referenda on the Polkadot OpenGov Referenda canceler track.

**Comment by laboon** [comment]
Yes, but the wording implies (or actually states) that the referenda.cancel extrinsic *must* be of Referendum 249. This clarifies that it's the Referendum you wish to cancel, _not_ always 249. That's just the example used.

Note that I am just referring to the _last_ sentence here, which also started with "To cancel a referendum". Reviewing it now, that can be removed and the last sentence changed to:

_You must specify the referenda.cancel extrinsic with the index equal to the Referendum you wish to cancel. In the screenshot below, the Referendum to be cancelled is 249."_

**Comment by DrW3RK** [comment]
Got it! Thanks Bill. Issues is now resolved. https://github.com/w3f/polkadot-wiki/commit/62c390b58e1a1c83eee52067210ecde015e6ab5e
