### ISSUE TITLE
Change KB links from Substrate.io to .dev

### ISSUE THREAD

**Issue by Swader** [w3f/polkadot-wiki#529]
https://www.substrate.io/kb/learn-substrate/tx-pool changes to substrate.dev/docs/en/knowledgebase/learn-substate/tx-pool

So a replace of `.io/kb` with `.dev/docs/en/knowledgebase` should do the trick. Do this after https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/pull/535 and
https://github.com/paritytech/substrate.io/pull/87 are merged.

**Comment by riusricardo** [comment]
#535 is merged. You can start updating and testing the links ;)
