### ISSUE TITLE
Plain text blocks are rendered as code blocks

### ISSUE THREAD

**Issue by dvdplm** [w3f/polkadot-wiki#534]
Code blocks content are rendered as source code by default and receive syntax highlighting. When the content is plain-text it looks odd with many "keywords" rendered in bold:

<img width="323" alt="image" src="https://user-images.githubusercontent.com/18515/83761994-53795100-a677-11ea-9332-d30dbc367f3e.png">

I noticed this [here](https://wiki.polkadot.network/docs/en/learn-keys#appendix-a-on-the-security-of-curves) but there are likely other places.

Possibly the fix is as easy as using ` ```text` instead of ` ``` `?

**Comment by Swader** [comment]
Thanks
