### ISSUE TITLE
[Feature Request] : add info about westmint testnet 

### ISSUE THREAD

**Issue by muddlebee** [w3f/polkadot-wiki#5341]
a section to explain what westmint testnet is about
https://wiki.polkadot.network/docs/maintain-networks#test-networks

we got few queries at discord.

**Comment by CrackTheCode016** [comment]
Working on adding a dedicated page for development networks in this PR #5332, will be sure to include this too :)

**Comment by filippoweb3** [comment]
@muddlebee see https://wiki.polkadot.network/docs/learn-guides-assets-create#creating-assets-on-the-asset-hub
Westmint is mentioned there. But yeah I agree it can be added in the maintain section as well.
