### ISSUE TITLE
Add Validator Monitoring Guide

### ISSUE THREAD

**Issue by wpank** [w3f/polkadot-wiki#536]
Add a validator guide on monitoring that covers:
- running prometheus
- setting up a grafana dashboard
- set up prometheus alerting

**Comment by FlorianFranzen** [comment]
Seems most of that is described now here: https://wiki.polkadot.network/docs/en/maintain-guides-how-to-monitor-your-node

**Comment by salmad3** [comment]
Yes, guide has been added as "Monitor your node". Seems like we can close this.
