### ISSUE TITLE
Add Validator Community Guides

### ISSUE THREAD

**Issue by wpank** [w3f/polkadot-wiki#537]
Add a page on how to build a community for a validator. Include things like:
- where to promote
- kinds of communication / communication channels
- how to engage with nominators

**Comment by salmad3** [comment]
@wpank we can address this if you'd like

**Comment by wpank** [comment]
@DannyS03 I actually have a draft of this page, can open a PR to start iterating on it

**Comment by salmad3** [comment]
> @DannyS03 I actually have a draft of this page, can open a PR to start iterating on it

Sounds good:)

**Comment by salmad3** [comment]
👊 page created
