### ISSUE TITLE
Add instructions for removing proxies

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#5383]
To this page - https://wiki.polkadot.network/docs/learn-proxies

It discusses how to add them but not how to remove them.

**Comment by filippoweb3** [comment]
@laboon At the end of the page there is a link to the JS guides

<img width="922" alt="Screenshot 2023-11-29 at 16 15 11" src="https://github.com/w3f/polkadot-wiki/assets/110459737/e87a4d4c-25b3-463a-ad0b-f2d5eb90ba59">

There you can find how to remove proxies (link to support)

https://wiki.polkadot.network/docs/learn-guides-accounts-proxy#removing-proxy-with-polkadot-js

**Comment by laboon** [comment]
We should at least say something like "In order to remove proxies, you will need to use Polkadot-JS" or similar text along with a link.
