### ISSUE TITLE
Add derivation path standards

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#5413]
This information belongs on the https://wiki.polkadot.network/docs/learn-account-advanced#derivation-paths page

You can get the text from Gav's Hackmd here: https://hackmd.io/@polkadot/rJ5nxXAHn

**Comment by Polkadot-Forum** [comment]
This issue has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/polkadot-standards-proposal-psp-to-define-hierarchical-deterministic-hd-key-derivation-paths/2941/6

**Comment by filippoweb3** [comment]
Isn't this just how Polkadot Vault handles Derivation? I would not add a section "standard derivation", but rather add a section about how vault/signer handles derivation. Would this be ok?

**Comment by josepot** [comment]
> Isn't this just how Polkadot Vault handles Derivation? I would not add a section "standard derivation", but rather add a section about how vault/signer handles derivation. Would this be ok?

I _think_ that it's actually how subkey and "polkadot-js apps" handle derivation. It's possible that Vault handles it the same way, but I'm not certain.

As someone who has been trying to learn about these things, I couldn't agree more with @laboon: this information definitely belongs into that section 💯 

### EDIT

The [document](https://hackmd.io/@polkadot/rJ5nxXAHn) starts with the following sentence:

> All paths as per `subkey` standard.

🙂
