### ISSUE TITLE
Update phala's about in the smart contract page and update missing doc link

### ISSUE THREAD

**Issue by ayomidebajo** [w3f/polkadot-wiki#5459]
The [Build smart contract's](https://wiki.polkadot.network/docs/build-smart-contracts#phala) page says "Phala is a privacy-preserving cloud compute platform and aims to provide strong guarantees of confidentiality as a cross-chain platform". AFAIK, Phala is more of an off-chain computing infrastructure.  The link to the docs on Phala network also returns a 404 page.

**Comment by CrackTheCode016** [comment]
closed in #5460

**Comment by ayomidebajo** [comment]
P.S This is my first contribution 😁
