### ISSUE TITLE
Add Polkassembly registrar (#5) to Kusama Registrar List

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#5483]
Page: https://guide.kusama.network/docs/learn-identity/#registrars

This is a result of [Ref 327](https://kusama.polkassembly.io/referenda/327).
 
F1wAMxpzvjWCpsnbUMamgKfqFM7LRvNdkcQ44STkeVbemEZ

Current fee is 0

**Comment by Sahillather002** [comment]
pls assign

**Comment by Sahillather002** [comment]
![image](https://github.com/w3f/polkadot-wiki/assets/72077931/85f33222-a637-4b6d-a641-affc85173e17)
It should be here na with registrar 5 : ?

**Comment by DrW3RK** [comment]
@Sahillather002 Thanks for the reminder. We usually self-assign in the team and the turnaround time for feature requests is about a day or two.

You are also free to create a Pull Request on the Wiki and we will review and merge it.
