### ISSUE TITLE
consts.staking.maxNominations is not fetching the correct value

### ISSUE THREAD

**Issue by muddlebee** [w3f/polkadot-wiki#5492]
![Screenshot 2024-01-10 052400](https://github.com/w3f/polkadot-wiki/assets/8139783/bc580d39-1d43-4af2-8fb6-ebedc456b710)

**Affected Pages**
https://wiki.polkadot.network/docs/learn-staking
https://wiki.polkadot.network/docs/learn-nominator

Note : Search for the keyword " [object Object] " the issue is affecting many pages.

**Comment by DrW3RK** [comment]
Thanks for bringing this to our notice. This seems to be a result of the planned changes to Staking pallet https://forum.polkadot.network/t/discussion-define-and-enable-dynamic-nomination-quota-curve-based-on-the-nominators-balance/4137

The number is now accessible as a runtime call

<img width="952" alt="image" src="https://github.com/w3f/polkadot-wiki/assets/86818441/ef19dc52-cbf2-4863-9ba3-6adbcb67a1bd">

<img width="893" alt="image" src="https://github.com/w3f/polkadot-wiki/assets/86818441/9e45a14b-3034-47e3-9a17-ef5f34f4dbdb">

Will make the necessary changes to the Wiki
