### ISSUE TITLE
Add Decentralized Futures to Grants program page

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#5505]
Add a link to either https://futures.web3.foundation/ or https://wiki.polkadot.network/docs/decentralized-futures to https://wiki.polkadot.network/docs/grants

**Comment by DrW3RK** [comment]
Perhaps, like an info note at the beginning of the Grants page funnelling them to decentralized futures page?

**Comment by laboon** [comment]
Something like that would be good - the DF program is much bigger than the Grants program, in general it would make more sense for people to look there first.
