### ISSUE TITLE
Explain lock start time better

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#5534]
Explain in OpenGov conviction ( https://wiki.polkadot.network/docs/learn-polkadot-opengov#voluntary-locking-conviction-voting ) that your votes will be locked until the end of the Referendum and the unlocking time starts after that. Note especially that even with no conviction, DOT/KSM will be locked until the Referendum ends.

**Comment by bluezdot** [comment]
How do I check the information (e.g: How long does it last?) about the Enactment period of an ongoing referendum?
