### ISSUE TITLE
Archive old Democracy pages

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#5637]
Pages like this: https://wiki.polkadot.network/docs/maintain-guides-democracy#with-a-ledger-hardware-wallet-or-unlocking-very-old-locks are confusing to users. 

The old Democracy pallet no longer exists in either the Polkadot or Kusama runtimes, so we  should  put very clear indications that they are no longer used (instead of saying "they will soon be archived".

**Comment by filippoweb3** [comment]
There are two articles I wrote, we can implement in the Wiki
- https://grillapp.net/@filippoweb3/polkadot-locks-explained-49678?ref=10124
- https://grillapp.net/@filippoweb3/polkadot-wallet-balances-explained-50416?ref=10124

What do you think?
