### ISSUE TITLE
Image to show how locks work

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#5659]
We should have an infographic showing how locks work that we can link people to.

Show how staking and governance locks (and vesting locks, etc.) are separate and can overlap. I recommend a glass of water with multiple lines.

**Comment by filippoweb3** [comment]
@laboon I could create a new "Locks" page explaining how locks work.
I did some previous work here
- https://grillapp.net/@filippoweb3/polkadot-wallet-balances-explained-50416
- https://grillapp.net/@filippoweb3/polkadot-locks-explained-49678
- https://grillapp.net/@filippoweb3/polkadot-open-gov-locks-explained-47939

**Comment by laboon** [comment]
Yes, something like this makes sense to me to add.
