### ISSUE TITLE
Use injector to keep code versions up-to-date

### ISSUE THREAD

**Issue by lsaether** [w3f/polkadot-wiki#566]
We should set up the injector to follow GitHub releases so that we can automatically update the latest versions in the guides without manually updating them every time (could happen multiple times a day at worst).

cc https://github.com/w3f/polkadot-wiki/pull/565

**Comment by Swader** [comment]
Needs closures in injector. Feature pending.

**Comment by lsaether** [comment]
Is this still a feature that's pending? I'll be able to create a script for this if it's something that is still a while in the making.

**Comment by Swader** [comment]
Yes, all of this is coming. Something with WSL and yarn is wrong on my end today, but once I fix it I'll finish this thing
