### ISSUE TITLE
"Grants Programme" should be "Grants Program"

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#5685]
https://wiki.polkadot.network/docs/grants

The Grants Program should be spelled without the "me" at the end

This might be in other places on the Wiki, please do a search-and-replace

The 1KV Programme is the only project currently using the British spelling. We are likely changing the name of that in the future too, though.

**Comment by takahser** [comment]
This also applies to the Decentralized Futures Program, see https://futures.web3.foundation/ and this screenshot:

<img width="904" alt="image" src="https://github.com/w3f/polkadot-wiki/assets/5393704/5ba379f7-c368-4eab-888c-1ef720faccdb">
