### ISSUE TITLE
Improve the Wiki Search Bar

### ISSUE THREAD

**Issue by krichard410** [w3f/polkadot-wiki#569]
When using the search bar on the wiki, there's always one search result that is concealed with pink. When hovered, the search result is visible, but it might be nice not having to hover to see a search result. 

<img width="656" alt="Screen Shot 2020-06-15 at 8 13 18 AM" src="https://user-images.githubusercontent.com/36748441/84651514-7827c100-aee0-11ea-9f3c-0a429a081c5a.png">

<img width="653" alt="Screen Shot 2020-06-15 at 8 13 48 AM" src="https://user-images.githubusercontent.com/36748441/84651613-a0afbb00-aee0-11ea-89d3-24b385412e4d.png">

(hovered over text):
<img width="673" alt="Screen Shot 2020-06-15 at 8 19 39 AM" src="https://user-images.githubusercontent.com/36748441/84651869-01d78e80-aee1-11ea-9468-0d8e3a22a282.png">

**Comment by Swader** [comment]
This is new. I believe this might be due to @lsaether styling the "Kusama" link?
