### ISSUE TITLE
Update Treasury page

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#5701]
https://wiki.polkadot.network/docs/learn-guides-treasury#creating-a-treasury-proposal

As with all Polkadot-JS pages, we should add the banner indicating Polkadot-JS App is for developers/experienced only.

We should make a Support page on how to do TPs via Polkassembly.

**Comment by x676f64** [comment]
I recommend that page instead guides people on how to do it with PA and create a separate page for advanced mode/using dotapps.io.
