### ISSUE TITLE
Remove DotScanner

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#5706]
Dotscanner.com has shut down - 

_Unfortunately, due to rising costs of the servers, databases, and bot fighting matched with the ever changing and tedious hoops I've had to jump through to get the funding from the community every few months I have decided to eat my losses and shutdown the service._

We reference it here - https://wiki.polkadot.network/docs/build-tools-index#block-explorers (along with Polkascan) - and should remove it.

**Comment by filippoweb3** [comment]
@laboon we removed Polkascan, it seems Dotscanner was not even mentioned in the Wiki
