### ISSUE TITLE
There are 2 links to archived repo's wiki

### ISSUE THREAD

**Issue by gui1117** [w3f/polkadot-wiki#5742]
There is 2 links to archived repo's wiki
```
./docs/build/build-parachains.md:375:[SS58 encoding](<https://github.com/paritytech/substrate/wiki/External-Address-Format-(SS58)>) for
./docs/learn/archive/learn-governance.md:523:- [Initial Governance Description](https://github.com/paritytech/polkadot/wiki/Governance)
```

I don't know if those wiki has been moved somewhere.

**Comment by filippoweb3** [comment]
The link https://github.com/paritytech/polkadot/wiki/Governance still provides information about Gov1. The link https://github.com/paritytech/substrate/wiki/External-Address-Format-(SS58) has been replaced with one that is working
