### ISSUE TITLE
Add more to the News Page

### ISSUE THREAD

**Issue by krichard410** [w3f/polkadot-wiki#575]
I noticed that the [News page](https://wiki.polkadot.network/docs/en/news) didn't have much links there, maybe we could link the Polkadot Medium blog or even the twitter page? Or perhaps the News page could go underneath the [Community page](https://wiki.polkadot.network/docs/en/community) as a sub section?

**Comment by laboon** [comment]
You can include links to the /r/DOT subreddit, W3F blog, Research page, our Medium, Gav's Medium, DOT Leap, maybe ask in the Tech Ed channel if others have ideas?
