### ISSUE TITLE
Issue with the max number of nominators in the electing set

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#5777]
"Due to the current runtime constraints, Polkadot can only handle [object Object] nominators comfortably in the [electing set](https://wiki.polkadot.network/docs/learn-nominator#staking-election-stages)."

https://wiki.polkadot.network/docs/learn-nomination-pools

**Comment by DrW3RK** [comment]
The restrictions were lifted https://forum.polkadot.network/t/next-revision-of-increasing-nomination-pool-limits/2498/13?u=radha Will update the Wiki accordingly.

**Comment by laboon** [comment]
@DrW3RK That's for the number of nomination pools / nomination pool members, not the the number of nominators themselves.
