### ISSUE TITLE
Sidebar subsection structure proposal

### ISSUE THREAD

**Issue by Swader** [w3f/polkadot-wiki#58]
Here's a proposal for restructuring the wiki's sidebar.

### Current

- DOT
- Polkadot Runtime Environment (PRE)
- Polkadot UI
- Architecture
- Parachain Slots Auction
- Basics
- Bridges
- Polkadot vs. Cosmos: Design Comparison
- Polkadot comparisons
- Polkadot Consensus
- Cryptography Explainer
- Frequently Asked Questions (FAQs)
- Governance
- GRANDPA
- Polkadot Implementations
- Learn about Polkadot
- Interchain Message Passing (ICMP)
- Polkadot
- Polkadot Keys
- Parachains
- Parathreads
- What is Phragmen and what does it mean for node operators?
- Randomness
- Links
- Roadmap
- Security of the network
- SPREE
- Staking
- Treasury
- WebAssembly (Wasm)

### Proposed

- Basics _(remove current basics page altogether)_
  - Polkadot _(append "Learn about Polkadot")_
  - Architecture
  - Security of the Network
  - Consensus (merge with GRANDPA page)
  - Governance
  - Bridges
  - Parachains
  - Parathreads
  - Polkadot Runtime Environment (PRE)
  - Treasury
- Advanced
  - Staking
  - Randomness
  - SPREE
  - WASM
  - What is Phragmen and what does it mean for node operators?
  - Interchain Message Passing (ICMP)
- Cryptography
  - Cryptography in Polkadot _(Cryptography Explainer)_
  - Polkadot Keys
- Polkadot Comparisons
  - Polkadot vs. Cosmos
  - Polkadot vs. Ethereum _(will be external link to my post published elsewhere)_
  - Polkadot vs. Tezos _(split from current Comparisons page)_
- Economics
  - DOT
  - Parachain Slots Auction
- Implementations
  - Runtime Clients _(renamed from current Implementations page)_
  - Web3 Tools (browsers, wallets)
  - Polkadot UI
  - Developer Tools _(github repos of interesting projects)_
- Misc
  - Roadmap
  - Links
  - FAQ

Probably warrants some reordering in individual subsections to keep the learning flow intact and more aggressive cross-linking across pages, but should read better if following things in sequence.

**Comment by lsaether** [comment]
To me this looks sensible and a lot better than what we have now. 

The only subsection that sticks out to me may be better moved to the build section is Implementations, since we will be maintaining a list of developer tools already in build.

**Comment by Swader** [comment]
+1
 I will prepare a PR for this structure as soon as I've gone through Build and Maintain.

**Comment by lsaether** [comment]
Closing as this was merged in #77
