### ISSUE TITLE
Update Identity Page for Polkadot Amounts

### ISSUE THREAD

**Issue by wpank** [w3f/polkadot-wiki#582]
Right now the identity page lists some ksm amounts for setting an identity. 

> Users can register some default fields like legal name, display name, website, Twitter handle, Riot handle, etc. along with extra, custom fields for which they would like attestations (see Judgements). Users must reserve funds in a bond to store their information on chain - 10 KSM per identity, and 2.5 KSM per each field beyond the legal name. These funds are locked, not spent - they are returned when the identity is cleared. Each field can store up to 32 bytes of information, so the data must be less than that. When inputting the data manually through the Extrinsics UI, a UTF8 to bytes converter can help.

These amounts have changed since then, but it should also be added what the costs in DOTs are.

**Comment by Swader** [comment]
#1926 will handle this.
