### ISSUE TITLE
[Feature Request] Move async backing docs to `polkadot-sdk-docs`

### ISSUE THREAD

**Issue by kianenigma** [w3f/polkadot-wiki#5835]
as per discussed with @DrW3RK, since it is full of code snippets and it is easier to maintain it in `polkadot-sdk`, assuming there is one correct example of each snippet in that repo, which I believe it is.

**Comment by DrW3RK** [comment]
Sure. PR in progress already https://github.com/DrW3RK/polkadot-sdk/pull/1
