### ISSUE TITLE
[Feature Request] Clarifying that accounts with locked or staked DOT won't get reaped if free balance is under 1.1 DOT

### ISSUE THREAD

**Issue by sacha-l** [w3f/polkadot-wiki#5836]
I wanted to make sure that an account won't get reaped if it has DOT locked in staking. So I did a quick search and landed on this page: https://support.polkadot.network/support/solutions/articles/65000168651-what-is-the-existential-deposit-

For example, I have an account with 1.14 free balance and 42 DOT locked in staking. I want to send 1 DOT to another account which will result in my account having a free balance of 0.14. Nothing in the support resource inspired confidence that my account won't get reaped. Then I went here: https://wiki.polkadot.network/docs/build-protocol-info#free-vs-reserved-vs-locked-vs-vesting-balance

And IIUC it confirmed that because free balance is an abstraction over locked or reserved balance, then it should in theory not get reaped. Right? The language is quite technical though, I think the page would benefit from a clearer outline of what users need to know, straight to the point.

**Comment by filippoweb3** [comment]
#5659
