### ISSUE TITLE
[Feature Request] : add metadata explorer for other system parachains

### ISSUE THREAD

**Issue by muddlebee** [w3f/polkadot-wiki#5917]
![image](https://github.com/w3f/polkadot-wiki/assets/8139783/3fbb3631-4db6-40a1-99fb-773f049ccd56)

can add for Coretime, People, BridgeHub

https://wiki.polkadot.network/docs/metadata

**Comment by filippoweb3** [comment]
Done with https://github.com/w3f/polkadot-wiki/pull/6148
