### ISSUE TITLE
[BUG] The how to guide reports a 404

### ISSUE THREAD

**Issue by erik78se** [w3f/polkadot-wiki#6010]
The how-to-guide to Kusama Treasury is a broken link. See attached image.

On this page:
https://guide.kusama.network/docs/learn-polkadot-opengov-treasury/

In the green info box.

![image](https://github.com/w3f/polkadot-wiki/assets/850603/06e42ddb-26d5-4b06-9d66-adeb3181c7c2)

**Comment by filippoweb3** [comment]
the link seems to work for https://wiki.polkadot.network/docs/learn-polkadot-opengov-treasury
Might be a Docusaurus issue since we are not running the latest version

**Comment by filippoweb3** [comment]
found the bug, and now it should work. Lmk, in case, feel free to close the issue.

**Comment by erik78se** [comment]
> found the bug, and now it should work. Lmk, in case, feel free to close the issue.

I can confirm that the fix works. Closing the issue.
