### ISSUE TITLE
Switching Order of Build and Learn

### ISSUE THREAD

**Issue by krichard410** [w3f/polkadot-wiki#626]
I'm thinking switching the order of 'Build' and 'Learn' might make more sense to a new user, like first it's required you learn the material, then build with it, then maintain it? 

<img width="299" alt="learn-polkadot" src="https://user-images.githubusercontent.com/36748441/85961116-882eae80-b97e-11ea-8a63-546f38116f3e.png">

It might too be an interesting idea to have a 'Getting Started' tab underneath 'Learn' where it would suggest possible ways to get started on Polkadot (for example, is it best to start with making an account or watching a TechEd Explainer video on getting to know the UI or even going through the Web3 MOOC course?).

**Comment by Swader** [comment]
Sounds good to me, I always felt like learn should be first. Keep in mind that the homepage header buttons also have a similar order which will need to be modified.

Feel free to push a suggestion PR for that getting started page, we do need a basic guide for people to land on, yes.
