### ISSUE TITLE
Moving Account generation and restoring accounts

### ISSUE THREAD

**Issue by krichard410** [w3f/polkadot-wiki#627]
I think it would make more sense if 'Account Generation' and 'Backing up/Restoring Accounts' were placed somewhere else than inside Miscellaneous, perhaps underneath Build? Somewhere easier for users to find in the side bar. 

<img width="286" alt="Screen Shot 2020-06-29 at 12 01 38 AM" src="https://user-images.githubusercontent.com/36748441/85968581-d7cfa300-b99b-11ea-9684-89a8afc1a0ec.png">

**Comment by Swader** [comment]
I would go as far as advocating for another category besides learn, build and maintain. Something like "Getting Started" which could contain both extremely simple explanations and guides for basic things like these. @laboon @lsaether @ansonla3 thoughts?

**Comment by lsaether** [comment]
"Getting Started" could also go under the Main heading (which currently doesn't have much visibility either). If we add another header button I would probably suggest we add "Main".

**Comment by Swader** [comment]
Not sure how I feel about "Main". Indicates that something else is less important? Or is that just me? How about "General"?
