### ISSUE TITLE
Create a Polkadot vs Kusama Comparison Page

### ISSUE THREAD

**Issue by krichard410** [w3f/polkadot-wiki#628]
I'm thinking it might be helpful for users to see a page full of differences/similarities between Kusama and Polkadot (for example, which network might be better suited for them, how many validators on each, what they have in common, etc.). It could be placed within 'Polkadot Comparisons'.

<img width="262" alt="Screen Shot 2020-06-29 at 8 06 58 AM" src="https://user-images.githubusercontent.com/36748441/85997336-c14b3b00-b9df-11ea-9257-4c64db02d12c.png">

This article sums up quite a bit between the two: https://medium.com/polkadot-network/kusama-polkadot-comparing-the-cousins-170e4fe6c280

**Comment by Swader** [comment]
The on-chain values might prove difficult to keep in sync (i,e. changing validator numbers on either means updating this page, which is prone to go out of date quickly), so we should use the #348 Injector for this or avoid being verbose with such values. A general comparison intro page is fine, but I don't think there's a need to go into any more detail than what those articles and videos we have on this topic already cover (maybe link to them on this page). What might be interesting though is documenting a difference between the runtimes - which modules are in which chain for example. That's also a manual process, but much more useful than value comparison page imo.

**Comment by krichard410** [comment]
@Swader where can i find more info on the difference between runtimes?

**Comment by Swader** [comment]
Easiest is to look at the source code of each runtime to see which dependencies get activated by which chain genesis
The source code here might be useful: https://github.com/paritytech/polkadot/blob/3b0934cfe9443660a56d272663d3b4859d9d2dcb/service/src/chain_spec.rs#L288

**Comment by TomaszWaszczyk** [comment]
What are differences, requirements to become parachain of Kusama and Polkadot?

**Comment by laboon** [comment]
It's the same process and requirements on both networks. 

In the future, if you think there is missing data from the wiki, please add a new issue.  Thanks!
