### ISSUE TITLE
PDF Downloads

### ISSUE THREAD

**Issue by lsaether** [w3f/polkadot-wiki#63]
We should enable PDF download so that people can have an offline way to read the content.

**Comment by Swader** [comment]
I looked into this, and the only package currently capable of doing this is docusaurus-pdf but it [does not support custom styling](https://github.com/KohheePeace/docusaurus-pdf/issues/8).

Another possible approach is [pandoc](https://pandoc.org/demos.html). Here is an example implementation via Travis I found: [1](https://github.com/sourabh2311/MuftEducation.in/blob/master/.travis.yml), [2](https://github.com/sourabh2311/MuftEducation.in/tree/master/travis), [3](https://github.com/sourabh2311/MuftEducation.in/blob/master/requirements.txt) but I don't think this would respect styling.

I think we better just generate from HTML, experimenting with that next: https://github.com/alextiley/convert-html-to-pdf

**Comment by lsaether** [comment]
Let me know how it goes. I don't think we really need too much styling though, as long as we can have proper headings and italics. Maybe even using a markdown -> pdf converter would work but would require us to integrate it into the build process.
