### ISSUE TITLE
Vesting link out of date

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#632]
In this section of the page, the 'Vesting' link leads to an old pallet and 404's - please update

https://wiki.polkadot.network/docs/en/build-protocol-info#free-vs-reserved-vs-locked-vs-vesting-balance

It currently goes to https://substrate.dev/rustdocs/master/pallet_vesting/index.html

I would guess it should go here: https://substrate.dev/rustdocs/v2.0.0-rc4/pallet_vesting/struct.Vesting.html

or maybe

https://github.com/paritytech/substrate/blob/master/frame/vesting/src/lib.rs

or both?

**Comment by semuelle** [comment]
There is no more `Vesting` struct since [this commit](https://github.com/paritytech/substrate/pull/8440), so `v3.0.0/pallet_vesting/struct.Vesting.html` links work, but all the `latest/pallet_vesting/struct.Vesting.html` 404 now.
