### ISSUE TITLE
broken link to OpenGov

### ISSUE THREAD

**Issue by Retamogordo** [w3f/polkadot-wiki#6336]
An archived article on https://wiki.polkadot.network/docs/learn/learn-governance#endorsing-proposals suggests redirecting to
https://wiki.polkadot.network/learn/learn-polkadot-opengov.md
However this page doesn't exist.

**Comment by filippoweb3** [comment]
issue should be fixed @Retamogordo, thanks for flagging and do not hesitate to report more stuff :)
