### ISSUE TITLE
Sending a transfer

### ISSUE THREAD

**Issue by lsaether** [w3f/polkadot-wiki#638]
We should have a section instructing users how to send a transfer using Polkadot-JS Apps.

**Comment by Swader** [comment]
Why? Isn't it intuitive? There are glaring Send buttons everywhere. Maybe we could expand the scope of this section / page to include programmatic sending as well along with fee estimation? Though that is kind of covered in the implementors guide.

**Comment by krichard410** [comment]
This might be useful to include in the 'getting started' page, once you've made an account.

**Comment by lsaether** [comment]
It's intuitive if you've used blockchain applications in the past but if someone is a complete newbie, it may not be. In which case, it would be helpful to have this available. It was also requested by Ledger along with a "check your balance" section that I've included in the [draft Ledger guide](https://github.com/w3f/polkadot-wiki/pull/572/files#diff-acfe4c9136c9a09609d93e8d256ac56bR144).

@krichard410 Yes I think this would go perfectly as part of the getting started page. I would rather have it there than on the Ledger guide; we'll just link to it.

**Comment by krichard410** [comment]
Perfect! I'll get started on that page then and include it in the getting started page

**Comment by wpank** [comment]
Tangential, but also would be good to perhaps include a section on making transfers with the polkadot js api.

Also how to do transfers with a multisig.
