### ISSUE TITLE
Build Examples page

### ISSUE THREAD

**Issue by Swader** [w3f/polkadot-wiki#648]
Imo the time has arrived to prune the wiki a bit. There's too much info for us to keep up to date easily, and we're being unnecessarily verbose with some of the content when it could be merged and better structured.

As an example, the build-examples-index page is outdated and could use a refresh. I'm not sure if it's worth maintaining with Polkaproject and Kusamaproject being out there as well as our Grants list page. Just linking to those three may be enough, but those three links we could put into any other page as well, like the builders guide landing page, and just remove this examples page.

Thoughts @laboon @lsaether @krichard410 @ansonla3?

**Comment by krichard410** [comment]
I personally like that idea @Swader, I think placing those examples/resources as part of the builders guide landing page makes sense plus it would save time on consistent maintenance. I'm just wondering if that'd be easier or harder to find these examples if they were moved to the landing page? What's your opinion on if 'Examples' was renamed to something along the lines of 'Polkadot Project Ideas', that way it's more specific?

**Comment by Swader** [comment]
Having thought further about it I'm a bit conflicted on recommending third party lists, even if they were funded by the Kusama treasury like kusamaproject.com was.

Perhaps a dirty but effective trick would be to have a crawler put links from all three of those pages into our examples page on build. That way we keep it on-page but up to date.

**Comment by Swader** [comment]
Resources to consume:

- [Polkaproject list](https://api.staked.xyz/apiPolka/getPolkaList?limit=171&tagID=0&page=0)
- [Polkaproject categories](https://api.staked.xyz/apiPolka/getCategory)
- [Kusamaproject list](https://kusamaproject.com/data/posts-manifest.js)

These can be fetched by a script during build time, processed, and turned into a nice list on the examples page. Checking how doable that is now.

**Comment by krichard410** [comment]
@Swader Do you think that crawler could update the [Relevant Links page](https://wiki.polkadot.network/docs/en/learn-relevant-links) with up to date Crowdcast webinars?

**Comment by Swader** [comment]
No, we have no categories on CC so it would grab everything, it would be hard to filter them for relevant videos.

**Comment by lsaether** [comment]
Closing since the scope is the same as #661
