### ISSUE TITLE
Revert kusama homepage

### ISSUE THREAD

**Issue by Swader** [w3f/polkadot-wiki#656]
We should carefully revert #619, due to design team's lack of sign-off.

**Comment by krichard410** [comment]
@Swader what should the reverted homepage look like?

**Comment by Swader** [comment]
I don't know tbh. @iggyweb3?

**Comment by lsaether** [comment]
So I'm not sure what to do about this - reverting the homepage would basically removing the homepage.

Can we close this until we have an alternative design?

**Comment by Swader** [comment]
I vote yes

**Comment by krichard410** [comment]
I'm going to close this for now, I've mentioned this to Iggy and he has it written down in the Design notion document
