### ISSUE TITLE
Build Crawler for `Teams Building on Polkadot` + `Examples` Page

### ISSUE THREAD

**Issue by krichard410** [w3f/polkadot-wiki#661]
On this page [here](https://wiki.polkadot.network/docs/en/community), the link at the bottom, "Teams Building on Polkadot" leads to a list created in January 2019. I'm thinking it might be a good idea to create a separate page on the Polkadot Wiki underneath General that holds an updated list of teams building on Polkadot or link it to a list that is more up to date.

**Comment by Swader** [comment]
Somewhat related to #663 and Polkaproject and Kusamaproject as third party websites. I still think crawling those sites and putting their links in here automatically would be best to keep things up to date.

**Comment by krichard410** [comment]
@Swader is there a crawler already created for web3 that I could take a look at? Or does the crawler need to be built?

**Comment by Swader** [comment]
It would have to be built. I can take a stab at it, I've built a few hundred crawlers during my time at Diffbot.

**Comment by lsaether** [comment]
So as far as I can tell, this issue and #648 really have the same scope of work: building a crawler / scrape script that can auto-populate the `Teams` and `Examples` pages.

Reposting the list of resources to consume from [Bruno's comment](https://github.com/w3f/polkadot-wiki/issues/648#issuecomment-655751203):

- [Polkaproject list](https://api.staked.xyz/apiPolka/getPolkaList?limit=171&tagID=0&page=0)
- [Polkaproject categories](https://api.staked.xyz/apiPolka/getCategory)
- [Kusamaproject list](https://kusamaproject.com/data/posts-manifest.js)

@Swader Is this something you want to work on solo or is it something we should work on together?

**Comment by Swader** [comment]
We can team up on it, sure, or if you want to take it I can focus on the injector
