### ISSUE TITLE
Kusama Guide's search leads to Polkadot wiki

### ISSUE THREAD

**Issue by Swader** [w3f/polkadot-wiki#675]
Solution is to add a separate search for kusama wiki, which will need a separate API code from Algolia, unless we've got one from before. @fgimenez do you know perhaps?

**Comment by fgimenez** [comment]
No idea sorry

**Comment by Swader** [comment]
I dug through the old source code and it looks like it was just mkdocs with a build index on build, local search. So we'll have to request a new key. Doing that now.
