### ISSUE TITLE
Explain the validator limit

### ISSUE THREAD

**Issue by Swader** [w3f/polkadot-wiki#68]
The validator number being thrown around is 1000. This warrants some explaining due to Ethereum aiming for up to 250000 validators and also using BLS aggregation (though I understand Polkadot keys are not BLS yet). 

The validator count is one people really sink their teeth into when speaking about decentralization, and most will not look into Phragmen and the rebalancing that's going on there.

I do know both projects are basically guesstimating, but in our tests on Nimbus we've easily surpassed 1000 validators on non-local machines in our Nimbus-only testnet, over Libp2p. Granted, no data, just empty blocks being gossiped and justified/finalized, but still. 

I understand that no one knows how much our limit will actually end up being when data comes into play and the network is saturated with gossiping collators and validators, but in light of Ethereum advertising numbers 2 orders of magnitude higher, we should at least explain that this is a guess and a conservative estimate and that we absolutely hope / expect that number to go way higher, unless this is not the case.

Thoughts?

**Comment by lsaether** [comment]
I think this requires more research into assumptions both projects are making for their estimations, state of the different software implementations, test case and test environments, and economic design differences between the two networks (i.e. NPoS vs. Serenity PoS). Also, would be curious if the estimated number of validators has changed with the recent sharding proposals for serenity or if the new design has no bearing on this aspect.

As far as the Polkadot estimation of 1000 validators, I agree it may be conservative but we should also keep in mind it's much higher than any live proof-of-stake network can boast (almost a full order of magnitude more). So I think we should continue to err on conservative estimates until we have better data.

**Comment by Swader** [comment]
No info yet on specifics re validator count / new shard count, but by all estimations unchanged. There is discussion about raising the staking limit so fewer validators are needed to lock up more ether, but it's meeting resistance from community which grew used to the 32 eth number.

How can we get this research started, and where can I best help? Let's get something rolling, this comparison will come up a lot in the near future and it's best if we have specifics to throw around.

**Comment by lsaether** [comment]
I think we could expand on this point in the [Eth2.0 comparison](https://wiki.polkadot.network/docs/en/learn-comparisons#ethereum-20) section, with the goal of having a full page of Eth2.0 comparison points like we have for Cosmos. Let's try to keep to technical comparison as much as possible with how things are implemented or how the design is specified.

Let's not get too caught up on this point at the time, but I think writing more on the economic difference between NPoS and Serenity PoS is helpful as the two approaches dictate a bit why there is such a large difference between the two project's communicated validator count.

**Comment by Swader** [comment]
I was going to render that section mostly obsolete with my polkadot for ethereans post. Should it instead be linked to from that section, and that section kept as is?

**Comment by lsaether** [comment]
We can either put an external link in the sidebar linking to the post for the "Ethereum" comparison underneath the Cosmos one and delete the section or work the post back into its own wiki page. Either way we need to beef up that section some way.

Which do you think is better?

**Comment by Swader** [comment]
I want to publish the post on Bitfalls.com, I can get bigger reach there than with a wiki post, harder to share on social media. Since it'll be external, I can make an abridged version which only briefly covers the differences (as the post is extensive) and that can be the wiki page. Thoughts?

**Comment by lsaether** [comment]
Sounds fine.

**Comment by lsaether** [comment]
closed in #365
