### ISSUE TITLE
Parathreads, parachains, and local tokens

### ISSUE THREAD

**Issue by Swader** [w3f/polkadot-wiki#69]
_Assuming a parathread has its own local token system, it pays the collators from the transaction fees in its local token. If the parathread does not implement a local token, then it can use DOTs_

As mentioned in #66 the local economy and related aspects of chain/thread need to be clarified. The second sentence seems restrictive, given that a thread and become a chain and vice versa - what happens to this condition then? Shouldn't this choice be entirely up to the chain/thread developer? So...

- thread: _should_ use local token to reward collators. _Can_ use DOT if not using local tokens.
- chain: _should_ use DOTs for everything. _Can_ use local tokens.

Is the above accurate? That's the impression I'm getting from the wording above.

---

 _Collators may be paid in local parathread currency. However, the relay chain transacts with the Polkadot universal currency (DOT) only. Collators must then submit block candidates with an associated bid in DOT. This means that if the parathread offers a local currency, the collator will need to understand the exchange rate between this currency and DOT in order to place a proper DOT bid on the relay chain and ensure that they make a profit._

So collators of chains vs collators of threads differ in implementation. Where collators of chain pass data to the validator who then submits a block, collators of threads build and submit a block themselves and then submit it for block inclusion via the block bid. This difference in collator should be specified somewhere more concretely, and whether or not this will be implemented in Cumulus by default or if one will need a different PDK for thread projects.

**Comment by keorn** [comment]
It will be up to the chain/thread developer what token they use, relay chain is agnostic to particular mechanics/incentivisation.

> So collators of chains vs collators of threads differ in implementation.

Yes, but ideally PDKs will allow easy switch.

> This difference in collator should be specified somewhere more concretely, and whether or not this will be implemented in Cumulus by default or if one will need a different PDK for thread projects.

The aim is to have Cumulus and some other PDKs support both, but that is after initial chain-only version is done. Precise difference will be also finalized only with implementation of Cumulus.

**Comment by lsaether** [comment]
> Is the above accurate? That's the impression I'm getting from the wording above.

Not quite,

- thread:  _must_ make incentive to collators using one of possible options including local currency, DOT, or some other incentive (vague and undefined and still need to be thought up).
- chain: does not need to make incentive for collators for inclusion of their blocks (they have already acquired a full parachain slot), but _can_ implement arbitrary logic including local currencies or using (para-)DOT for something.

**Comment by lsaether** [comment]
Part of #38

**Comment by Swader** [comment]
> > Is the above accurate? That's the impression I'm getting from the wording above.
> 
> Not quite,
> 
> * thread:  _must_ make incentive to collators using one of possible options including local currency, **DOT**, or some other incentive (vague and undefined and still need to be thought up).
> * chain: does not need to make incentive for collators for inclusion of their blocks (they have already acquired a full parachain slot), but _can_ implement arbitrary logic including local currencies or using (para-)DOT for something.

Does the DOT in the "thread" line mean para-DOT also?

**Comment by lsaether** [comment]
Yeah I'm using DOT as shorthand for wrapped-DOT, para-DOT, synthetic-DOT, and so on. Collators can be paid in whatever currency they are willing to accept, or none if they are okay with footing the bill for block production.
