### ISSUE TITLE
Add DNSLink to the built IPFS hosted sites

### ISSUE THREAD

**Issue by lsaether** [w3f/polkadot-wiki#696]
See #369 for context.

The sites are already hosted on IPFS and built on pushes to master using the GitHub actions. The actions spit out a hash at the end of their deployment. We need to set up DNSLink to point to the hashes every time the site is re-built.

**Comment by jakehemmerle** [comment]
We could also use IPNS with DNSLink for this (as that might be easier to use than using the Cloudflare API and updating the TXT record for DNSLink for CICD)

**Comment by jakehemmerle** [comment]
checkout  #2338
