### ISSUE TITLE
Explain what happens to parachain slots when number of validators dramatically drops

### ISSUE THREAD

**Issue by Swader** [w3f/polkadot-wiki#70]
If the goal is to have 5 validators per parachain slot, then what happens when number of validators decreases suddenly and some chains end up with a single validator responsible for them? How is such a scenario mitigated? Would there ever be purposeful skipping of a slot to normalize things? Say out of 100 validators 81 have stupidly hosted on AWS. Now the 20 parachain slots have 19 validators between them because AWS went down. What happens?

**Comment by lsaether** [comment]
Should be added to a FAQ.

**Comment by Swader** [comment]
Sure, but what's the answer? :D
