### ISSUE TITLE
Adding more details to Polkadot's explanation

### ISSUE THREAD

**Issue by krichard410** [w3f/polkadot-wiki#704]
I think users would find it helpful if there were more details on the [Polkadot explanation page](https://wiki.polkadot.network/docs/en/learn-introduction), specifically answering: What issues or problems is Polkadot solving, The importance of Polkadot, How it will impact the future, Why you should consider using Polkadot, etc. 
I think answering more of these kinds of questions will help a new non-technical user understand the purpose of Polkadot and what needs they might have for this network (that they could've not have known before).

**Comment by Swader** [comment]
Agreed
