### ISSUE TITLE
Create ease of access for current and upcoming events

### ISSUE THREAD

**Issue by krichard410** [w3f/polkadot-wiki#707]
I'm finding it difficult to navigate through the wiki in search of new webinars, updates, articles, etc. between the [Roadmap page](https://wiki.polkadot.network/docs/en/learn-roadmap) and the [Links page](https://wiki.polkadot.network/docs/en/learn-relevant-links) under the Miscellaneous tab. 

Proposed Idea: Combine the two pages together and list it under the General tab in the sidebar, or create a section on the wiki landing page that reads "What's new" (something like that) and is linked to these two pages. It could even hold an interactive calendar that lists events/articles/webinars for the current month?

Update: We could even merge the Roadmap page within the [Polkadot explanation page](https://wiki.polkadot.network/docs/en/learn-introduction), perhaps as another section? And place the Links page underneath General, so that it's easier to find?

**Comment by Swader** [comment]
I guess it depends on what you want from it - do you want upcoming stuff, or recently published stuff? Do you want to filter by category, type of content? All these requirements quickly make a new mess, a too busy page: a calendar and then all the links would be too much, but a calendar on its own sounds interesting and should probably be discussed with Dan, Urban, and co. 

I'm in favor of merging pages and reducing count, but we need to be careful to no create boring behemoths no one will want to read and that will just make our bounce rate go up.

Maybe bring it up in the growth + teched room, link to this issue?

**Comment by lsaether** [comment]
Agree with @Swader 

A calendar would be cool, but it's probably something that the community team is better at keeping maintained. I'm not sure it needs to live on the wiki - it could be a public Google Calendar or a Notion calendar - then we can embed it into a wiki page or just put an external link.
