### ISSUE TITLE
Validators are storage-rich because they need to keep state of ALL chains

### ISSUE THREAD

**Issue by Swader** [w3f/polkadot-wiki#71]
The validator hardware requirements need to be updated to say that while an average CPU will be fine, an average disk will not be, nor will an average internet connection probably. People are expected to need 1TB SSDs fairly quickly given that all validators need to sync all parachains at all times, due to not knowing which chains they are being assigned to ahead of time.

**Comment by lsaether** [comment]
Validator will not be keeping state of all chains (unless they want to).
