### ISSUE TITLE
Phragmen storage bloat and equalization clarification

### ISSUE THREAD

**Issue by Swader** [w3f/polkadot-wiki#72]
If 16 validators can be nominated by a nominator, and the table of stakes per validator for each nominator is stored on chain and rebalanced every Phragmen run, this makes it seem like we'll be writing _a lot_ of arbitrary data regularly. 

**What are the storage implications, has any research been done?** Can offline workers help? Run phragmen locally, commit just a hash, gossip table and hash with other nodes?

Further, Phragmen needs an offline simulation runner to be able to present people with a solution to a question like this:

Given only 2 slots, and validators of such setup:

- A: 0 own stake, 50 DOT from N1, 50 DOT from N2
- B: 25 own stake, 50 DOT from N1, 10 DOT from N2, 15 DOT from N3
- C: 105 own stake, 0 DOT from nominators
-  D: 100 own stake, 0 DOT form nominators

Which two validators end up being in the slots? C is obvious (hopefully) but who is the second?

**Comment by Swader** [comment]
Additionally, in `learn-staking`:

> For each validator pool, we keep a list of nominators with the associated stakes.

If this is stored on-chain, the storage bloat of a shifting set needs to be addressed.

**Comment by ansonla3** [comment]
@kian has written the [offline-phragmen](https://github.com/kianenigma/offline-phragmen) script to simulate the result.

**Comment by lsaether** [comment]
More info: https://github.com/paritytech/substrate/pull/4517

**Comment by lsaether** [comment]
@Swader would you say this is resolved now with #247 and #419 ? Please re-open if no.

**Comment by Swader** [comment]
Yes, but our phragmen doc is out of date now as it's no longer sequential phragmen, but edge-reduce phragmen. Opened #443 for that.
