### ISSUE TITLE
Update the Parachain implementers guide

### ISSUE THREAD

**Issue by krichard410** [w3f/polkadot-wiki#737]
On this page [here](https://wiki.polkadot.network/docs/en/learn-implementers-guide), I think this section should be placed underneath the Build tag, (along with https://wiki.polkadot.network/docs/en/build-pdk) to keep the parachain material in one place. It might also be helpful for users to place a "Further reading" or a "Extra Resources" section on this page that links to articles and videos on parachains. 
I also noticed the link on this page (https://github.com/paritytech/polkadot/tree/master/roadmap/implementors-guide) leads to a 404 page.

**Comment by krichard410** [comment]
I suppose this issue also somewhat relates to this one: https://github.com/w3f/polkadot-wiki/issues/38
Maybe the two could be incorporated together?

**Comment by Swader** [comment]
Go for it

**Comment by krichard410** [comment]
Hm I'm having trouble finding the link to the repo https://github.com/paritytech/polkadot/tree/master/roadmap/implementors-guide on parity's github. Anyone know where this is located?

**Comment by Swader** [comment]
https://github.com/paritytech/polkadot/tree/master/roadmap/implementers-guide

**Comment by Swader** [comment]
Spelling in URL

https://github.com/paritytech/polkadot/tree/master/roadmap/implementers-guide
