### ISSUE TITLE
Validator anonimity

### ISSUE THREAD

**Issue by Swader** [w3f/polkadot-wiki#74]
Is there any official mention somewhere about validator anonymity or research being done I could look at? 

There is an [answer by gav](https://www.reddit.com/r/dot/comments/bcqrx9/answered_by_gav_can_i_run_multiple_validators/) saying that dos resistance is up to the validator / collator. Seems a little discouraging to the home staker / nominator, but I guess some best practices like using a dedicated internet connection which can switch IP on demand would be a decent solution.

@lsaether says Sergei is doing some of this work, so I'm going to talk to him asap, but in the meanwhile is there any official roadmap/discussion on this? Any thoughts from you guys as potential collators / validators?

**Comment by keorn** [comment]
Segei is doing work on block production and on succinct proof parachain, not validator anonymity.

Validator identifies themselves primarily by a public key, so there is already pseudonimity there. As for network anonimity, we need indeed more resources/work. Max at Parity is working on sentry nodes, which will improve ability to stay secure as validator. Also Ximin and Federico will work on networking and deployment solutions for that.

**Comment by Swader** [comment]
Can you tag them to facilitate more discussion, or do you perhaps have some links to further discussion on this? I'm primarily interested in network anonimity, which seems like the sentry nodes use case.

**Comment by lsaether** [comment]
Ah, I guess I lumped anonymity into the succinct proof stuff that Sergei is working on.

Anyway, here is the relevant issue on Polkadot re sentry nodes: https://github.com/paritytech/polkadot/issues/264, Max is assigned there.

Also the README for the secure validator set-up details how the public / private nodes are set up: https://github.com/w3f/polkadot-secure-validator#structure

**Comment by lsaether** [comment]
Validator anonymity on the chain side is a research question. Validator anonymity on the network side is a technical challenge that is individual to each validator set-up and can solved by using sentries and/or VPNs. Considering this closed as a wiki issue.
