### ISSUE TITLE
Linking to tags across parity resources

### ISSUE THREAD

**Issue by Swader** [w3f/polkadot-wiki#745]
From danforbes:

From my POV, I just want to suggest that you have alignment among the resources you're linking to. Personally, I think it is always best to link to the latest tagged released, but if this is not possible, linking to master is fine too. If you decide to link to tagged versions, Rustdocs links should go to to substrate.dev/rustdocs, if you're linking to master use crates.parity.io.

**Comment by lsaether** [comment]
Ok so if I understand this, the actions we should take are:

- Change `crates.parity.io` -> `substrate.dev/rustdocs/{tag}`
- Update all tags to the current latest release

Beyond this we need a way to keep the links up to date to the current release. For this we can just have a CI job that checks the latest Substrate release and make sure all the substrate.dev links are up-to-date.

@danforbes Is there any part of your feedback that is not covered by the action items above?

**Comment by Swader** [comment]
Let's re-use the injector for this tag checking? I need to fix it still, want to do it this week

**Comment by danforbes** [comment]
Sounds good, @lsaether - I wrote a script to help us with this over on the substrate.dev Knowledge Base https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/blob/source/scripts/update-kb-rustdocs
