### ISSUE TITLE
Update Sidebar and Links

### ISSUE THREAD

**Issue by krichard410** [w3f/polkadot-wiki#753]
I'm thinking of reducing the number of pages on the Polkadot wiki and have the sidebar a bit more organized. 

For example, in the Nominator section, there are three separate pages that all fall underneath the same category. We could blend this pages into one, call it 'Nominator Guide' and inside we have different subsections (that used to be the separate pages). 
<img width="254" alt="Screen Shot 2020-08-04 at 4 40 00 PM" src="https://user-images.githubusercontent.com/36748441/89307248-2514f380-d671-11ea-9e1f-980e5cb2c8af.png">

If we do something like this, we would have links to each of the subsections in the right sidebar so that users can click on a subsection without much scrolling. Example: 'What is a nominator?', 'How to stop being a Nominator", etc. 
<img width="932" alt="Screen Shot 2020-08-04 at 4 41 06 PM" src="https://user-images.githubusercontent.com/36748441/89307377-4d045700-d671-11ea-8c4f-568386d50d12.png">

Of course though, depending on some of the material, having one page with multiple subsections could be a very long page, but I'm thinking we could do it for some of the smaller pages (like Nominator).

**Comment by lsaether** [comment]
I think it's a good idea to do this as long as we make it easier to find content, and not harder. Personally, I always use the search bar to find what I'm looking for, but people might be used to the side navigation. We should make sure it's kept intuitive to find what someone is looking for if we collapse pages into one. This might mean re-thinking some sections completely (like the governance guide sections which I never felt 100% comfortable putting into _maintain_.)

As far as large pages, I think it's fine as long as they're organized neatly.

**Comment by Swader** [comment]
Agreed - I never use the sidebar, there's too much stuff to look through, so I always default to search. I think normalizing the sidebar a bit would increase engagement with it

**Comment by krichard410** [comment]
Ah, I'm going to close this issue because this was already implemented.
