### ISSUE TITLE
Clarify onlineness

### ISSUE THREAD

**Issue by Swader** [w3f/polkadot-wiki#76]
It is not clear how often or how hard one would be penalized when offline.

We should make it very clear that:

- the size of the penalty depends on how many others are offline at the same time
- the frequency of the liveness ping is once per epoch, which is 4 hours currently. This means that you may be asked to chime in twice in 10 minutes (if you get asked at the end of one and the start of another epoch), or once in 7 hours. The unanswered question here is - what happens if I chime in as online once per epoch, but then still don't show up for work when selected? Is the "work" part counted as another "I'm online" ping?
- the ping is on-chain (state bloat possible?)

**Comment by lsaether** [comment]
This has been clarified I believe in validator / slashing guides. Now onlineness is considered either producing a block during an epoch or sending a heartbeat.
