### ISSUE TITLE
Sentries Deprecated 

### ISSUE THREAD

**Issue by m-saxemberg** [w3f/polkadot-wiki#761]
Based on this https://github.com/paritytech/substrate/issues/6845 sentries will become deprecated shortly, so an updated version of this section 
https://wiki.polkadot.network/docs/en/maintain-guides-how-to-setup-sentry-node
should be online before the client's breaking change goes live.

**Comment by Swader** [comment]
@fgimenez I'll defer to your devops expertise IRT setting up a good proxy / firewall etc - could you whip up some instructions for this?

**Comment by fgimenez** [comment]
Sure, we will coordinate with Parity for updating https://github.com/w3f/polkadot-secure-validator after the deprecation comes into play, we will propose there the new setup with all the required network settings, will ping you when ready.

**Comment by fgimenez** [comment]
Quick heads up, the changes were merged here https://github.com/w3f/polkadot-secure-validator/pull/89 the readme has been updated to describe the current setup https://github.com/w3f/polkadot-secure-validator/blob/master/README.md

**Comment by Swader** [comment]
I would like a detailed step by step process of setting things up manually (without Ansible) as well. I think there's a large group of people who might be interested in a more manual approach to learn what's happening. I'll set up a validator next week according to these instructions and test on my own skin.

**Comment by m-saxemberg** [comment]
I added the following document detailing NGINX configuration to hopefully replace the sentries page in the wiki 
https://github.com/w3f/polkadot-wiki/pull/1475
