### ISSUE TITLE
Which validators should we nominate?

### ISSUE THREAD

**Issue by krichard410** [w3f/polkadot-wiki#770]
After watching [this walkthrough video on how to nominate on Kusama](https://www.youtube.com/watch?v=NYs9oWAbzbE&list=PLOyWqupZ-WGuAuS00rK-pebTMAOxW41W8&index=14), it dawned on me that choosing which validators to nominate doesn't appear to be common knowledge on the wiki. In fact, it can be difficult to do this if you're nominating for the first time. 

I propose we include some more information on which validators should we nominate in section in the Nominator guide. A section that highlights how to use the target tool correctly and what things we should look for when nominating validators we may not know (like profit/era, own stake, etc.). Essentially a tip toolkit. 

I found already on the Nominator Guide that there was some information here: "When looking for validators to nominate, a nominator should pay attention to their own reward percentage for nominating a specific validator - as well as the risk that they bare of being slashed if the validator gets slashed.", but it would be nice to have some clear instructions and photos to help guide a user more. 

What are your thoughts on this? @Swader @lsaether @joepetrowski

**Comment by Swader** [comment]
This is an area of active development on the Apps UI and I'm not sure it's worth trying to explain it. A lot of nomination optimization tools are coming, third party, and I think we can just rely on people to check those out. 

The maximum I would do is go through the process of manually vetting a nominator - the stuff you mention basically - showing people how to read a nominator's info, how to check their history of changing the fee, how to check their setup and historical reliability, and just manually checking people like that, but without relying on Apps. Perhaps even write a simple script to specifically check a single validator and output some info, the common stuff we can pull from the chain.

**Comment by lsaether** [comment]
Well, the goal of the nominator is to maximize their profits while trying to minimize their risks. The Apps UI already has a way to auto-populate the nomination targets to maximize profits. So I think what we can do is to show users how to check the identity of the suggested nominators and what kind of policies they can check (i.e. does the validator cover any loss of funds if slashes occur?)

**Comment by wpank** [comment]
I'm actually working on a guide for nominators that expands on this. Basically a lot of factors for nominators to look into.

**Comment by laboon** [comment]
We also have this - https://wiki.polkadot.network/docs/en/maintain-nominator#what-to-take-into-consideration-during-nominating

but it could be expanded.  @wpank

**Comment by Swader** [comment]
@wpank let's talk more about this. I'm working with growth / Raul on a mini-course for nominator optimization now. Let's collab as much as possible?
