### ISSUE TITLE
*Feature* Scrap Staking excel sheet

### ISSUE THREAD

**Issue by krichard410** [w3f/polkadot-wiki#772]
In the Staking page [here](https://wiki.polkadot.network/docs/en/learn-staking#3-staking-rewards-distribution), there is an excel sheet linked that looks to be out of brand with Polkadot and can take a little while to load. This is more of an additional feature, but I think it would be neat to embed something a bit more aesthetic and clean within that section on the wiki page that users could play around with. What do you all think?

**Comment by wpank** [comment]
That spreadsheet I think is out of date and not the best estimate. We should remove that. 

Could point to something like [Staking Rewards](https://www.stakingrewards.com/asset/kusama/calculate), or embed something ourselves. 

This is something a lot of people have asked about, so would be good to add something around this.

**Comment by lsaether** [comment]
Yeah agreed on getting rid of the Excel sheet. 

I would be hesitant to suggest staking rewards proprietary algorithm as the only estimation tool though. It might be best to implement a small dashboard like this ourselves so we know that it's right and can keep it maintained.
