### ISSUE TITLE
Add information on Rococo

### ISSUE THREAD

**Issue by lsaether** [w3f/polkadot-wiki#775]
- [x] How to connect
- [x] How to get some tokens (is there a facuet?)
- [x] How to make a cross-chain transfer

**Comment by krichard410** [comment]
Should this go on a new page? I'm thinking of creating a similar page to this one here https://wiki.polkadot.network/docs/en/build-deploy-parachains and linking it on the Parachain page [here](https://wiki.polkadot.network/docs/en/learn-parachains#deploying-parachains)

**Comment by lsaether** [comment]
Yep - I think making something to replace that page would be great.
