### ISSUE TITLE
Generic-fy Phragmen into Election

### ISSUE THREAD

**Issue by Swader** [w3f/polkadot-wiki#785]
Looks like we're dropping Phragmen in some big ways due to the difference between the custom implementation and the original, so we'll need to update the phragmen page to reflect this some time soon: https://github.com/paritytech/substrate/pull/6886

**Comment by salmad3** [comment]
Let's evaluate this, will also address: https://github.com/w3f/polkadot-wiki/issues/2149

**Comment by salmad3** [comment]
https://wiki.polkadot.network/docs/learn-phragmen

needs some investigation - we can reach out to the right folks to clarify @a-jwc
