### ISSUE TITLE
Document Kusama time warp

### ISSUE THREAD

**Issue by Swader** [w3f/polkadot-wiki#791]

**Comment by lsaether** [comment]
Context: https://polkadot.network/kusamas-first-adventure/

**Comment by Swader** [comment]
I suggest we create a "Landmarks" page which would, vertical-roadmap-style, document all the big changes and landmarks the network has gone through. Could take a fair bit of work but would make a nice visual impact for sharing around, especially if Iggy applies some magic to it by giving us some Illustrator assets to plop onto that diagram. Thoughts?

**Comment by lsaether** [comment]
We already have a [timeline](https://guide.kusama.network/docs/en/kusama-timeline) page which we can re-purpose to use for landmarks. We can ask Iggy at some point for some nice graphics but I think first we need to beef up this page a bit more.
