### ISSUE TITLE
Header redesign

### ISSUE THREAD

**Issue by Swader** [w3f/polkadot-wiki#805]
Our header area is a bit crowded and starting to llook like the dev tools JS console:

![image](https://user-images.githubusercontent.com/1430603/90613576-da1ae480-e209-11ea-835c-360a430c59de.png)

![image](https://user-images.githubusercontent.com/1430603/90613380-945e1c00-e209-11ea-9a70-a2a3aa576212.png)

We should not nerf the search input as it's by far the most used feature on the wiki, but we should think about the second line as it's getting too crowded. Maybe a dropdown for the main category (Get Started, Learn, Build, Maintain), a link for Kusama, and a dropdown for Language? Skeptical about design for that but might be worth a go...

Alternatively, we could try moving the language selector next to the search bar, then it would all be flush with edges.

**Comment by krichard410** [comment]
@Swader do you think we can close this issue? Seems to be haven taken care of with the front page redesign

**Comment by Swader** [comment]
Yep
