### ISSUE TITLE
Updating Images/Instructions based on new Header

### ISSUE THREAD

**Issue by krichard410** [w3f/polkadot-wiki#808]
As Joe pointed out in the Polkadot Wiki channel, the navigation in the header has changed on polkadot.js.org/apps. I think we should go through and update any instructions/images. 

<img width="748" alt="Screen Shot 2020-08-21 at 8 22 50 AM" src="https://user-images.githubusercontent.com/36748441/90858949-81715600-e387-11ea-9c66-68d8ea400927.png">

Also noticed that for the Polkadot network, there are some new tabs underneath Developer, like Sign and verify and RPC calls, which weren't there before
<img width="375" alt="Screen Shot 2020-08-24 at 8 52 23 AM" src="https://user-images.githubusercontent.com/36748441/91012889-22aa1780-e5e7-11ea-94d4-98165b140b9c.png">

**Comment by Swader** [comment]
Let's identify a list of all pages where this needs to be updated. The 0.55 release was just tagged, which means this UI is coming to production on IPFS  (dotapps.io) within the day. By having a list of pages we need to update we can also focus on updating other content on those pages and maybe optimize the images a bit further (use https://imagecompressor.com/ for example) so we don't bloat git history.

**Comment by krichard410** [comment]
Possible list (can be altered too):
- https://wiki.polkadot.network/docs/en/claims
- ~https://wiki.polkadot.network/docs/en/learn-account-generation~ _edit: this has been updated_
- ~https://wiki.polkadot.network/docs/en/learn-account-restore~ _edit: this has been updated_
- ~https://wiki.polkadot.network/docs/en/learn-identity~ _edit: this has been updated_
- ~https://wiki.polkadot.network/docs/en/learn-balance-transfers~  _edit: this has been updated_
- ~https://wiki.polkadot.network/docs/en/learn-treasury~ _edit: this has been updated_
- ~https://wiki.polkadot.network/docs/en/learn-simple-payouts~  _edit: this has been updated_
- ~https://wiki.polkadot.network/docs/en/maintain-wss~  _edit: this has been updated_
- ~https://wiki.polkadot.network/docs/en/learn-nominator~ _edit: this has been updated_
- ~https://wiki.polkadot.network/docs/en/maintain-guides-how-to-nominate-polkadot~  _edit: this has been updated_
- https://wiki.polkadot.network/docs/en/maintain-guides-democracy
- ~https://wiki.polkadot.network/docs/en/maintain-guides-how-to-join-council~  _edit: this has been updated_
- ~https://wiki.polkadot.network/docs/en/maintain-guides-how-to-vote-councillor~  _edit: this has been updated_
Note these are all the pages on the Wiki that have images from the Polkadot JS UI

**Comment by krichard410** [comment]
From the Kusama guide:
- ~https://guide.kusama.network/docs/en/kusama-claims~ _edit: has been updated_
- ~https://guide.kusama.network/docs/en/kusama-endpoints~ _edit: has been updated_
- https://guide.kusama.network/docs/en/mirror-maintain-guides-how-to-validate-kusama
- ~https://guide.kusama.network/docs/en/mirror-maintain-guides-how-to-nominate-kusama~  _edit: has been updated_
- ~https://guide.kusama.network/docs/en/mirror-learn-identity~  _edit: has been updated_
- ~https://guide.kusama.network/docs/en/mirror-learn-treasury~  _edit: has been updated_
- ~https://guide.kusama.network/docs/en/maintain-guides-society-kusama~  _edit: has been updated_
- ~https://guide.kusama.network/docs/en/kusama-social-recovery~  _edit: has been updated_

**Comment by krichard410** [comment]
Do we also need to update any technical explainer videos?

**Comment by Swader** [comment]
Only if you have something new to say or have learned to dramatically improve the output quality somewhat (though not even then usually, it's okay to show progress). It's implied that stuff like videos goes out of date. Unless you have the source files of your videos and can easily drop in a replacement video of the UI without having to re-narrate it and do it all over, I'd leave it.

**Comment by ansonla3** [comment]
> * https://guide.kusama.network/docs/en/maintain-guides-society-kusama
> * https://guide.kusama.network/docs/en/kusama-social-recovery

These two should be up-to-date

**Comment by ansonla3** [comment]
@krichard410 anything else is missing? ;)

**Comment by krichard410** [comment]
@ansonla3  I think it's all good to me, I noticed:
- One image on https://wiki.polkadot.network/docs/en/learn-accounts
- A couple images on https://wiki.polkadot.network/docs/en/maintain-guides-how-to-nominate-polkadot
- a few images on https://wiki.polkadot.network/docs/en/maintain-guides-how-to-validate-polkadot
- a few images on https://wiki.polkadot.network/docs/en/maintain-guides-democracy
and that's it 👍
