### ISSUE TITLE
Time Delay Proxies

### ISSUE THREAD

**Issue by krichard410** [w3f/polkadot-wiki#813]
In the proxies page, we should have an explanation of time delay proxies, what they are, how to set it up, why you should consider setting one up yourself, some photos, etc.
Ref: https://github.com/paritytech/substrate/pull/6770

**Comment by salmad3** [comment]
Closing. See: https://github.com/w3f/polkadot-wiki/pull/2116#issuecomment-887179473; please reopen if otherwise.
