### ISSUE TITLE
Add interactive glossary

### ISSUE THREAD

**Issue by krichard410** [w3f/polkadot-wiki#815]
I think it would be neat and helpful to have a photo of the relay chain and to have some definitions on there hoverable. 

So for example, this photo:
<img width="921" alt="Screen Shot 2020-08-24 at 11 15 54 AM" src="https://user-images.githubusercontent.com/36748441/91026553-2f386b00-e5fb-11ea-9184-0b22e73e4a46.png">

We could embed within the glossary page and just have parts of the picture hoverable that shows the definition, or perhaps we could place this on the main polkadot intro/getting-started page. What are your thoughts?

**Comment by Swader** [comment]
Sure, but:

1. Might be too much work for too little payoff, not sure how much it brings to the table that a labeled diagram and searchable glossary already don't.
2. Might be hard to make work on mobile.

Other than those remarks I have nothing against the experiment.

**Comment by krichard410** [comment]
Hm I see your perspective actually, I'm going to close this Issue for now because I'm thinking of a different visual project to do with BABE/GRANDPA
