### ISSUE TITLE
Front page redesign

### ISSUE THREAD

**Issue by lsaether** [w3f/polkadot-wiki#823]
I met with Iggy from the design team and we discussed a bit on how we should focus the front page of both the Wiki and the Kusama Guide. The biggest area of improvement is around our CTAs: What are we telling readers of the wiki to do?

- To learn
- To maintain
- To build

Do we keep these sections or evolve them?

We should craft out sections of the front page specifically to attract these people and direct them to the relevant pages on the wiki. We should also reconsider our organization and how it makes sense to someone approaching it for the first time. Right now we heavily rely on search in order to find content - while the wiki is large, it is not so large that we can order it in a linear fashion.

Additionally, we can include some dynamic content on the front page in order to keep it fresh and encourage people to keep checking back in on the progress. Some ideas to do this include a "featured article of the day", a "recent news" section, and the "most recently edited article." Since the wiki is a static site it will need to update any of these when it is rebuilt. We could add a CI to ensure that the wiki is rebuilt at least once a day so we can always have a fresh article of the day.

**Comment by krichard410** [comment]
This is a great issue, and I am for changing the landing page so that it makes more sense. This issue also relates to #771 and the two could be merged into one CSS landing page revamp issue.

**Comment by krichard410** [comment]
@lsaether is it good to close this issue? Looks like there was a big redesign

**Comment by lsaether** [comment]
Yeah, there's some other ideas in this issue but it will be better to separate them and post new issues for each one.
