### ISSUE TITLE
Fix button redirect

### ISSUE THREAD

**Issue by krichard410** [w3f/polkadot-wiki#825]
If I'm on the page: https://wiki.polkadot.network/docs/en/learn-comparisons and I press the `Next` button, it brings me to the main landing page instead of the Build section.

**Comment by Swader** [comment]
This is because learn-relevant-links wasn't removed from the sidebar config, but was removed as a page. Any page we remove MUST also be removed in the sidebar - that's what the next/prev buttons use to navigate.
