### ISSUE TITLE
Be explicit when switching networks

### ISSUE THREAD

**Issue by lsaether** [w3f/polkadot-wiki#827]
For example, the first step of the Kusama claims guide should be "Make sure you're on the Kusama network by doing X, Y, Z." 

This is because Polkadot network is default on Apps.

**Comment by laboon** [comment]
@krichard410 I think this would be a good first issue for Majella, going to give it to her

**Comment by MajellaH** [comment]
All claims pages are updated. Link to old claims page deleted and linked to current pages.
