### ISSUE TITLE
Add tool for showing addresses on different networks 

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#836]
Similar to pubkeyToAddress.js in `utility-scripts`

```
(894) ~/web3/utility-scripts/src/misc $ node pubkeyToAddress.js  0x9a2145448b564cdbea678b32335ab08a1dbfda0bfd31ad11e6864b6c390e8b10
Substrate Address:
5FYo7cYWbjDFTQBUVUrZxRD8jZL2798k6jFgCYkTfTF1Bj1Q
Kusama Address:
G4QmvtPE6EBD3zvGBfcrNa8t9cFuowvZ76RbD2R9FTVvefv
Polkadot Address:
14V6FwoaTWUitwBzT7ua6a3HbBKfoSgtBDzAMqjpDYGXN9N5
```

We should have a place where users can enter, e.g. Kusama address and see their Polkadot address (and ideally their public key).  Code is in JavaScript so should be easy to add.

Shawn's page also has similar functionality.

**Comment by krichard410** [comment]
For my tutorial on DotLeap, I created a component similar to this. It could also be used as a reference in case anyone wants to look at it: https://dotleap.com/building-and-address-converter-page-polkadot/

**Comment by Swader** [comment]
They can do this in the extension and in the apps settings - this is not enough? I guess we could write a small widget we can plop onto a page.

**Comment by lsaether** [comment]
Shawn's page has exactly this functionality.

![image](https://user-images.githubusercontent.com/25539605/91614063-a93b5d80-e935-11ea-8a69-930e0605a5b5.png)

Do we still want an alternative?

**Comment by laboon** [comment]
Yes.  Shawn's page is great but a) not user friendly and b) hosted on his own github.  I'd also  prefer having something official to which we can point users.

**Comment by laboon** [comment]
Shawn's page also requires users to know the SS58 network prefix, and I would guess that > 95% of users don't even know what that is, let alone know what Polkadot's or Kusama's is without looking it up.
