### ISSUE TITLE
Remove list of wallets, set up alternative list

### ISSUE THREAD

**Issue by Swader** [w3f/polkadot-wiki#841]
Based on discussions in Riot, due to security and other implications we'll remove the list of wallets from the wiki. The wallets will be listed on Wallets.Review or another community platform instead and maintained by the community.

**Comment by lsaether** [comment]
I'm maybe missing a bit of context here - but why can we not just add a note to that page like this?

> This page is community maintained. The wallets below have not been audited or endorsed by the official Polkadot team.

**Comment by laboon** [comment]
Where did this come up in Riot?  I remember us discussing this but AFAIK we didn't come to a conclusion.

**Comment by krichard410** [comment]
Is this issue still relevant?

**Comment by laboon** [comment]
I talked with Dieter about improving this (we made some changes yesterday, will make some more soon) and what our responsibilities are.  Closing for now but @Swader please re-open if you think it's necessary.
