### ISSUE TITLE
Document that vested dots cannot be used to vote or interact with the chain in any meaningful way

### ISSUE THREAD

**Issue by Swader** [w3f/polkadot-wiki#845]

**Comment by wpank** [comment]
I think vested DOTs can be able to be used in governance, staking, etc 🤔

**Comment by lsaether** [comment]
Yeah they can, I think the only restrictions are anything that requires transfers like parachain deposits.

**Comment by laboon** [comment]
This seems incorrect @Swader , can you clarify?

**Comment by Swader** [comment]
Hmm I've been getting Unable to Pay Bond for any amount of DOT I try to vote for Council with for the past few days on some 2-year vested DOT. I'll have to look into it a bit deeper.

**Comment by laboon** [comment]
Weird, I'm getting that error message as well for Council voting.  But I am definitely staking with DOT that are still vesting.

This might be a bug.

**Comment by laboon** [comment]
I can vote on Referenda as well, just can't vote for Council.

**Comment by Swader** [comment]
I dug around a bit.

@laboon can you try executing "Unlock vested funds" on your account and seeing if it does anything? For me it didn't even though I had a non-zero amount available for unlocking. In order to really unlock funds I had to go through extrinsics -> vesting -> vest. Then I had more than 5 DOT and was able to vote for Council, which was needed because that vote locks up 5 DOT in reserve. Before you vest at least 5 DOT, you can't vote for Council, that was the problem.

So we have two things to check:

1. Is the Account-screen unlock-vested-funds option broken?
2. Is the problem fixed if you vest through extrinsics and then try to vote?

**Comment by laboon** [comment]
Yes, will do this soon...

**Comment by joepetrowski** [comment]
Yup exactly, requires a 5 DOT reservation, which is prevented by the lock.
