### ISSUE TITLE
When there are empty blocks, AURA kicks in. Documentation needed.

### ISSUE THREAD

**Issue by Swader** [w3f/polkadot-wiki#85]
During the shuffling, some blocks have no slot leader candidates. These slots used to remain empty under BABE, but with AURA which runs in constant time to catch up with those, they are handled. This has some ICMP implications too, given that queues can get filled up if a block is skipped.

We need a document about AURA. I'll see what I can do about that once I've digested the paper unless someone is already more familiar.

**Comment by Swader** [comment]
Paper: https://eprint.iacr.org/2018/1079.pdf

**Comment by Swader** [comment]
I'm on this.

**Comment by joepetrowski** [comment]
> AURA which runs in constant time to catch up

It's not like Aura is running separately to catch up. It's part of the BABE protocol now. It assigns a "Primary" based on the VRF (normal BABE) and a "Secondary" based on round robin (like Aura). When a block producer wins the VRF, it broadcasts a message to say that it's the primary. If no primary messages are received within some window, then the Secondary assignee produces the block.

Please tag me as a reviewer in your PR.

**Comment by Swader** [comment]
@joepetrowski what if latency causes the primary to come in after the secondary has already decided that the primary isn't coming? Is the primary validator subject to equivocation penalty?

**Comment by joepetrowski** [comment]
> @joepetrowski what if latency causes the primary to come in after the secondary has already decided that the primary isn't coming? Is the primary validator subject to equivocation penalty?

No, there would not be equivocation. Since the Primary is the function of randomness, it's normal to have multiple Primaries in a slot. Equivocation is only if the same author produces two blocks in the same slot.

What the next block author will do: If you receive two blocks of the same slot, one from a Primary and one from a Secondary, then you will choose to build on the one created by the Primary. If you receive blocks from two or more Primaries, then you will probably just build off the first one you imported. (CC @rphmeier or @andresilva)

**Comment by andresilva** [comment]
I'd prefer if we stopped referring to this as Aura blocks. I suggested using the naming of primary and secondary slots. At this point secondary slots aren't even picked using Aura's logic, so there's really no relationship. I wrote an overview of the current implementation here: https://github.com/paritytech/substrate/blob/master/core/consensus/babe/src/lib.rs#L17

We will always pick the chain that has the most primary blocks, in case of a tie it's effectively random, and should be resolved eventually (as one chain gets longer than the other).

**Comment by Swader** [comment]
The threshold being proportional to stake, is that a new development? I was explicitly told a week or so ago that all validators have the same threshold, regardless of stake. I'll try to find out who told me this.

Also IRT

>The fork choice rule is weight-based, where weight equals the number of primary blocks in the chain

Just need a clarification - does GRANDPA not factor into this _before_ the primary blocks? I.e. if some blocks were secondary in a chain but then finalized, and the finalized block on the chain with secondary blocks is a shorter distance away than the finalized block on the chain with primary blocks, does this not take precedence?

**Comment by andresilva** [comment]
@Swader Both BABE and GRANDPA substrate implementations support having weighted validators. But we are indeed setting all weights to 1 (see here for BABE: https://github.com/paritytech/substrate/blob/master/srml/babe/src/lib.rs#L562) and aren't using this feature (i.e. all validators have the same weight).

Yeah, so the fork choice rule for the whole system is (in this order):
1. Follow whatever chain includes the latest GRANDPA finalized block.
1. Follow the chain with the highest weight (i.e. most BABE primary blocks).

Whatever GRANDPA finalizes is canonical, regardless of BABE's fork choice rule, so yeah we could finalize a chain with less primary blocks. In practice though, we keep some distance from what we're trying to finalize and what is the best block, so by the time GRANDPA votes to finalize something the secondary blocks should have been re-orged out already.

**Comment by Swader** [comment]
Very good, thank you, that clears up a lot of things.
