### ISSUE TITLE
Host presentation slides 

### ISSUE THREAD

**Issue by lsaether** [w3f/polkadot-wiki#88]
We need a directory that hosts all the presentation slides for people to read, copy, remix and use.

**Comment by Swader** [comment]
What's the use case for this? People external to W3F or internal? If latter, the Slides on W3F's Google Drive could be adequate if we remind everyone to upload there.

**Comment by lsaether** [comment]
Yeah agreed, but we need a directory of all the links to these. Plus the couple slide templates that we have and give on request to ambassadors. The use case if for external people to find our presentation materials.

**Comment by Web3Foundation** [comment]
We already have something similar here https://github.com/w3f/Web3-collaboration/blob/master/meetups.md (2 presentations) and are working on a comprehensive community page, feel free to amend any other presentations here & add where relative to the wiki as well! @lsaether @Swader

**Comment by Swader** [comment]
@Web3Foundation where did this go? Did that community page happen? Perhaps something to be integrated with #32 aka [wiki community page](https://wiki.polkadot.network/docs/en/community)?

**Comment by krichard410** [comment]
Is this still a relevant issue?

**Comment by laboon** [comment]
I think this would be a good thing to do eventually - let's leave it open for now.

**Comment by krichard410** [comment]
Where would one get these presentation slides from? And which presentation materials should be public?

**Comment by Swader** [comment]
Presentation stuff we do for public meetups mainly. They will be in the Tech Ed / Talks folder on W3F's Google Drive
