### ISSUE TITLE
Compare to Dfinity

### ISSUE THREAD

**Issue by lsaether** [w3f/polkadot-wiki#89]

**Comment by Swader** [comment]
Hard to do given that they're closed source.

**Comment by sebastiendan** [comment]
Hi, the comparison page redirects to polkadot wiki home page. Is there a reason why it was removed?

https://wiki.polkadot.network/docs/en/learn-comparisons-dfinity

**Comment by Swader** [comment]
This is because we lack the manpower to do a fair and thorough comparison at this point in time, so we'd rather not keep inaccurate information in the public domain.
