### ISSUE TITLE
Commoditization of Trust

### ISSUE THREAD

**Issue by lsaether** [w3f/polkadot-wiki#91]
How does Polkadot make trust into a commodity? What does this mean on concrete terms? How can we move more towards a continuum of trust <-> trustless rather than the binary option of either full trust or no trust?

**Comment by lsaether** [comment]
Probably just needs an FAQ entry for this...

What is the commodification of trust?
> answer

**Comment by Swader** [comment]
I think this ties into governance and a relaxed concept of immutability. Should tie in nicely with Raul's new post on the motions in which the council saved some claims. It's also a good example of a spectrum of trust, given that the council is a small group with a lot of power (especially IRT treasury) but we've elected to trust them.
