### ISSUE TITLE
Document using Polkadot with package managers

### ISSUE THREAD

**Issue by wpank** [w3f/polkadot-wiki#934]
https://github.com/paritytech/polkadot/pull/1676

The Polkadot Binary has now been added to package managers. We should describe how to use this to install it system wide instead of downloading the binary.

**Comment by Swader** [comment]
Hey @wpank you working on this?

**Comment by Swader** [comment]
Adding myself, as discussed on Riot. [resource](https://medium.com/@martin_parity/e49b9895d6f2)

**Comment by salmad3** [comment]
If I'm not mistaken, most of these steps are spread out among the maintain docs
