### ISSUE TITLE
Algolia un-index Kusama

### ISSUE THREAD

**Issue by Swader** [w3f/polkadot-wiki#938]
@lsaether since you're the one in charge of the Algolia account for the wiki, can you tell them to unindex the *kusama* URL pattern? Otherwise we get stuff like this in search, which leads to a sidebar-less page.

![image](https://user-images.githubusercontent.com/1430603/92939279-dddb0900-f44d-11ea-95bd-aad3d948c22d.png)

**Comment by lsaether** [comment]
Yeah, will ask them to do that. 

However, I think the core of the problem is also related to #936 in that the pages are still being hosted on the website. This is the default behavior of Docusaurus so we'll need to do some tweaking to the build process to fix it.

**Comment by Swader** [comment]
Algolia only indexes the pages that are reachable somewhere via a link. So if we cut off that part and make them unlinked from everywhere, the problem *should* auto-resolve.
