### ISSUE TITLE
Make the prettier bot work on external PRs

### ISSUE THREAD

**Issue by lsaether** [w3f/polkadot-wiki#944]
Currently the prettier bot only works on PRs made on branches of this repository and not on forks / external PRs. The reason for this is the bot API key that is not exposed to forks of the repo. If we exposed it to forks, someone could fork the repository and alter the CI commands to print our secret API key. We need to come up with a way to solve this - but it involves some thinking and research.

**Comment by salmad3** [comment]
As a substitute, we will add `pretty-quick` as a pre-commit check that is generic.
We can revisit if necessary; please reopen if otherwise.
