### ISSUE TITLE
Kusama Society interface has been updated

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#965]
You can now use the UI to do all interactions, no need for raw extrinsics.

https://wiki.polkadot.network/docs/en/maintain-guides-society-kusama

**Comment by Swader** [comment]
What could you not do before that you can now?

**Comment by laboon** [comment]
Bidding no longer requires you to submit an extrinsic - you can do it right from the UI - https://polkadot.js.org/apps/#/society

We give instructions for doing this all via extrinsics here: https://wiki.polkadot.network/docs/en/maintain-guides-society-kusama#1-bid-phase

I believe candidacy and membership role functionality is also accessible via the UI, although I can't confirm that at this point.

**Comment by laboon** [comment]
@ansonla3 are you working on this?  if not I can take it.

**Comment by salmad3** [comment]
Content seems okay, and UI can be update. Will be addressed in: https://github.com/w3f/polkadot-wiki/issues/2390
