### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by Swader** [w3f/polkadot-wiki#986]
The Kusama Guide link on [this page](https://wiki.polkadot.network/docs/en/maintain-guides-how-to-nominate-polkadot) is broken. Obviously, our link checker is broken too.

This issue will be resolved by completing:

- [ ] Make link checker detect this
- [ ] Fix link

**Comment by ansonla3** [comment]
@Swader can we close this?

**Comment by Swader** [comment]
Sure
