### ISSUE TITLE
Add a Polkadot vs. Avalanche comparison

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#996]
I'm seeing a lot of questions about comparing Avalanche and Polkadot.   I know @Swader has a demo, perhaps it can be easily converted into a wiki page?

**Comment by Swader** [comment]
The page is already in progress.

**Comment by lsaether** [comment]
#844

**Comment by laboon** [comment]
Weird, I did a search for "avalanche" and it didn't show anything.
